### ISSUE TITLE
Adding a code of conduct to your project

### ISSUE THREAD

**Issue by arthurbuhl** [twindle-co/twindle#100]
A _code of conduct_ defines standards for how to engage in a community. It signals an inclusive environment that respects all contributions. It also outlines procedures for addressing problems between members of your project's community. For more information on why a code of conduct defines standards and expectations for how to engage in a community, see [github docs](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/adding-a-code-of-conduct-to-your-project).

**Comment by UnevenCoder** [comment]
Anyone taken this task up yet ?

**Comment by johnjacobkenny** [comment]
Go for it @UnevenCoder

**Comment by arthurbuhl** [comment]
F.Y.I. This can be easily implemented using the template here:

https://github.com/twindle-co/twindle/community/code-of-conduct/new

**Comment by johnjacobkenny** [comment]
> F.Y.I. This can be easily implemented using the template here:
> 
> https://github.com/twindle-co/twindle/community/code-of-conduct/new

Then I'll leave this to @proful

**Comment by UnevenCoder** [comment]
Cool all the bets @proful

**Comment by piratelicorne** [comment]
🤔 💭

**Comment by proful** [comment]
defferred
