### ISSUE TITLE
Help documentation for Twindle

### ISSUE THREAD

**Issue by Mira-Alf** [twindle-co/twindle#1003]
We currently use yargs for getting the command line argument values. yargs provides default help formatting and that currently looks like this:
![image](https://user-images.githubusercontent.com/64691316/105788092-cc7e3d80-5fa5-11eb-8bca-4c59af01f573.png)

* It was decided during the call that we can go with TLDR help format and that looks a little different.
* Also currently we have too many options combined into the same command:
    - Twitter: -i (list of comma separated tweet ids), -u (list of comma separated user ids), -n (number of tweets), -r (boolean flag to include answers to other's replies)
    - Github: -g (list of comma separated github MD file urls or a file path where github  MD file urls are listed)
    - Hackernews: -h (list of comma separated hackernews article ids ), -t ( number of top level comments ), -d ( levels of depth of replies to be included )
    - Readability: -a ( list of comma separated article urls )
* What if a user combines different sets of arguments? Should we throw an error or generate that content as well in the PDF file?

**Comment by johnjacobkenny** [comment]
How about using the command such that "twindle hn" filters arguments to those relevant to hn, "twindle GitHub" or "twindle gh" filters for GitHub, and so on?
