### ISSUE TITLE
Mock feature currently not working

### ISSUE THREAD

**Issue by Mira-Alf** [twindle-co/twindle#1007]
Mock feature is no longer working in the Twindle CLI application. This needs to be fixed. But here are some questions that needs clarifications:
* Originally Twitter was the only source which meant that the -m flag in the command line meant that the twitter.json file in the mock folder will get picked up for rendering the output file
* Now we have other sources like github, hackernews and other articles - so how do we leverage the mock flag?
* One possible solution could be to add the source flags without the values like:
  - `node . -i -m` will mean use twitter thread mock file
  - `node . -u -m` will mean use twitter user profile tweets mock file
  - `node . -g -m` will mean use github MD mock file
  - and so on
Any other suggestions for the mock flag? Or do we remove the flag completely?
@twindle-co/developer

**Comment by tr0mbl3y** [comment]
- whenever user type ```node -h/-g/-e``` without providing any ```id/url``` it should automatically generate the ```pdf/epub``` of default  hnews id/git url /article url
- for twitter case if no token is provided it should generate pdf of the mock json as well as if user press ```node -i/-u``` without providing anyother info default id/username should be used. doing this we will not need ```- m``` flag.
- right now i'm getting this error
![Screenshot from 2021-02-02 01-24-31](https://user-images.githubusercontent.com/72851843/106844550-d7844c80-66ce-11eb-8551-417583cab4b8.png)
