### ISSUE TITLE
Add Issue and pull request templates

### ISSUE THREAD

**Issue by arthurbuhl** [twindle-co/twindle#101]
Issue and pull request templates customize and standardize the information you'd like contributors to include when they open issues and pull requests in your repository. For more information, see "[About issue and pull request templates](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/about-issue-and-pull-request-templates)"

**Comment by pranavgoel29** [comment]
I am making one it will be updated time to time.

**Comment by arthurbuhl** [comment]
@pranavgoel29 any updates related to this? In case you are not working on this, please let us know so that someone else can take it up. Thanks!

**Comment by pranavgoel29** [comment]
I was a bit busy last week because of my college work😅, but now I am working on it.😄

**Comment by pranavgoel29** [comment]
## check these and tell me is there anything else which we can add ?

![image](https://user-images.githubusercontent.com/48860494/97071308-1f3e0700-15fd-11eb-8075-7e84c04830fc.png)

**Comment by arthurbuhl** [comment]
This looks good to me. Let get this rolling and we will keep updating it as needed.

**Comment by pranavgoel29** [comment]
Ok making a PR now
