### ISSUE TITLE
Add a EditorConfig file to the project

### ISSUE THREAD

**Issue by arthurbuhl** [twindle-co/twindle#103]
**EditorConfig** helps maintain consistent coding styles for multiple developers working on the same project across various editors and IDEs. The **EditorConfig** project consists of a file format for defining coding styles and a collection of text editor plugins that enable editors to read the file format and adhere to defined styles. **EditorConfig** files are easily readable and they work nicely with version control systems.

For more info: 

- [EditorConfig.org](https://editorconfig.org/)
- [Why development teams should use EditorConfig](https://medium.com/@edvinsantonovs/why-development-teams-should-use-editorconfig-f58011b1cc56)

**Comment by proful** [comment]
That will complicate for beginners. Will definitely add in future.

**Comment by proful** [comment]
in the future, it can be re-opened.

Now cleaning up issues.
