### ISSUE TITLE
Problem with local desktop PR

### ISSUE THREAD

**Issue by cankocman** [twindle-co/twindle#114]
warn: No match for commit 84690c850e986d19789c415009e5ce3177dfa16d found at https://github.com/twindle-co/twindle.git
warn: Are you sure you pushed 'HEAD' there?

Hİ, when i try to do my second PR i get these errors i've checked on stackoverflow and they say i have to push first. But when i try to push permission is denied remotely. Can anyone help ?
![resim_2020-10-15_110927](https://user-images.githubusercontent.com/49498453/96095139-e3a58d80-0ed6-11eb-9493-071ef81fe22b.png)

**Comment by arthurbuhl** [comment]
As mentioned in the [Documentation](https://github.com/twindle-co/twindle/issues/41), you needed to do sync your `forked` repo first with the `main` repo before making your local changes, like:

```sh
git remote add upstream https://github.com/twindle-co/twindle.git
git fetch upstream
git merge upstream/main
git push origin main
```

Then make your local changes and then do git add, commit and then finally do git push.

**Comment by tolgaerdonmez** [comment]
I'm facing the same problem. I synced the local with upstream, than made my changes, but same problem goes.
<img width="796" alt="image" src="https://user-images.githubusercontent.com/45141388/96132026-92ab8e80-0f02-11eb-97c5-c4cf484bec9e.png">

I cannot create a pull request from commit **f9f8bc7408841a3669b415e360f72ead11f8b918** to upstream

**Comment by Rakesh-4** [comment]
Hey, can you pls check whether ur local and remote repo is in sync via this command  `git status -uno  `.

**Comment by tolgaerdonmez** [comment]
> Hey, can you pls check whether ur local and remote repo is in sync via this command `git status -uno `.

It prints
`Your branch is up to date with 'origin/main'`

**Comment by Rakesh-4** [comment]
Nice. Then try to create a pull request via a web interface(If you had made any new changes). Are you still getting an error while doing that? If so pls let me know the error message

**Comment by tolgaerdonmez** [comment]
> Nice. Then try to create a pull request via a web interface(If you had made any new changes). Are you still getting an error while doing that? If so pls let me know the error message

I did successfully by using the github's website, but I'm wondering why it is not working from terminal. We'll see in future PR's, how will it go. @Rakesh-4 Thank you anyway

**Comment by Rakesh-4** [comment]
Nice. Post me that error let me have a look.

**Comment by tolgaerdonmez** [comment]
> I'm facing the same problem. I synced the local with upstream, than made my changes, but same problem goes.
> <img alt="image" width="796" src="https://user-images.githubusercontent.com/45141388/96132026-92ab8e80-0f02-11eb-97c5-c4cf484bec9e.png">
> 
> I cannot create a pull request from commit **[f9f8bc7](https://github.com/twindle-co/twindle/commit/f9f8bc7408841a3669b415e360f72ead11f8b918)** to upstream

That was the error I was getting from terminal, but none occurred using GitHub's website

**Comment by tolgaerdonmez** [comment]
<img width="784" alt="image" src="https://user-images.githubusercontent.com/45141388/96143216-90016700-0f0b-11eb-9ff6-28cad74d018d.png">
 
I was having this error, but none occurred in GitHub's website

**Comment by arthurbuhl** [comment]
As of February 2020, you can now use [GitHub CLI](https://github.blog/2020-02-12-supercharge-your-command-line-experience-github-cli-is-now-in-beta/) and then easily Create a pull request from command line like:

![](https://i.stack.imgur.com/X17nW.png)

**Comment by Rakesh-4** [comment]
It's not an error just a warning saying the changes you made isn't for remote server as it won't be available for others to pull your changes so you need to push you changes to the remote server first and the warning will go away.

**Comment by tolgaerdonmez** [comment]
Thanks guys, I'll try a dummy PR to solve this problem, as soon as I can.

**Comment by ad3rinto** [comment]
@johnjacobkenny can this be closed now since it is fixed? 😁

**Comment by johnjacobkenny** [comment]
Sure, please close if it's fixed!

**Comment by piratelicorne** [comment]
I can close it hehe.
