### ISSUE TITLE
Add Youtube, twitter Link in readme with icon

### ISSUE THREAD

**Issue by proful** [twindle-co/twindle#118]
Someone take the task and update the readme file with icon

Github: https://github.com/twindle-co/twindle
Twindle YT:		https://www.youtube.com/channel/UCKxUmbHq5P5pd5IyUiZ8MHA
Daily Standup Playlist:
https://www.youtube.com/watch?v=mveHORtiKx8&list=PLJ6Y8JfXAV--l82_UnUi4w7WEaYJhJFRQ

Twitter: https://twitter.com/twindleco

**Comment by UnevenCoder** [comment]
so u want img to go to the link ?

**Comment by proful** [comment]
yes

**Comment by UnevenCoder** [comment]
You can assign it to me 
done

**Comment by proful** [comment]
Go ahead and do it and send a pr

**Comment by mrsidverse** [comment]
I have added the links and have created a PR sir.

**Comment by UnevenCoder** [comment]
already done @mrsidverse
