### ISSUE TITLE
Anyone is working on a banner for the yt channel ?

### ISSUE THREAD

**Issue by UnevenCoder** [twindle-co/twindle#119]

**Comment by UnevenCoder** [comment]
You can make it responsive by following this template 
![image](https://user-images.githubusercontent.com/49345531/96101029-b0b2c800-0edd-11eb-85bc-7e379f94a707.png)

**Comment by proful** [comment]
Thanks for creating this issue.

YT banner is needed.

**Comment by pranavgoel29** [comment]
I can make one.

**Comment by UnevenCoder** [comment]
cool go ahead after making the banner forward it here for feedback :)

**Comment by pranavgoel29** [comment]
Ok

**Comment by proful** [comment]
@pranavgoel29 any update?

**Comment by pranavgoel29** [comment]
@proful will share it today today

**Comment by pranavgoel29** [comment]
![Artboard – 1](https://user-images.githubusercontent.com/48860494/97314625-e799be00-188d-11eb-9165-268143e202f2.png)


How it is?

@proful @johnjacobkenny @sarathkumar6 @piratelicorne

**Comment by shekhar10feb** [comment]
That's great!!

**Comment by pranavgoel29** [comment]
> That's great!!

Thank you 😄

**Comment by johnjacobkenny** [comment]
Looks good. And I suppose that once the branding is done, we would be able to finalize on the colors, but overall design is good.

**Comment by pranavgoel29** [comment]
> Looks good. And I suppose that once the branding is done, we would be able to finalize on the colors, but overall design is good.

Ok 🤗

**Comment by proful** [comment]
YT banner is good

**Comment by pranavgoel29** [comment]
> YT banner is good

Thank you
