### ISSUE TITLE
Anyone facing push issue while using GitKraken client

### ISSUE THREAD

**Issue by jahidhasanlinix** [twindle-co/twindle#144]
![Screenshot from 2020-10-15 19-44-55](https://user-images.githubusercontent.com/36171973/96137825-f04dd400-0f1e-11eb-9483-d61acc30013a.png)

**Comment by Rakesh-4** [comment]
You can push to the repo directly as you don't have the access. So create a pull request and someone will review ur changes and if it goes well it will merged

**Comment by jahidhasanlinix** [comment]
Yes, I did a pull request for new changes so after that, it will merge once it accepted, right

**Comment by Rakesh-4** [comment]
Yup

**Comment by mrsidverse** [comment]
Try Github desktop mate if you're facing such problems with Gitkraken. I didn't try with Gitkraken but it's working fine with Github Desktop.

**Comment by johnjacobkenny** [comment]
If this is fixed please close

**Comment by piratelicorne** [comment]
@jahidhasanlinix was it fix?

**Comment by johnjacobkenny** [comment]
Will close for now, @jahidhasanlinix please reopen if issue persists.
