### ISSUE TITLE
Link not working in readme

### ISSUE THREAD

**Issue by johnjacobkenny** [twindle-co/twindle#152]
![image](https://user-images.githubusercontent.com/19240564/96144134-7834dd80-0f21-11eb-9f50-b286d0c0c635.png)
This middle link in the readme, I'm not sure is working. Does anyone want to take this task?

**Comment by tolgaerdonmez** [comment]
I'm gonna take a look

**Comment by michaelcosj** [comment]
I created a pull request with a fix
There was a typo in the '<a>' tag href

**Comment by tolgaerdonmez** [comment]
It is also available in my pull request #150

**Comment by johnjacobkenny** [comment]
Okay @michaelcosj next time please take the task and then work on it, so that we don't have a duplication of work. I have to go with @tolgaerdonmez since he took the task first. Could you help review his PR?

I have another similar task that I will create in sometime, I will assign you @michaelcosj is that fine :smiley:

**Comment by michaelcosj** [comment]
Yhh, Thanks!

**Comment by johnjacobkenny** [comment]
> It is also available in my pull request #150

@tolgaerdonmez once we learn more about branching, we will know how to create separate PR for different tasks. That is the best way to do PR.

**Comment by johnjacobkenny** [comment]
Thanks @tolgaerdonmez @michaelcosj

**Comment by tolgaerdonmez** [comment]
> > It is also available in my pull request #150
> 
> @tolgaerdonmez once we learn more about branching, we will know how to create separate PR for different tasks. That is the best way to do PR.

Yeah, I agree so. It would be nice to decide a way of creating branches for PR's.. But it would be better after some amount of people become comfortable with sending regular ones.
