### ISSUE TITLE
Documentation: Path to follow for Second Pull Request

### ISSUE THREAD

**Issue by tusharkandpal** [twindle-co/twindle#156]
For a Second Pull Request, I used a  **Fork & Branch Workflow** mentioned below:

## Step 1: Fork the Repository
As you're making your 2nd PR, you already would have so you can skip this step.
For the sake of mentioning here is how you can do that:
Click on the **Fork** in the top right corner (below your profile icon) on https://github.com/twindle-co/twindle.

## Step 2: Make a Local Clone
- Open Git or any terminal you're using.
- Type `git clone <url of forked repo>` 
- It will by default create Git remote as **origin**
- `cd twindle` to enter the cloned repo.

## Step 3: Adding a Remote
**Syntax: `git remote add <remote> <url of original repo>`**
- `git remote add upstream https://github.com/twindle-co/twindle.git`

**Note:** Git Remote to pull changes from the original repo is **upstream** here. You can name it anything.
We will need it at a later point.

### 1) Create and Checkout
**Method 1**

- `git branch feature`
- `git checkout feature`
# OR
**Method 2**
(shorthand for Method 1)

**Syntax: `git checkout -b <branch-name>`**
- `git checkout -b feature`

Executing either method creates & switches to the new branch i.e feature.

### 2) Make changes to the files via any editor of your choice
Any changes made will be in the **feature** branch not main.

### 3) Commit those changes

- `git add .`
- `git commit -m "<message>"`

## Step 5: Pushing changes to GitHub

**Syntax: `git push <remote> <branch>`**
- `git push origin feature`

## Step 6: Opening a Pull Request
- GitHub makes it incredibly easy.
- Click on **Create Pull Request** button.
- Wait for it to be merged.

## Step 7: Cleaning Up After a Merged PR
- `git pull upstream main`
Pull changes from the original repo

**Note:** You need to switch the branch to main before deleting the feature branch (next command)
- `git branch -d feature`
Delete the feature branch locally
- `git push origin main`
Push changes to forked repo > main branch
- `git push origin --delete feature`
Delete the feature branch remotely

## Step 8: Keeping your Forked Repo in Sync with the Original Repo
(You need to do this time-to-time to update your Forked Repo > main branch)
- `git pull upstream main`
- `git push origin main`

# OR 
you can also do this step as mentioned in #41

**Comment by pranavgoel29** [comment]
There's a type in step 7 last line
it should be `git push origin --delete feature`


Good Work 🎉

**Comment by tusharkandpal** [comment]
Thanks, fixed it! 👍

**Comment by johnjacobkenny** [comment]
Great walkthrough @tusharkandpal :partying_face:

**Comment by tusharkandpal** [comment]
Thanks, @johnjacobkenny 😃

**Comment by EYRAM565** [comment]
good

**Comment by tolgaerdonmez** [comment]
Awesome, good work!

**Comment by viraj-patil** [comment]
Great work !

**Comment by jahidhasanlinix** [comment]
Great !

**Comment by proful** [comment]
Awesome @tusharkandpal 👍

**Comment by piratelicorne** [comment]
This was referenced in the FAQ document and updated in the PR #201  ✅
