### ISSUE TITLE
Guide for 2nd pull request using git bash

### ISSUE THREAD

**Issue by naveenkala** [twindle-co/twindle#163]
First Install git to your machine[DOWNLOAD HERE](https://git-scm.com/downloads)<h1>
![step0](https://user-images.githubusercontent.com/65217331/96152021-ae765b00-0f29-11eb-8bfb-cccb1778d614.jpg)

STEP 1:
![step1](https://user-images.githubusercontent.com/65217331/96152124-d239a100-0f29-11eb-95b0-e93c503da818.jpg)

STEP 2:
![step2](https://user-images.githubusercontent.com/65217331/96152198-e9788e80-0f29-11eb-8645-4e57b8f5812a.jpg)

STEP 3:
![step3](https://user-images.githubusercontent.com/65217331/96152232-f301f680-0f29-11eb-9043-90c75cd9ec00.jpg)

STEP 4:
![step4](https://user-images.githubusercontent.com/65217331/96152435-2c3a6680-0f2a-11eb-82cc-729a60770e21.jpg)

STEP 5:
![step5](https://user-images.githubusercontent.com/65217331/96152466-33fa0b00-0f2a-11eb-97f7-9069aee51eff.jpg)

STEP 6:
![step6](https://user-images.githubusercontent.com/65217331/96152491-3bb9af80-0f2a-11eb-8bf1-a22e8e74d427.jpg)

STEP 7:
![step7](https://user-images.githubusercontent.com/65217331/96152550-4aa06200-0f2a-11eb-8f03-c704626827b4.jpg)

STEP 8:
![step8](https://user-images.githubusercontent.com/65217331/96152571-50964300-0f2a-11eb-95f0-7c1c27154a5b.jpg)

STEP 9:
![step9](https://user-images.githubusercontent.com/65217331/96152590-55f38d80-0f2a-11eb-9149-aa72cfdfb85b.jpg)

STEP 10:
![step10](https://user-images.githubusercontent.com/65217331/96152607-5b50d800-0f2a-11eb-8f86-afdc67c90453.jpg)

STEP 11:
![step11](https://user-images.githubusercontent.com/65217331/96152642-63107c80-0f2a-11eb-9a14-a5df8f3cab8e.jpg)

**Comment by KKhosla7** [comment]
If anyone like the video version

[[Watch the video](https://youtu.be/7ls6wDZk29g)]

**Comment by johnjacobkenny** [comment]
Thanks @naveenkala this is a very useful documentation 🥳

**Comment by proful** [comment]
@naveenkala very good video. Please upload in the twindle channel.

**Comment by naveenkala** [comment]
> @naveenkala very good video. Please upload in the twindle channel.

Sorry, I only clicked photos of the process. But many of our members have already uploaded video tutorials 😊
From next time I will make sure.

**Comment by proful** [comment]
@KKhosla7  Please upload your video on YT channel. DM me your email to add into Twindle channel.

**Comment by piratelicorne** [comment]
This was referenced in the FAQ document and updated in the PR #201  ✅

**Comment by naveenkala** [comment]
> @KKhosla7 Please upload your video on YT channel. DM me your email to add into Twindle channel.

Nevermind I have created a video by attaching my screenshots.
https://youtu.be/cBigFcoAXZg

**Comment by KKhosla7** [comment]
@proful I've already uploaded the video in the YouTube channel.

https://youtu.be/7ls6wDZk29g. Sharing my email id in DM.

**Comment by piratelicorne** [comment]
closing the issue, but it's referenced in documentation 🏆
