### ISSUE TITLE
team.md styling better

### ISSUE THREAD

**Issue by UnevenCoder** [twindle-co/twindle#168]
Let's create a fixed format for people to follow

Name can be a link to github too , country , years of experience , and some special fact 👍 

lemme know what u think

**Comment by johnjacobkenny** [comment]
Great suggestion. 👌

**Comment by UnevenCoder** [comment]
and can be in a list form too .. to keep stuff uniform and looking good

**Comment by johnjacobkenny** [comment]
Share a sample and let others comment too

**Comment by RafaelBatman55** [comment]
Sounds good! This way will be more organized.

**Comment by UnevenCoder** [comment]
![image](https://user-images.githubusercontent.com/49345531/96162940-dc57a180-0f21-11eb-9bf2-0af7bc087978.png)

Something similar to this 

We can maybe change the first one in Intermediate by the permission of the author to match the scheme

**Comment by UnevenCoder** [comment]
To understand the changes showing the current state
![image](https://user-images.githubusercontent.com/49345531/96163678-dca46c80-0f22-11eb-9299-e9f853783fab.png)

**Comment by tolgaerdonmez** [comment]
> ![image](https://user-images.githubusercontent.com/49345531/96162940-dc57a180-0f21-11eb-9bf2-0af7bc087978.png)
> 
> Something similar to this
> 
> We can maybe change the first one in Intermediate by the permission of the author to match the scheme

It's okay, I'll match the scheme :), good suggestion btw.

**Comment by UnevenCoder** [comment]
Created the PR , will wait for further feedback and will imply the changes later today or tomorrow :)

**Comment by proful** [comment]
Very good idea

**Comment by UnevenCoder** [comment]
Should I add a comment in team.md to let new people know the format

**Comment by johnjacobkenny** [comment]
@Rakesh-4 has this suggestion

![image](https://user-images.githubusercontent.com/19240564/96270049-c82aa780-0fe8-11eb-8a6f-efd950e98b6f.png)

**Comment by UnevenCoder** [comment]
isn't table kind of over kill .. whats ur opinion ?

**Comment by Rakesh-4** [comment]
Just a quick suggestion am happy with anything and have no issues. Many ppl are already updating and creating PR(on team.md) so it would be better to come to the conclusion.

I won't be available till tomorrow can't reply. Thanks.

**Comment by johnjacobkenny** [comment]
> isn't table kind of over kill .. whats ur opinion ?

Table is fine, point is that it should be easy to read through. Anything is fine

**Comment by UnevenCoder** [comment]
Yup lets maybe take vote .. which ever you[all of the ppl reading this] prefer write it down below :) 

I have no issues with any

**Comment by UnevenCoder** [comment]
> > isn't table kind of over kill .. whats ur opinion ?
> 
> Table is fine, point is that it should be easy to read through. Anything is fine

Cool so lets go with it .. anyone else wants to add anything to the discussion  

What ever you [all of the ppl reading ] think give ur thoughts below

**Comment by tusharkandpal** [comment]
you can add a section **Place** assuming that everyone is mentioning their place

**Comment by Rakesh-4** [comment]
@johnjacobkenny if you guys have decided on what format to go with. please let me know because am gonna pull the latest changes and will update the team.md according to that so my PR can be closed. Thanks

**Comment by johnjacobkenny** [comment]
I think we have a few yes votes, you can go for it @Rakesh-4

**Comment by Rakesh-4** [comment]
So should I update other changes into table format?

> I think we have a few yes votes, you can go for it @Rakesh-4

**Comment by johnjacobkenny** [comment]
Yep! If you're doing it now, I'll merge quickly. Should create conflicts for everyone else in the PR queue 🥳

**Comment by Rakesh-4** [comment]
Ok.

**Comment by Rakesh-4** [comment]
@johnjacobkenny pls check now hope I didn't miss out any info

**Comment by johnjacobkenny** [comment]
I can't find the pr

**Comment by Rakesh-4** [comment]
> I can't find the pr

#221

**Comment by johnjacobkenny** [comment]
Okay done! Next time in the pr just mention in the description "closes #abc" with abc being issue number

**Comment by Rakesh-4** [comment]
> Okay done! Next time in the pr just mention in the description "closes #abc" with abc being issue number

I forgot to do that my bad
