### ISSUE TITLE
Enabling required reviews for pull requests

### ISSUE THREAD

**Issue by arthurbuhl** [twindle-co/twindle#171]
### Overview

Repository administrators can enforce required reviews so that pull requests must have a specific number of approving reviews before they are merged. This will help in better coordination and making sure only valid reviewed PRs are only merged.

For more info: [Enabling required reviews for pull requests](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/enabling-required-reviews-for-pull-requests)

### Status

_Open For Discussion_

**Comment by johnjacobkenny** [comment]
Sounds good! @proful @proful

**Comment by proful** [comment]
Can you @johnjacobkenny enforce 2 reviewer please?

**Comment by johnjacobkenny** [comment]
@proful I can't see the option mentioned in the link. Maybe access is restricted. Please take a look

**Comment by proful** [comment]
I have enforced reviews @johnjacobkenny @arthurbuhl

Watch out for any issues

**Comment by johnjacobkenny** [comment]
Yes it is working @proful. The reviewers though are only the people with write access. Might be a bottleneck with just us 3.

**Comment by proful** [comment]
I thought anyone. Not?

Can you ask someone else to check

**Comment by arthurbuhl** [comment]
This doesn't seem to be working properly. Me & @PrasoonPratham approved #190, but its still saying

```
At least 2 approving reviews are required by reviewers with write access. 
```

**Comment by proful** [comment]
![image](https://user-images.githubusercontent.com/354596/96225761-4aad6a00-0fdd-11eb-860e-c1496d25e473.png)

Yes any solution?

**Comment by arthurbuhl** [comment]
I think we need to look into [Repository permission levels for an organization](https://help.github.jp/enterprise/2.11/user/articles/repository-permission-levels-for-an-organization/) and upgrade few members to Team Maintainer or Collaborators roles.

**Comment by johnjacobkenny** [comment]
@proful please take a look

**Comment by proful** [comment]
Thanks @arthurbuhl I read the organization. Looks good I will try it.

**Comment by piratelicorne** [comment]
🏆

**Comment by proful** [comment]
The manual process is good enough

in the future, it can be re-opened.

Now cleaning up issues.
