### ISSUE TITLE
Documentation: Your Second Pull request using Github Desktop

### ISSUE THREAD

**Issue by nishanknavelkar** [twindle-co/twindle#177]
PROCESS OF DOING YOUR SECOND PULL REQUEST USING GITHUB DESKTOP

STEPS 
1.	Download and install Github Desktop , the instructions to set it up can be found here https://docs.github.com/en/free-pro-team@latest/desktop/installing-and-configuring-github-desktop/installing-github-desktop
2.	Once you authorize it by signing in it should show you your forked repositories. 
![image](https://user-images.githubusercontent.com/48888656/96177474-90b9ed80-0f4b-11eb-8a9a-ff711ccd8511.png)

3.	Click it and then go ahead and clone it. ( This will save a copy of all files on your desktop locally so that you can still access the copy even without being connected through internet) 
![image](https://user-images.githubusercontent.com/48888656/96177571-b0511600-0f4b-11eb-98c9-bc4501bdb972.png)

4.	Next step is to choose a destination where the file needs to be stored. In My case I have made a floder named Twindle in the E:\ drive(You can keep it as default path would be in the github folder in documents)
![image](https://user-images.githubusercontent.com/48888656/96177618-c2cb4f80-0f4b-11eb-9c07-9b91a34e23b8.png)

5.	Next step is to click Clone and the whole project files will appear at the chosen location.

6.	Since we want to contribute to the parent project we click continue.
![image](https://user-images.githubusercontent.com/48888656/96177678-d70f4c80-0f4b-11eb-87b5-40dba6bccb50.png)

7.	Your screen should now look something like this, 
![image](https://user-images.githubusercontent.com/48888656/96177709-e42c3b80-0f4b-11eb-812e-e14f8b6750e0.png)

8.	Next step would be to make changes and push those changes to the main project.

9.	We open the Project from Visual Studio Code ( You will need to download this)

10.	Open the project in VS Code , it should look something like this, 
![image](https://user-images.githubusercontent.com/48888656/96177757-f908cf00-0f4b-11eb-8b5e-afe41e1c8042.png)

11.	Open firstpr, open your already created pull request and modify the contents and save them.

12.	After Saving the changes the github desktop app shows the changes , 
![image](https://user-images.githubusercontent.com/48888656/96177787-058d2780-0f4c-11eb-8440-de79478fc30c.png)

a.	The changes that have been made .
b.	Add the update title and describe the changes if needed.
c.	Commit to main.

13.	After commiting you need to push the changes to the main branch. 

![image](https://user-images.githubusercontent.com/48888656/96177837-19d12480-0f4c-11eb-90b3-2e6ba9032bd2.png)

14.	Go to your fored repo and create a pull request. 
![image](https://user-images.githubusercontent.com/48888656/96177867-2786aa00-0f4c-11eb-8bb0-9eeef79c72c4.png)

15.	Done.
![image](https://user-images.githubusercontent.com/48888656/96177905-379e8980-0f4c-11eb-9867-02102c8ec0fe.png)

**Kindly Leave comments and Let me know if this method is correct**

**Comment by KiranDon** [comment]
Clearly explained.... Thanks

**Comment by piratelicorne** [comment]
This was referenced in the FAQ document and updated in the PR #201  ✅

**Comment by piratelicorne** [comment]
closing the issue because it was referenced in documentation. 🏆
