### ISSUE TITLE
Explore Figma and do initial design of twindle homepage

### ISSUE THREAD

**Issue by sarathkumar6** [twindle-co/twindle#184]
As a designer, I want to explore the high-level features of Figma and design the twindle home page mock up

![image1](https://user-images.githubusercontent.com/354596/96359749-09929280-1162-11eb-8424-005ab1b6bd24.png)

![image0](https://user-images.githubusercontent.com/354596/96359748-0697a200-1162-11eb-89d8-d52e2deabce1.png)

[My thoughts Youtube Link](https://youtu.be/7cJIYNB2pNo)  

[Great start]( https://madhusudanbabar.github.io/twindle-web/) by @madhusudanbabar

**Comment by sarathkumar6** [comment]
@vasudeveloper001 Here is the issue to look into figma and come up with intial design of twindle UI page.

For awareness @proful @johnjacobkenny

**Comment by johnjacobkenny** [comment]
There is a suggestion to consider color scheme, etc before jumping into this

**Comment by sammjainn** [comment]
Yes, how about let's finalise the logo or the color scheme before designing homepage, banners and thumbnail etc.

**Comment by proful** [comment]
Let's discuss this on call today

**Comment by teckiegeek** [comment]
I would to suggest that we novice get paired up based on our availability to watch those the experts as you work via a video call. It's the fastest way to learn for me.

**Comment by proful** [comment]
Discord is better for that purpose. Keep encouraging others to have a call.

**Comment by UnevenCoder** [comment]
As @sarathkumar6  has told previously -

- Discussing the brand colors before hand 
- Maybe get some basic illustrations down
- Discuss what all stuff should be on the site
- Amount of pages built specific (about ,payment etc...)

Directly jumping into design is not a good idea

**Comment by manohar52** [comment]
I came across a website : [https://threadreaderapp.com/](url).
We could look to it for reference.

**Comment by UnevenCoder** [comment]
True that's a great idea

**Comment by frankiefab100** [comment]
@proful @sarathkumar6 
Here's a UI design I came up with. Constructive criticism and ideas are welcome for further iteration.

![Twindle Landing Page](https://user-images.githubusercontent.com/46662771/96950866-3092f080-14e3-11eb-8cc2-1ba1d401abdf.png)

**Comment by johnjacobkenny** [comment]
For me it makes sense to merge the how to use and the actual usage into one section so that it is immediately clear to anyone using it. Locality of the instructions and the usage.

**Comment by proful** [comment]
@frankiefab100 [my feedback](https://youtu.be/X2a-gftJRWM)

**Comment by JoelVinayKumar** [comment]
Are submissions still open ?

**Comment by vasudeveloper001** [comment]
> Are submissions still open ?

Yes @JoelVinayKumar. It is still open. Take your time.

**Comment by JoelVinayKumar** [comment]
https://www.figma.com/file/34YX1uk6ZVhQWVzLyjzUdG/Twindle?node-id=0%3A1

![Home - Light Mode](https://user-images.githubusercontent.com/16177724/97005129-9fac2b80-155b-11eb-981d-fe0a072ffab5.png)
![Team](https://user-images.githubusercontent.com/16177724/97005144-a3d84900-155b-11eb-9440-cd028916485e.png)
![Home - Dark Mode](https://user-images.githubusercontent.com/16177724/97005151-a63aa300-155b-11eb-8232-521c7955d53b.png)
![Team - Dark Mode](https://user-images.githubusercontent.com/16177724/97005159-a89cfd00-155b-11eb-9b70-31a9b8f3b9c8.png)

**Comment by proful** [comment]
@JoelVinayKumar please watch my feedback for Frankie and update your design on the same line.

Thanks very much for the submissions

**Comment by frankiefab100** [comment]
@proful how do you see this new design?

![Twindle Landing Short(1)](https://user-images.githubusercontent.com/46662771/97039751-d175c000-1564-11eb-81c9-85e92ebe9a58.jpg)

**Comment by vasudeveloper001** [comment]
This is the pre-launch design for landing page. I have changed the background and removed the different color variation for header, footer, main section banner and other sort of design for starters. It's just one color theme layout.

The highlighted menu will be in white color. The rest in light variant of background color. The circle is there as a placeholder for logo. I think we should go with logo having no background in circle. Will be designing other pages as well.

Your opinion @johnjacobkenny @proful @JoelVinayKumar is welcome.

![Pre-Launch Design](https://user-images.githubusercontent.com/56103269/97070381-835ccd00-15f5-11eb-8cb2-59744b1e675b.png)

**Comment by vasudeveloper001** [comment]
## Modified Design with font changed to Open Sans:

### Post-Launch Design
![Post-Launch Modifed Design](https://user-images.githubusercontent.com/56103269/97088437-761ffc80-164e-11eb-8b6c-a04aebadda50.png)

### Pre-Launch Design
![Pre-Launch Modified Design](https://user-images.githubusercontent.com/56103269/97088438-77e9c000-164e-11eb-9d3b-0e34c031d6d9.png)

**Comment by sarathkumar6** [comment]
@vasudeveloper001 Appreciate the thought  of providing the option i.e., pdf in the post-launch UI.

**Comment by vasudeveloper001** [comment]
@sarathkumar6 It's something @JoelVinayKumar did in his first design. I simply applied it in mine as well.

**Comment by proful** [comment]
Initial design finalized. closing this ticket.
