### ISSUE TITLE
Create Youtube Thumbnail

### ISSUE THREAD

**Issue by proful** [twindle-co/twindle#187]
Figure out which resolution needed.

**Comment by Harsha-Ambati** [comment]
1280 x 720  would be best..

**Comment by arthurbuhl** [comment]
Google recommend for custom thumbnails:

- Have a resolution of 1280x720 (with minimum width of 640 pixels).
- Be uploaded in image formats such as JPG, GIF, or PNG.
- Remain under the 2MB limit.
- Try to use a 16:9 aspect ratio as it's the most used in YouTube players and previews.

For more info: [Add video thumbnails](https://support.google.com/youtube/answer/72431?hl=en)

**Comment by proful** [comment]
Any one wants to create something?

**Comment by UnevenCoder** [comment]
Sure who ever is making can keep the 16:9 ratio in mind & make it so such that a simple thing can be changed for each vid like day - number gap

Don't you think we should a branding folder with all the banner logo etc so anybody working on something like this will be a + .. will create an issue

**Comment by johnjacobkenny** [comment]
I could do it, but I want to let someone else step up and take the responsibility. One way to do it would be to create an svg file in Inkscape with the design and some sample text added. This could then be added to the repo as @UnevenCoder suggested. From there anyone could reuse it for videos.

**Comment by UnevenCoder** [comment]
> I could do it, but I want to let someone else step up and take the responsibility. One way to do it would be to create an svg file in Inkscape with the design and some sample text added. This could then be added to the repo as @UnevenCoder suggested. From there anyone could reuse it for videos.

I think I will do it since noone took it up yet 

I will prepare it in canva and save to .svg :)

**Comment by SunnyDev7** [comment]
yeah i would like to do it, btw i haven't done it before but will give my best!!!

**Comment by SunnyDev7** [comment]
i guess we can do it together what you say @UnevenCoder

**Comment by UnevenCoder** [comment]
Sure you on discord ? If so .. my id is Ameen#0112

Lets chat there :)

**Comment by tusharkandpal** [comment]
I can also contribute.. if needed 🙂

**Comment by UnevenCoder** [comment]
Cool let's talk on discord what say .. your username ?

**Comment by SunnyDev7** [comment]
i sent u a request @UnevenCoder. And yeah sure @tusharkandpal.

**Comment by tusharkandpal** [comment]
Discord id Tushar#7450

**Comment by UnevenCoder** [comment]
Accepted & sent Tushar

**Comment by Akshay2996** [comment]
Just a Suggestion!

If you want to create a **Youtube Thumnail** try out **[Canva](https://www.canva.com/)**

It has many templates for Youtube Thumnail which we can leverage ourselves with.

Cheers🍻

**Comment by ad3rinto** [comment]
first attempt.

![twindle](https://user-images.githubusercontent.com/46092157/96311317-1e0b4980-1001-11eb-8a80-1289abeca49d.png)!

**Comment by johnjacobkenny** [comment]
@UnevenCoder please coordinate among the volunteers and take this forward

**Comment by UnevenCoder** [comment]
> @UnevenCoder please coordinate among the volunteers and take this forward

Doing it 😃

**Comment by proful** [comment]
in the future, it can be re-opened.

Now cleaning up issues.
