### ISSUE TITLE
Create twindleco twitter banner

### ISSUE THREAD

**Issue by proful** [twindle-co/twindle#188]
Use correct resolution

**Comment by tusharkandpal** [comment]
I can give it a try🙋🏻‍♂️

**Comment by johnjacobkenny** [comment]
Go for it!

**Comment by tusharkandpal** [comment]
![Website Launch Rocketship Twitter Header](https://user-images.githubusercontent.com/66052835/96240734-e8de0780-0fbe-11eb-96df-b948a69737e6.png)

Any feedback is appreciated. 😄

**Comment by johnjacobkenny** [comment]
Logo could be bigger? Just my thought 🙂

**Comment by tusharkandpal** [comment]
![Website Launch Rocketship Twitter Header (1)](https://user-images.githubusercontent.com/66052835/96243110-e9c46880-0fc1-11eb-8723-af54d133c6fe.png)

Fixed it!

**Comment by johnjacobkenny** [comment]
Ask for feedback by sharing this link with the group :smiley:

**Comment by tusharkandpal** [comment]
ok 😄

**Comment by teckiegeek** [comment]
Great job!

**Comment by UnevenCoder** [comment]
Thats beautiful good job !

**Comment by niveth09** [comment]
Great work!

**Comment by niveth09** [comment]
> Use correct resolution
I want to give it a try. May I know the correct resolution?

**Comment by tusharkandpal** [comment]
Recommended dimensions are usually 1500 x 500 pixels @niveth09

**Comment by proful** [comment]
See your banner in action

https://mobile.twitter.com/twindleco

**Comment by tusharkandpal** [comment]
Looks Cool!! 😄 😄

**Comment by niveth09** [comment]
![Untitled design (1)](https://user-images.githubusercontent.com/19762119/96287408-82c5a480-0fff-11eb-8383-37a9371a242a.png)

**Comment by johnjacobkenny** [comment]
Thanks @niveth09 for the contribution it looks good too!

**Comment by tusharkandpal** [comment]
Amazing work!! 👍 @niveth09

**Comment by niveth09** [comment]
Thanks @tusharkandpal

**Comment by frankiefab100** [comment]
I will work on this tomorrow 👍

**Comment by piratelicorne** [comment]
both are cute! 🥳

**Comment by sarathkumar6** [comment]
@niveth09 @tusharkandpal Good job on the banner. A few things to consider when designing banner or logo are the banner or logo play a vital role in the branding of the product and helps to market it better. Here are some useful links to come up with better color creativity to apply on the thoughts. Please give it a read. @frankiefab100  Let me know your thoughts as a Visual Designer.

https://blog.bannersnack.com/color-combinations-in-display-ads/
https://www.esigns.com/effective_sign_design_tips.html
https://conceptdrop.com/blog/60-color-theory-the-psychology-of-color-marketing-and-branding/

**Comment by frankiefab100** [comment]
@sarathkumar6 that's definitely true. I will submit my own design soon.

**Comment by niveth09** [comment]
![We are launching](https://user-images.githubusercontent.com/19762119/97070310-f7e33c00-15f4-11eb-9715-7499c344bb4d.png)

**Comment by JoelVinayKumar** [comment]
Hi @niveth09  your first iteration looks very fabulous. Bright colours always inspire a person. My only suggestion is to stick to Blue theme so that we are close to Twitter

**Comment by niveth09** [comment]
> Hi @niveth09 your first iteration looks very fabulous. Bright colours always inspire a person. My only suggestion is to stick to Blue theme so that we are close to Twitter

Thank you @JoelVinayKumar  for the compliment. I have tried the blue theme.
![Untitled design (10)](https://user-images.githubusercontent.com/19762119/97077826-7a272c80-1604-11eb-864b-8bfd64193479.png)

**Comment by frankiefab100** [comment]
![Twindle Twitter cover](https://user-images.githubusercontent.com/46662771/97080193-9077bd00-15f1-11eb-9e77-092dbe8fd16e.jpg)

**Comment by JoelVinayKumar** [comment]
Great update @niveth09

**Comment by shekhar10feb** [comment]
> 
> 
> @niveth09 @tusharkandpal Good job on the banner. A few things to consider when designing banner or logo are the banner or logo play a vital role in the branding of the product and helps to market it better. Here are some useful links to come up with better color creativity to apply on the thoughts. Please give it a read. @frankiefab100 Let me know your thoughts as a Visual Designer.
> 
> https://blog.bannersnack.com/color-combinations-in-display-ads/
> https://www.esigns.com/effective_sign_design_tips.html
> https://conceptdrop.com/blog/60-color-theory-the-psychology-of-color-marketing-and-branding/

Thank you for sharing this and these banners are looking great

**Comment by niveth09** [comment]
![download (13)](https://user-images.githubusercontent.com/19762119/97101175-275f7a80-16c1-11eb-841e-4e46fe705eb0.png)

**Comment by shekhar10feb** [comment]
![Frame 2](https://user-images.githubusercontent.com/72906055/97101550-84106480-16c4-11eb-81a4-6fbd410ddaa7.png)

**Comment by shekhar10feb** [comment]
![Frame1](https://user-images.githubusercontent.com/72906055/97102816-98595f00-16ce-11eb-8c37-4abf36bcb118.JPG)

**Comment by shekhar10feb** [comment]
![aBanner](https://user-images.githubusercontent.com/72906055/97103494-d8badc00-16d2-11eb-97b9-b64267d048fc.png)

**Comment by shekhar10feb** [comment]
![aBanner](https://user-images.githubusercontent.com/72906055/97103665-e3c23c00-16d3-11eb-963e-b2293256c21d.png)

**Comment by johnjacobkenny** [comment]
@shekhar10feb interesting design :smiley:

**Comment by shekhar10feb** [comment]
> 
> 
> @shekhar10feb interesting design smiley

Thank you :)

**Comment by proful** [comment]
in the future, it can be re-opened.

Now cleaning up issues.
