### ISSUE TITLE
Remove GitHub icon from README.md

### ISSUE THREAD

**Issue by thunder-coding** [twindle-co/twindle#199]
I think it is just a unnecessary icon crowding the README.md file.

If it was some other platform then it was necessary. No need for GitHub icon on GitHub repository :)

**Comment by proful** [comment]
Agree

**Comment by johnjacobkenny** [comment]
Hehe yes agreed

**Comment by thunder-coding** [comment]
I am doing a PR..

**Comment by thunder-coding** [comment]
https://github.com/twindle-co/twindle/pull/200#issue-504683155

Look at this PR and approve the changes

**Comment by tusharkandpal** [comment]
This issue is also done. ready to be closed 👍

**Comment by johnjacobkenny** [comment]
Next time when you create the PR, in the description just add "Closes #abc" with the issue number instead of abc. It will auto close the issue when PR is merged

**Comment by thunder-coding** [comment]
WOW!! Heard of such thing for the first time

**Comment by piratelicorne** [comment]
yes, that was added :)
