### ISSUE TITLE
Video tutorial for second pull request

### ISSUE THREAD

**Issue by naveenkala** [twindle-co/twindle#209]
[![](http://img.youtube.com/vi/cBigFcoAXZg/0.jpg)](http://www.youtube.com/watch?v=cBigFcoAXZg "")
How to do Second PR with git bash

**Comment by johnjacobkenny** [comment]
@naveenkala make sure someone else adds to the resources list, or if nobody is volunteering, you can create a PR today or tomorrow

**Comment by piratelicorne** [comment]
@naveenkala was this added?

**Comment by naveenkala** [comment]
> @naveenkala was this added?

PR #488
