### ISSUE TITLE
videos for 2nd & 3rd PR

### ISSUE THREAD

**Issue by sammjainn** [twindle-co/twindle#211]
Refer these video tutorials:

Second PR from Git Bash : https://www.youtube.com/watch?v=MUGhso65ub8&t=262s&ab_channel=SamriddhiJain

Third PR from VS Code : https://www.youtube.com/watch?v=DGKGgXnP8Po&ab_channel=SamriddhiJain

**Comment by piratelicorne** [comment]
Hi, I referenced the third PR's video from Twindle channel in this #201 (it's in the ONBOARDING.md)

**Comment by piratelicorne** [comment]
Added in the ONBOARDING.md -> #306
