### ISSUE TITLE
Add google meet link in readme

### ISSUE THREAD

**Issue by proful** [twindle-co/twindle#218]
Time 5 PM IST
https://meet.google.com/gna-hvym-tfj

**Comment by RafaelBatman55** [comment]
I will do this task, @proful!

**Comment by UnevenCoder** [comment]
Wanna trim the link to
bit.ly/twindle

**Comment by RafaelBatman55** [comment]
Done! This one is included in this PR: https://github.com/twindle-co/twindle/pull/185

**Comment by UnevenCoder** [comment]
👍

**Comment by tusharkandpal** [comment]
This issue can be closed now. @proful
