### ISSUE TITLE
Creating a branding_design folder

### ISSUE THREAD

**Issue by UnevenCoder** [twindle-co/twindle#219]
Well for all brand designs be it : 
- logo
- thumbnail
- banner
- brand colors
- all the ui design
- illustrations

Benifits :
- easy to access to make any design 
- easy to work on new design (previously made designs can be made use as inspiration)
- professional look to the repo too. 

Looking forward to some feedback on this issue

**Comment by johnjacobkenny** [comment]
I think we can wait till we decide on the final files. Right now we have not taken the vote on which ones we are using, or have we?

**Comment by UnevenCoder** [comment]
True we can still keep the yt banners , thumbnails , twitter-banners etc in one place :)

**Comment by proful** [comment]
@UnevenCoder Raise a PR

**Comment by frankiefab100** [comment]
@UnevenCoder I agree with you. 
I will suggest we discuss this or may be get inspiration from Twitter & Kindle style guide them implement on it.

**Comment by proful** [comment]
assets folder can be used
