### ISSUE TITLE
Tutorial For Third Pull Request

### ISSUE THREAD

**Issue by michaelcosj** [twindle-co/twindle#226]
How I made my Third PR Using Git CLI

Note that I have already forked the twindle project and cloned it to my local machine and I already have git installed, steps on getting all of this set up have already been discussed on other issues.

- Step 1, Navigate to local twindle project folder
![img1](https://user-images.githubusercontent.com/49528393/96284699-da4f1a80-0fd5-11eb-900a-2fcd132dcbe2.png)

- Step 2, Sync fork with the twindle directory
![img2](https://user-images.githubusercontent.com/49528393/96284776-fbb00680-0fd5-11eb-945c-c9610f429e3c.png)
![img3](https://user-images.githubusercontent.com/49528393/96284803-05d20500-0fd6-11eb-8258-9798c6b7b21c.png)
![img5](https://user-images.githubusercontent.com/49528393/96284830-0b2f4f80-0fd6-11eb-82e4-f0df2f129d36.png)

- Step 3, After making desired changes, add it to the staging area so its ready to be commited
![img6](https://user-images.githubusercontent.com/49528393/96284897-226e3d00-0fd6-11eb-82f7-a5ea16c6d67c.png)

- Step 4, Check the status and make sure everything is fine
![img7](https://user-images.githubusercontent.com/49528393/96284906-28fcb480-0fd6-11eb-99a5-febe9c82f77e.png)
![img8](https://user-images.githubusercontent.com/49528393/96284977-40d43880-0fd6-11eb-89c3-9499b1ec9b98.png)

- Step 5, Commit changes
![img9](https://user-images.githubusercontent.com/49528393/96285126-6d885000-0fd6-11eb-9179-436be78f0725.png)

- Step 6, Push changes to github
![img10](https://user-images.githubusercontent.com/49528393/96285154-7842e500-0fd6-11eb-92bc-7f6f4ac6f8b3.png)
![img11](https://user-images.githubusercontent.com/49528393/96285185-84c73d80-0fd6-11eb-84c3-ea3ed80faff6.png)

- Step 7, Go to the Github page of the fork, and click on pull request or compare changes
![Untitled design](https://user-images.githubusercontent.com/49528393/96285733-39f9f580-0fd7-11eb-8385-953d1c65bbca.png)

- Step 8, Click on create pull request
![img12](https://user-images.githubusercontent.com/49528393/96285556-03bc7600-0fd7-11eb-9887-06136893a96f.png)

- Step 9, Add a title and/or comment and create your pull request
![Untitled design (2)](https://user-images.githubusercontent.com/49528393/96285867-6ada2a80-0fd7-11eb-8f3a-63253a7e6ada.png)

# Helpful Resources
- Issues #41  and #156 
- [Git-Guides](https://github.com/git-guides/)
- [Learn Github in 20 minutes by Colt Steele on YouTube](https://www.youtube.com/watch?v=nhNq2kIvi9s)
- [Dzone.com - How to resolve github merge conflicts](https://dzone.com/articles/how-to-resolve-github-merge-conflicts)
- [GitHub docs - Resolving a merge conflict on github](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/resolving-a-merge-conflict-on-github)

I hope this was helpful!

**Comment by nishanknavelkar** [comment]
Screenshots not visible.

**Comment by michaelcosj** [comment]
All of them?
They work when I try

**Comment by nishanknavelkar** [comment]
This is what I see,
![image](https://user-images.githubusercontent.com/48888656/96274439-1d1cec80-0fee-11eb-93d4-209a2a395170.png)

**Comment by michaelcosj** [comment]
Oh!! You have to click on the image links to see it
Because the images are a bit big I didn't want it to take too much space so I hosted them on imgshare.io

**Comment by nishanknavelkar** [comment]
Oh, ok 👍. See if there is a way where you could downsize the images, It would become a much better tutorial.

**Comment by michaelcosj** [comment]
I'll look into it now
Thank you!!

**Comment by michaelcosj** [comment]
I've scaled the images and updated it.
Thanks for the suggestion!

**Comment by nishanknavelkar** [comment]
looks great 👍

**Comment by nishanknavelkar** [comment]
@piratelicorne @johnjacobkenny , how can we add this to FAQ and Documentation?

**Comment by proful** [comment]
Please update your experience with fixing merge conflicts. 

That is the objective of this 3rd pr

**Comment by johnjacobkenny** [comment]
> @piratelicorne @johnjacobkenny , how can we add this to FAQ and Documentation? 

@piratelicorne @Sheetal777 🙂

**Comment by piratelicorne** [comment]
Added in the ONBOARDING.md -> #306
