### ISSUE TITLE
use tips to automatically close an issue

### ISSUE THREAD

**Issue by tusharkandpal** [twindle-co/twindle#229]
Please use `close <issue-no.>` in the description of PR to automatically close an issue related to it otherwise it's just cluttering around.
You can go into details about it in Issue #167

**Comment by johnjacobkenny** [comment]
Is this post for awareness or any action required from someone?

**Comment by tusharkandpal** [comment]
for awareness @johnjacobkenny

**Comment by johnjacobkenny** [comment]
Could you please find the FAQ section and share the info in the twitter group too so others may see
