### ISSUE TITLE
Readme image sizes on GitHub mobile

### ISSUE THREAD

**Issue by johnjacobkenny** [twindle-co/twindle#233]
![Screenshot_20201016-223004.jpg](https://user-images.githubusercontent.com/19240564/96287219-3712fb00-0fff-11eb-8d08-dd57e03f321a.jpg)

Something is wrong here!

**Comment by tolgaerdonmez** [comment]
I'll try to handle it

**Comment by tolgaerdonmez** [comment]
I tried [in my own fork](https://github.com/tolgaerdonmez/twindle/blob/fix/readme-mobile-images/README.md) some adjustments but I couldn't get it to work on GitHub's application :(

```markdown
[<img src='https://www.creativefreedom.co.uk/wp-content/uploads/2017/06/Twitter-featured.png' height='45' width='55' />](https://twitter.com/twindleco)
[<img src ='https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQ342VRbRlgLDPviYYJgxfCVEHKmtuV8LIisA&usqp=CAU'  width='50' height='50' />](https://www.youtube.com/channel/UCKxUmbHq5P5pd5IyUiZ8MHA)
<a target="_blank" href="https://discord.gg/jBj2zMR">
<img src='https://cdn.vox-cdn.com/thumbor/nU3aFhQTGn1z9ImiSHXkF0bnyLk=/0x0:1600x1600/1400x1400/filters:focal(659x770:915x1026):format(jpeg)/cdn.vox-cdn.com/uploads/chorus_image/image/56262027/discord_logo.0.jpg' height='50' width='50' /></a>
```
these just won't work on mobile

**Comment by madhusudanbabar** [comment]
Has somebody fixed it?? 

![Screenshot_20201017-055919416](https://user-images.githubusercontent.com/28552728/96324174-08684500-103e-11eb-9036-e91b0eac138c.jpg)
This is how it looks now.

**Comment by proful** [comment]
Someone fixed it I think.

Looks good. 

@johnjacobkenny can confirm and close it

**Comment by johnjacobkenny** [comment]
This is still open, on GitHub mobile app I'm having this issue.

**Comment by tusharkandpal** [comment]
@tolgaerdonmez are these fixed? Do tell if your need help

**Comment by tolgaerdonmez** [comment]
I couldn't fix, some help will be nice :)

**Comment by tusharkandpal** [comment]
Ok i will look into it.

**Comment by michaelcosj** [comment]
I think I've fixed it at my [fork](https://github.com/michaelcosj/twindle/blob/main/README.md) by replacing the icons with icons from [icons8](https://icons8.com) but attribution is needed for use

**Comment by tusharkandpal** [comment]
What kind of attributes you mean?

**Comment by michaelcosj** [comment]
Oh not attributes, attribution like to link to their site

https://icons8.com/license

**Comment by johnjacobkenny** [comment]
Can't we just resize the images

**Comment by michaelcosj** [comment]
I looked into it and markdown doesn't have a way to resize the images and I think the GitHub app ignores the img height and width attributes.

I think we can just resize the image files and host it somewhere or create a images folder in the projectand put the images there.

**Comment by codeprm** [comment]
How does this one look - [https://github.com/twindle-co/twindle/pull/309](https://github.com/twindle-co/twindle/pull/309) ?

**Comment by thunder-coding** [comment]
This is due to a bug in GitHub Mobile. I am also facing the same issue, not only on Twindle repository but all repositories

**Comment by thunder-coding** [comment]
> This is still open, on GitHub mobile app I'm having this issue.

You are talking about GitHub web on mobile not on GitHub app for mobile

**Comment by thunder-coding** [comment]
> Has somebody fixed it?? 
> 
> ![Screenshot_20201017-055919416](https://user-images.githubusercontent.com/28552728/96324174-08684500-103e-11eb-9036-e91b0eac138c.jpg)
> This is how it looks now. 


You are talking about GitHub website on mobile not GitHub app for Android

**Comment by madhusudanbabar** [comment]
> > Has somebody fixed it??
> > ![Screenshot_20201017-055919416](https://user-images.githubusercontent.com/28552728/96324174-08684500-103e-11eb-9036-e91b0eac138c.jpg)
> > This is how it looks now.
> 
> You are talking about GitHub website on mobile not GitHub app for Android

yes but I believe it's the application issue, anyways resized images will solve this.

**Comment by tolgaerdonmez** [comment]
I believe so, does including the images in the repository a problem. I wanted to avoid that.

**Comment by johnjacobkenny** [comment]
@tolgaerdonmez I don't think it's a problem unless there's any copyright related issue?

**Comment by tolgaerdonmez** [comment]
> @tolgaerdonmez I don't think it's a problem unless there's any copyright related issue?

Yeah probably

**Comment by johnjacobkenny** [comment]
> How does this one look - [https://github.com/twindle-co/twindle/pull/309](https://github.com/twindle-co/twindle/pull/309) ?

Could you let me know more about this?

**Comment by piratelicorne** [comment]
I tried on my phone, now it looks like normal size :)

**Comment by johnjacobkenny** [comment]
@piratelicorne are you using the mobile app or the mobile website? For me this is on the app and I am still having it

**Comment by piratelicorne** [comment]
I tested on the website (twindle.co) but I just checked in the GitHub mobile app ![image](https://user-images.githubusercontent.com/52439373/97004962-63e57780-1503-11eb-9cf9-29e2b5205d6b.png) and looks good, can you check also the icons in the ONBOARDING.md? Maybe we can use those ones, they are smaller sand I used them from "iconfinder"

**Comment by johnjacobkenny** [comment]
Those are slightly larger than the ones we have here, but yeah maybe we could look at something like that, or simply resize the files.

And I think this could be a GitHub android issue since you don't have the issue in iOS

**Comment by piratelicorne** [comment]
What about this?

![image](https://user-images.githubusercontent.com/52439373/97190887-479c4180-1774-11eb-9087-01d530109b7a.png)

**Comment by madhusudanbabar** [comment]
> Those are slightly larger than the ones we have here, but yeah maybe we could look at something like that, or simply resize the files.
> 
> And I think this could be a GitHub android issue since you don't have the issue in iOS

Yeah, it's actually on android app only, i reported this issue [here](https://github.com/github/feedback/discussions/14#discussioncomment-110071), they will work on it in future but till then we can go with resized images.

**Comment by johnjacobkenny** [comment]
> > Those are slightly larger than the ones we have here, but yeah maybe we could look at something like that, or simply resize the files.
> > And I think this could be a GitHub android issue since you don't have the issue in iOS
> 
> Yeah, it's actually on android app only, i reported this issue [here](https://github.com/github/feedback/discussions/14#discussioncomment-110071), they will work on it in future but till then we can go with resized images.

Great! So then I think we can use what @piratelicorne has implemented.

**Comment by proful** [comment]
Closing this. We can reopen in future.
