### ISSUE TITLE
ONBOARDING.md

### ISSUE THREAD

**Issue by proful** [twindle-co/twindle#242]
Create a onboarding docs

What to do next after joining?

Step by step instruction

1. follow twitter
2. sub YT
3. join discord
4. fork github
5. first pr
6. second pr
7. third pr

@piratelicorne

**Comment by piratelicorne** [comment]
I'm on it

**Comment by proful** [comment]
- update in README
- open links in new tab

**Comment by johnjacobkenny** [comment]
Super fast response and awesome docs @piratelicorne 🥳
