### ISSUE TITLE
Discord Usage

### ISSUE THREAD

**Issue by proful** [twindle-co/twindle#243]
## Initial Discord thoughts

[JOIN DISCORD](https://discord.com/invite/jBj2zMR)

During the initial time, we will use the #general channel for all related discussions.

Also, use #general voice channels for all project-related discussions.

Avoid creating small groups for calls. This will reduce visibility for new members who want to participate.

We will slowly optimize the process.

Now knowing each other is important & allows all to join the call. We will monitor & review the process.

**Comment by ad3rinto** [comment]
Thanks @proful , this is a good way to start.
