### ISSUE TITLE
OBS how to add voice of other participants for daily call recording

### ISSUE THREAD

**Issue by proful** [twindle-co/twindle#245]
- need suggestions on how to do it?

**Comment by manohar52** [comment]
![image](https://user-images.githubusercontent.com/46411996/96327179-f3b78d00-0ffc-11eb-8c93-922f23a760aa.png)
I created a new scene called "online meetings"; added audio output, input and display sources. I tested it and it worked. I could hear the other persons voice as well, in the recording.

**Comment by proful** [comment]
Tomorrow ping me when you are free we can have discord call

**Comment by proful** [comment]
No device is appearing.

![image](https://user-images.githubusercontent.com/354596/96364220-6c495580-1185-11eb-8f6d-334a740a00b3.png)

**Comment by manohar52** [comment]
Oh Somehow didnt see these comments.
I will ping you on discord
