### ISSUE TITLE
For impatient George who want to code

### ISSUE THREAD

**Issue by proful** [twindle-co/twindle#246]
https://github.com/twindle-co/twindle/graphs/contributors

- Write Node js program to fetch github contributor infor
github user name & other details

These are help utility. No restriction to use anything

Few ex:-
https://github.com/mgechev/github-contributors-list

This is side track work. Not going to merge into twindle repo now.

**Comment by proful** [comment]
@johnjacobkenny https://github.com/twindle-co/twindle-scripts

already done it!

**Comment by johnjacobkenny** [comment]
Haha 😁

**Comment by thunder-coding** [comment]
I think we should close this issue now :)

**Comment by johnjacobkenny** [comment]
Yes this is available in `twindle-scripts` repo
