### ISSUE TITLE
Fix a stray file called "secondpr"

### ISSUE THREAD

**Issue by johnjacobkenny** [twindle-co/twindle#252]
There is a stray file, can someone make it into correct section.

**Comment by arthurbuhl** [comment]
Added my comments here: https://github.com/twindle-co/twindle/pull/217#discussion_r506852002

**Comment by pranavgoel29** [comment]
Where to move it any suggestion?

**Comment by johnjacobkenny** [comment]
If it needs to go into faq or somewhere else please contact relevant people to ask

**Comment by pranavgoel29** [comment]
I will contact them when I get free time.

**Comment by johnjacobkenny** [comment]
@pranavgoel29 go ahead and raise a pr deleting it?

**Comment by pranavgoel29** [comment]
ok I am doing that
