### ISSUE TITLE
docs/onboarding content may be moved to readme file?

### ISSUE THREAD

**Issue by johnjacobkenny** [twindle-co/twindle#253]
Please comment on your thoughts, right now that is the only "homepage" we have. Beginners who are new to the project should be reading that and deciding to join!

**Comment by tusharkandpal** [comment]
Can it be pinned to the homepage by anyway?

**Comment by pranavgoel29** [comment]
I think that's a good idea to include the content in ONBOARDING.md file to readme file instead, then who is just checking Twindle for the first time or a beginner can get to know how they can start right away.

**Comment by tusharkandpal** [comment]
We can add a link to ONBOARDING.md as mentioned by proful in Issue #244  
This way if they find the project interesting they can jump onto the next steps.

**Comment by johnjacobkenny** [comment]
I strongly feel this should be the first thing anyone sees when they open the repository on github. Same thought process goes for the website content once it is ready

**Comment by proful** [comment]
OK @johnjacobkenny fine with me

**Comment by johnjacobkenny** [comment]
Yeah no problem with duplication

**Comment by piratelicorne** [comment]
I saw it's already moved.

**Comment by johnjacobkenny** [comment]
Great!
