### ISSUE TITLE
Creating a Teams page

### ISSUE THREAD

**Issue by Akshay2996** [twindle-co/twindle#271]
I would like to create a Teams Page for our Twindle Team

**Comment by teckiegeek** [comment]
That will be great. It will help newbies and beginners identify where to pitch their tents and learn by getting their hands dirty.

**Comment by johnjacobkenny** [comment]
Is this for the website

**Comment by Akshay2996** [comment]
Yes @johnjacobkenny I'm thinking of creating a static page of our Twindle Team

**Comment by sarathkumar6** [comment]
@UnevenCoder and @johnjacobkenny worked on fetching the contributors info through Giit API I guess. 
What info are you planning to have on the team's page? @Akshay2996

**Comment by johnjacobkenny** [comment]
Just a heads up, the script I implemented was not specifically for the teams page (but can be repurposed for it).

**Comment by Akshay2996** [comment]
Hi everyone! Sorry I'm a little late. My plan to make a dynamic teams page where the team members update a .js file with their information which I can create & guide them how to edit that file. & then after taking the data another .js file can automatically create a card containing the value of it as shown in the image.

What do you think about this idea @sarathkumar6 @johnjacobkenny @UnevenCoder ?

![image](https://user-images.githubusercontent.com/37118877/97023680-78f9ef00-1573-11eb-9a65-bf4f2ff714bc.png)

**Comment by ni3-kdm** [comment]
@Akshay2996  are you planning to generating dynamic html cards from a JSON file in the current implementation?

**Comment by UnevenCoder** [comment]
I created a simple script to retrieve the pfps and github name s of the
contributors .. will be creating a pr tommorow

Really sorry busy with exam prep , thanks for understanding

**Comment by Akshay2996** [comment]
> @Akshay2996 are you planning to generating dynamic html cards from a JSON file in the current implementation?

I have created a person.js file which will contain all the information of the team in one big object just like JSON. 

My plan so far -:
- Import **person.js** file to **team_details.js** file
- **team_details** will create a card based on the specification of **person.js**
- Our team members will only update **person.js** file which is just an Object file in a variable.

**Comment by Akshay2996** [comment]
> > @Akshay2996 are you planning to generating dynamic html cards from a JSON file in the current implementation?
> 
> I have created a person.js file which will contain all the information of the team in one big object just like JSON.
> 
> My plan so far -:
> 
> * Import **person.js** file to **team_details.js** file
> * **team_details** will create a card based on the specification of **person.js**
> * Our team members will only update **person.js** file which is just an Object file in a variable.

PS: I have the format ready for the **person.js** file

**Comment by proful** [comment]
@Akshay2996 very good. I like the approach you are taking.

**Comment by Akshay2996** [comment]
Till now I have created persons.js file with the specific format. Below is the screenshot with the format that I think will be great for the card.

![image](https://user-images.githubusercontent.com/37118877/97612589-9f210280-1a3d-11eb-955b-7377348a2e3d.png)

Please do tell me if any changes are needed in the format @proful @sarathkumar6 @johnjacobkenny @ni3-kdm @UnevenCoder 

PS: If any of you would like to volunteer in this work please do tell me because nobody responded me in taking the responsibility or working with me on this.

**Comment by ni3-kdm** [comment]
> Till now I have created **persons.js** file with the specific format. Below is the screenshot with the format that I think will be great for the individual card on the teams page.
> 
> ![image](https://user-images.githubusercontent.com/37118877/97613066-3ab27300-1a3e-11eb-8998-3163645c0b64.png)
> 
> **README.md** file created to guide our teammates on how to upload their details.
> 
> ![image](https://user-images.githubusercontent.com/37118877/97617994-78b29580-1a44-11eb-98ee-19e2fd7a0118.png)
> 
> Please do tell me if any changes are needed in the format @proful @sarathkumar6 @johnjacobkenny @ni3-kdm @UnevenCoder
> 
> **PS:** If any of you would like to volunteer in this work please do tell me because nobody responded me in taking the responsibility or working with me on this.

@Akshay2996 ping me on discord for any help.

**Comment by proful** [comment]
looks good @Akshay2996

**Comment by johnjacobkenny** [comment]
Good work @Akshay2996

**Comment by Akshay2996** [comment]
> > Till now I have created **persons.js** file with the specific format. Below is the screenshot with the format that I think will be great for the individual card on the teams page.
> > ![image](https://user-images.githubusercontent.com/37118877/97613066-3ab27300-1a3e-11eb-8998-3163645c0b64.png)
> > **README.md** file created to guide our teammates on how to upload their details.
> > ![image](https://user-images.githubusercontent.com/37118877/97617994-78b29580-1a44-11eb-98ee-19e2fd7a0118.png)
> > Please do tell me if any changes are needed in the format @proful @sarathkumar6 @johnjacobkenny @ni3-kdm @UnevenCoder
> > **PS:** If any of you would like to volunteer in this work please do tell me because nobody responded me in taking the responsibility or working with me on this.
> 
> @Akshay2996 ping me on discord for any help.

Sure @ni3-kdm Will do. Been busy with other work & personal life that is why I couldn't connect with anyone recently. But once I get back will surely do connect with you.

**Comment by proful** [comment]
@Akshay2996 raise a PR and close this issue please

**Comment by Akshay2996** [comment]
I have raised a PR & is going to close this issue now.
