### ISSUE TITLE
Twindleco website playground

### ISSUE THREAD

**Issue by proful** [twindle-co/twindle#272]
Created file naming conventions

https://github.com/twindle-co/twindle/tree/main/playground/twindleco

![image](https://user-images.githubusercontent.com/354596/96356001-6bd49e80-1134-11eb-8a50-f47252074e56.png)

This is a prototype.

Doesn't tell you which color style to use etc.

**Comment by nishanknavelkar** [comment]
Can we create a gh-pages branch and maybe experiment with the website design ?

**Comment by johnjacobkenny** [comment]
I think we can focus on publishing later? Once it comes to a maturity

**Comment by sarathkumar6** [comment]
@nishanknavelkar As posted in the discord, the actual design discussion will happen after the daily meeting tomorrow. Let's keep the playground version and the actual design separate.... To practice, Dribble is a wonderful place to look for some inspiration as @proful  mentioned in the meeting.

**Comment by nishanknavelkar** [comment]
ok 👍

**Comment by proful** [comment]
@Sheetal777 work on testimonials section. come up with ur own design

**Comment by Sheetal777** [comment]
@proful okay I will try to figure that out through resources. 👍

**Comment by frankiefab100** [comment]
Please who is handling the interface design?

**Comment by sarathkumar6** [comment]
@frankiefab100 
Myself and  @tusharkandpal are working on the UI design. We've come up with the basic UI design 
https://tusharkandpal.github.io/twindle-site/ and trying to improve the design. Please feel free to share your feedback with us. You can connect us through discord or twitter

@proful  Do you mind sending @frankiefab100  discord invite? Thanks.

**Comment by sarathkumar6** [comment]
@frankiefab100 Here is the discord server invite
https://discord.gg/Rc2PMN Please feel free to join and ping me to talk about the design. Thanks

**Comment by frankiefab100** [comment]
@sarathkumar6 I'm in the Discord workspace, I will send you a message
