### ISSUE TITLE
Solving merge conflicts

### ISSUE THREAD

**Issue by sammjainn** [twindle-co/twindle#273]
## Merge Conflicts

- Merge conflicts occur when competing changes are made to the same line of a file, or when one person edits a file and another person deletes the same file.
- A merge can enter a conflicted state at two separate points. When starting and during a merge process.

## Solving merge conflicts
- The only correct way to solve conflicts is to pull new changes, create a new commit and push again.
- Multiple ways to do this depending on how you use git: through command line, VS code, some GUI etc.

- **Written step by step**: [click here](https://github.com/twindle-co/twindle/issues/41)
- **Video tutorial for GitHub website**: [click here](https://www.youtube.com/watch?v=bzaBiQQl6fU&t=7s&ab_channel=Twindle)
- **Video tutorial for git command line**: [click here](https://www.youtube.com/watch?v=bPBTumdMhyQ&t=169s&ab_channel=Twindle)
- **Video tutorial for VS Code**: [click here](https://www.youtube.com/watch?v=U2bOwEY-vKo&ab_channel=Twindle)

**Comment by nishanknavelkar** [comment]
Looks Great, you can update the wiki with this information.
https://github.com/twindle-co/twindle/wiki/Resolving-merge-conflicts

**Comment by piratelicorne** [comment]
Hi @sammjainn  I added the info into the wikipage, I didn't include the videos because they don't cover merge conflicts.
