### ISSUE TITLE
Design: header for website

### ISSUE THREAD

**Issue by sammjainn** [twindle-co/twindle#274]
Share your ideas/designs and have discussions here for creating header for website

**Comment by nishanknavelkar** [comment]
Idea 1: 
![image](https://user-images.githubusercontent.com/48888656/96348192-a4d52a80-10c4-11eb-9583-fc2e7be586fd.png)

[https://dribbble.com/shots/14405499-Frubits](url)

**Comment by SwatiRaoDataEnthusiast** [comment]
This design header was suggested by Proful in the call

https://dribbble.com/shots/14403641-Comparrot

**Comment by SwatiRaoDataEnthusiast** [comment]
![image](https://user-images.githubusercontent.com/53012491/96349163-6000c200-10cb-11eb-883c-1d899be3f428.png)

**Comment by proful** [comment]
Can someone implement first design
header1.html
header1.css

Can someone implement the second design
header2.html
header2.css

**Comment by tusharkandpal** [comment]
@proful are you talking about above two images ?

**Comment by proful** [comment]
Yes. pick anyone & proceed.

**Comment by SwatiRaoDataEnthusiast** [comment]
okay I will try @proful the second design

**Comment by proful** [comment]
Go ahead @SwatiRaoDataEnthusiast

**Comment by tusharkandpal** [comment]
@nishanknavelkar please share the first link to me in twitter or discord, if you have. This is not working

**Comment by SwatiRaoDataEnthusiast** [comment]
#317

**Comment by tusharkandpal** [comment]
![header](https://user-images.githubusercontent.com/66052835/96368181-203fe600-1170-11eb-825f-6a8157ef4e31.JPG)

made using flex

**Comment by proful** [comment]
@tusharkandpal Great work 👍

**Comment by tusharkandpal** [comment]
@proful should i name header1 & css1 for mine ?

**Comment by proful** [comment]
Yes

Keep this issue open. Let others commit.

You implement other stuff.

**Comment by tusharkandpal** [comment]
Ok. Fine

**Comment by satyaki07** [comment]
![2020-10-18 (4)](https://user-images.githubusercontent.com/25426670/96371623-263dc300-1180-11eb-922f-5be9198c2b1a.png)

I have used Flexbox for the layout.

**Comment by tusharkandpal** [comment]
Good work @satyaki07 😀👍

**Comment by satyaki07** [comment]
I have submitted a PR for this.

**Comment by therealJimoh** [comment]
I want to implement the second design: header2 html and header2 css, can I?

**Comment by tusharkashyap63** [comment]
Yeah what is the progress with header 2? I would also like to try my hand at it.
