### ISSUE TITLE
Design: footer for website

### ISSUE THREAD

**Issue by sammjainn** [twindle-co/twindle#275]
This space is for discussing designs for website footer

**Comment by proful** [comment]
![image1](https://user-images.githubusercontent.com/354596/96360039-e2899000-1164-11eb-82cc-9bb76361eecd.png)

**Comment by princehaybee** [comment]
I will work on the footer section.

**Comment by sarathkumar6** [comment]
Please ensure to grab the right links of twindle online presence i.e., Twitter handle, Youtube channel, and GitHub repo
@princehaybee

**Comment by princehaybee** [comment]
@sarathkumar6 thanks. I am on the youtube channel now.
