### ISSUE TITLE
Figure out recording of discord calls

### ISSUE THREAD

**Issue by johnjacobkenny** [twindle-co/twindle#281]
@UnevenCoder could you please take this

**Comment by michaelcosj** [comment]
I think there's a discord bot that can help with recording the calls

**Comment by codeprm** [comment]
I don't think discord has a feature to do that. 
https://support.discord.com/hc/en-us/community/posts/360047224131-Record-video-audio-calls

There are some work around ideas like this one - 
https://www.howtogeek.com/677198/how-to-record-discord-audio/

We should take consent/have a notice issued before recording with the bot.

**Comment by UnevenCoder** [comment]
Bot idea is the best or we can use OBS
