### ISSUE TITLE
Apply for Twitter API

### ISSUE THREAD

**Issue by proful** [twindle-co/twindle#287]
Can someone try to apply for Twitter api and document the process of applying.

**Comment by sarathkumar6** [comment]
@proful I'll look into this task.

**Comment by vijaya-bhaskar** [comment]
@sarathkumar6 Please ping me if you need any assistance.

**Comment by UnevenCoder** [comment]
I got rejected 😢

**Comment by piratelicorne** [comment]
is this for twitter developer? I applied last year, but I don't have record of that :/

**Comment by proful** [comment]
Yes can you please explain how you did that. So that other can try?

**Comment by johnjacobkenny** [comment]
I think @piratelicorne meant she has access. I too had applied and got access a few months ago 🙂 But I didn't do documentation of the process

**Comment by proful** [comment]
Can you find json files? And upload it..

so that it can be used for mocking..

**Comment by johnjacobkenny** [comment]
@proful yeah 👍

**Comment by thunder-coding** [comment]
https://developer.twitter.com/en/apply/user.html

We can apply for Twitter API from this website. But the process is very complicated, we need to write them the reason why we are applying for the API. Don't know why @twitter has kept this process so complicated

**Comment by piratelicorne** [comment]
I remember I wrote "its a school project to write tweets from CLI" , they gave me access but took a week, at the end I didn't need it.

**Comment by Pa1sathvik** [comment]
How about http://twitter4j.org/en/ library ?

**Comment by thunder-coding** [comment]
> How about http://twitter4j.org/en/ library ?

This is written in Java we need in JavaScript

**Comment by Pa1sathvik** [comment]
@thunder-coding Why we need in Javascript specifically?

**Comment by UnevenCoder** [comment]
> @thunder-coding Why we need in Javascript specifically? 



We are keeping our stack limited to js so we need api to be fetch able in js or its of no use to us 😅

**Comment by Pa1sathvik** [comment]
@UnevenCoder Why we are limiting our Stack , if we are limiting our  stack then we will be not able to achieve what we planned for . We need language like Java , Scala which gives very good multi threading performance when compared to JS or python.

**Comment by johnjacobkenny** [comment]
@Pa1sathvik you can raise this concern during the meeting today 🙂

**Comment by johnjacobkenny** [comment]
Also just a heads up, the plan is to try and include as many people to contribute and learn. We might need to sacrifice a little initially and stick with a smaller stack, and eventually we might include some other stack as per requirement. @Pa1sathvik

**Comment by ad3rinto** [comment]
I have also applied for the twitter dev account, application is currently under review.
I was hoping it would be immediate.
@piratelicorne how long does it usually take?

**Comment by piratelicorne** [comment]
I remember between 7 and 10 days, but If im not mistaken they can approve within the next 15 days.

**Comment by johnjacobkenny** [comment]
> @UnevenCoder Why  are we limiting our Stack , if we are limiting our  stack then we will be not able to achieve what we planned for . We need language like Java , Scala which gives very good multi threading performance when compared to JS or python.

@proful

**Comment by vijaya-bhaskar** [comment]
@Pa1sathvik 
In my opinion, as Proful mentioned previously too in meetings, the intention to include more people to learn and introduce to open-source community is equally as important as the project objective is.
We can use the tools/languages you mentioned and complete this project in a day or two but that's not the whole aim here.
By having the stack minimum we are keeping the objective open to anyone to learn and code easily.
I am happy to say that many including me have done first pull-request because of Twindle.

**Comment by Sheetal777** [comment]
Hey, quick question, does every member need to apply for the Twitter API access?

**Comment by johnjacobkenny** [comment]
Nope, you can skip if you're not interested

**Comment by ad3rinto** [comment]
I have now received approval from twitter.

**Comment by proful** [comment]
That's great @ad3rinto Update document your observations.

**Comment by proful** [comment]
Refer wiki
