### ISSUE TITLE
Twindle CLI

### ISSUE THREAD

**Issue by proful** [twindle-co/twindle#288]
This is a very simple start

```
node twindle thread-id -o pdf
```

What are options we have?

node twindle thread-id -o pdf

Other options
epub
mobi

Can someone start writing one program to accept parameters and display some messages into console?

**DON'T WORRY ABOUT PDF, TWITTER etc**

https://github.com/twindle-co/twindle/tree/main/playground/cli

**Comment by UnevenCoder** [comment]
how do you want pdf to be made ?

**Comment by proful** [comment]
That is another task.

This is to create program to parse options and show help information.

**Comment by thisisarsa** [comment]
Can this be assigned to me?

**Comment by niveth09** [comment]
@proful I want to contribute 🙋

**Comment by proful** [comment]
go ahead @niveth09 u also work on it
