### ISSUE TITLE
Resolve merging conflict from your terminal

### ISSUE THREAD

**Issue by Akshay2996** [twindle-co/twindle#296]
To sync the Main repo and your Own repo, Follow the steps below:

1. Pointing to the main repo and pull from it. Create a new remote in local for pointing the main repo.
`git remote add upstream https://github.com/twindle-co/twindle.git`

2. To download all the changes and commits from main Repo.
`git fetch upstream`

3. The current branch will be updated to reflect the merge.
`git merge upstream/main`

4. Push the changes to own repository.
`git push origin main`

**Comment by Akshay2996** [comment]
We can also merge **Step 2 & Step 3** by writing:
`git pull upstream main`

**Comment by Akshay2996** [comment]
Hi @proful @sarathkumar6 & @johnjacobkenny Please some post this issue in the Resolving merge conflict wiki page so that it is easier for people having trouble with the merge conflict

**Comment by proful** [comment]
@Akshay2996 go ahead and edit wiki page and share the link with others

**Comment by Akshay2996** [comment]
I have updated the wiki page & I am closing this issue.
