### ISSUE TITLE
Hello World pdf 

### ISSUE THREAD

**Issue by proful** [twindle-co/twindle#301]
Write a program that generates hello world message in pdf.

Use any approach you like.

**Comment by michaelcosj** [comment]
This is probably not what you meant but I wanted to challenge myself so I spent all night writing this [node js application](https://github.com/michaelcosj/text2pdf) that generates a pdf document from given text.

I used a couple of npm packages though to make it.

**Comment by johnjacobkenny** [comment]
This is interesting @michaelcosj! @proful could you take a look at the approach if it's how you meant

**Comment by thunder-coding** [comment]
The code is bit complicated, we should try to make it as simple to understand as we can

**Comment by satyaki07** [comment]
A bit unclear on the 3rd line.

**Comment by proful** [comment]
@satyaki07 can u explain?

**Comment by michaelcosj** [comment]
Oh, I'm sorry about that
I've added comments to better explain the code.

**Comment by proful** [comment]
@michaelcosj howz your progress on pdf?

I want to see first pdf soon😊

**Comment by michaelcosj** [comment]
Its going fine. I already made a cli application that creates a pdf from given text and hosted it [in my own repo](https://github.com/michaelcosj/text2pdf/) because I wasn't sure it was what you wanted. I'm currently trying out different solutions like was suggested in the meeting, before I send a PR.

**Comment by proful** [comment]
What ever you have raise a PR

Create a Folder inside cli

It should be simple

**Comment by michaelcosj** [comment]
I just sent in a PR #336 
Thank you!

**Comment by sammjainn** [comment]
Please check PR #340

**Comment by proful** [comment]
We did good progress here and closing this issue.
