### ISSUE TITLE
Hello world message for mobi

### ISSUE THREAD

**Issue by proful** [twindle-co/twindle#303]
Write a program that generates hello world message in mobi.

Use any approach you like.

**Comment by billgufran** [comment]
It is okay to use library right? I'd like to work on this one

**Comment by UnevenCoder** [comment]
Any thing will work @billgufran

**Comment by billgufran** [comment]
I haven't found a way to generate mobi file without having to generate epub first. So I guess I will work on #302 first.

**Comment by johnjacobkenny** [comment]
@billgufran please comment there too

**Comment by billgufran** [comment]
Sure @johnjacobkenny 👍

**Comment by proful** [comment]
in the future, it can be re-opened.

Now cleaning up issues.
