### ISSUE TITLE
Write a program to READ from json file

### ISSUE THREAD

**Issue by proful** [twindle-co/twindle#308]
Once file created by the below issue
https://github.com/twindle-co/twindle/issues/299

- Write a node js program
- Read from the above json file
- Print the output in the console

**Comment by praveen2896** [comment]
I am going to try @proful

**Comment by tr0mbl3y** [comment]
i have also written a code for it is it still open?

**Comment by tr0mbl3y** [comment]
anyways just linking https://github.com/tr0mbl3y/reading_JSON_file_using_node

**Comment by UnevenCoder** [comment]
You can raise a pr .. we will see to it also to help and not ruin someone else's work please use the js to pdf scripts that have already been merged , we don't want someone to loose their work and even we don't want you to start coding it from ground up 😅

Just make it that it fetches data and converts the data into pdf 😃

**Comment by proful** [comment]
Use different file names.
