### ISSUE TITLE
Create folder for resources

### ISSUE THREAD

**Issue by madhusudanbabar** [twindle-co/twindle#328]
**Create a folder for resources**
it'll be easier to work on the UI part of the site if we have resources like logo images and banner for the background

**Comment by madhusudanbabar** [comment]
yes, I agree that we have not finalized the logo yet but temporary resources will also work

**Comment by proful** [comment]
Agree

Raise a PR

**Comment by ad3rinto** [comment]
And I can create an "src" folder for all resources once the PR is created. Is that okay @proful ?

**Comment by proful** [comment]
Feel free to create whatever you want. I will organize later.
