### ISSUE TITLE
NAMING-CONVENTIONS.md

### ISSUE THREAD

**Issue by proful** [twindle-co/twindle#330]
Need more work.

Lots of files we are currently creating and we need some guidance. 

@arthurbuhl

**Comment by arthurbuhl** [comment]
We can look into 

- [Git Naming Convention](https://github.com/naming-convention/naming-convention-guides/tree/master/git)
- [JavaScript Name and Coding Conventions](https://github.com/ktaranov/naming-convention/blob/master/JavaScript%20Name%20and%20Coding%20Conventions.md)
- [Coding Style Guide for node.js apps](https://stackoverflow.com/questions/5495984/coding-style-guide-for-node-js-apps)
- [Airbnb JavaScript Style Guide](https://github.com/airbnb/javascript)

**Comment by proful** [comment]
Summarize in this document.

Only put what is relevant.

Less is more.

**Comment by satyaki07** [comment]
https://github.com/twindle-co/twindle/pull/335#issue-505486561

check this and review.
