### ISSUE TITLE
[Documentation] GitHub keyboard shortcuts

### ISSUE THREAD

**Issue by arthurbuhl** [twindle-co/twindle#338]
If you have started using GitHub a lot more these days, then here are some keyboard shortcuts to perform actions faster. Nearly every page on GitHub has a keyboard shortcut.

Here are the [Keyboard shortcuts](https://docs.github.com/en/free-pro-team@latest/github/getting-started-with-github/keyboard-shortcuts).

**Comment by proful** [comment]
Can be moved to resources/docs
