### ISSUE TITLE
Task Allocation Guidance

### ISSUE THREAD

**Issue by proful** [twindle-co/twindle#343]
# Youtube Videos by me @proful 

- [Twindle Co Website](https://www.youtube.com/watch?v=7cJIYNB2pNo)
- [Run other developer code](https://youtu.be/BStPJrqOaEk)
- [Discussion with Praveen](https://www.youtube.com/watch?v=vVjZLkUgAGQ)
> Praveen started working on json 2 pdf. Join hand with him.

**Comment by UnevenCoder** [comment]
I didn't get the idea of this issue , car to explain ?

**Comment by johnjacobkenny** [comment]
@madhusudanbabar excellent work! :clap:
