### ISSUE TITLE
Creating PDF's from html using Puppeteer

### ISSUE THREAD

**Issue by tolgaerdonmez** [twindle-co/twindle#351]
We can use puppeteer to render pdf from html, should I create an example ?

**Comment by tolgaerdonmez** [comment]
Also It would be easy to create a design, using html & css for pdfs.

**Comment by PrasoonPratham** [comment]
I like this idea.

**Comment by proful** [comment]
i like puppeteer. go ahead @tolgaerdonmez

**Comment by tolgaerdonmez** [comment]
All right, lets give it a try :)

**Comment by johnjacobkenny** [comment]
Sounds good :smiley: 

Just to add my 2 cents, in the past I have used https://www.npmjs.com/package/html5-to-pdf along with mustache template library to generate pdf reports.

**Comment by tolgaerdonmez** [comment]
That's also good, we can start with bare puppeteer than switch to that if we're going to use this approach.
I've also used handlebars to setup a main template for the pdf.

**Comment by johnjacobkenny** [comment]
We will need handlebars or something, but if you can just keep a static html version of the same template so that we can show others what is happening and what handebars is doing.

**Comment by tolgaerdonmez** [comment]
That's a good idea, I'll do that, thanks.

**Comment by tolgaerdonmez** [comment]
I created the pull request, could you review it [pull request](https://github.com/twindle-co/twindle/pull/359)

**Comment by tolgaerdonmez** [comment]
Should we close this now ?

**Comment by tolgaerdonmez** [comment]
I explained the code [here](https://youtu.be/llkkwRABN-s)

**Comment by johnjacobkenny** [comment]
Awesome 🔥
