### ISSUE TITLE
Using ES6+ for nodejs

### ISSUE THREAD

**Issue by tolgaerdonmez** [twindle-co/twindle#352]
I think we could use es6 syntax, by adding babel.
I know that it is complicated for beginners but the ones who are experienced with it could set it up for general use.
The es6 syntax is more readable I believe.
I have myself created a cli for these kind of things it could be used to initialize es6 projects :)
my cli -> [link](https://www.npmjs.com/package/project-chef)
I'm not trying to promote anything, just to be helpful for beginners 🙂

**Comment by vasudeveloper001** [comment]
Why can't we simply write in ES6 format without the need for Babel? We should target new browsers [most now support ES6 - ECMA 2015 nowadays anyways].

I don't see the need for Babel here. Care to explain?

**Comment by proful** [comment]
@tolgaerdonmez this is very helpful

**Comment by tolgaerdonmez** [comment]
> Why can't we simply write in ES6 format without the need for Babel? We should target new browsers [most now support ES6 - ECMA 2015 nowadays anyways].
> 
> I don't see the need for Babel here. Care to explain?

As far as I know, nodejs doesnt support es6 format itself.

**Comment by tolgaerdonmez** [comment]
> @tolgaerdonmez this is very helpful 

thanks

**Comment by vasudeveloper001** [comment]
@tolgaerdonmez Ah right! I totally forgot. My bad!

**Comment by PuruVJ** [comment]
> > Why can't we simply write in ES6 format without the need for Babel? We should target new browsers [most now support ES6 - ECMA 2015 nowadays anyways].
> > 
> > I don't see the need for Babel here. Care to explain?
> 
> As far as I know, nodejs doesnt support es6 format itself. 

Or supports as far as es8 minus the imports. Wet don't transpiler for node

**Comment by aravindsivasailam** [comment]
In order to write es6 syntax such as `import from ` etc, we can either opt for installing a npm package like `esm`. This takes care of converting from es6 to regular to run the scripts. 

https://www.npmjs.com/package/esm. 

Once it is installed and part of package.json, we can then use it as a script in package.json as:
`"start": "node -r esm <file>.js"`

**Comment by proful** [comment]
@aravindsivasailam create a PR with a example and read me file.

Create a folder inside playground/cli
