### ISSUE TITLE
Separation of concern and splitting into multiple repos

### ISSUE THREAD

**Issue by johnjacobkenny** [twindle-co/twindle#362]
_Originally posted by @arthurbuhl in https://github.com/twindle-co/twindle/pull/336#issuecomment-711247789_

I think we should have separation of concern and keep things simple. So, basically we should have like:

- `twindle-co/twindle` repo as our core app. 
	- _Already implemented_ :heavy_check_mark: 
- `twindle-co/twindle-cli` repo as our CLI app
	- The CLI app done in this PR :heavy_check_mark: 
- `twindle-co/twindle-web` repo as our core website.
	- header.html, header.css
	- home_banner.html, home_banner.css
	- footer.html, footer.css
	- team_details.html, team_details.css
	- All our html files and assets should be here.

Just wanted to share my opinion. I will leave this up for other contributors for discussion.

**Comment by EYRAM565** [comment]
I feel we should maintain the process we are used to until we are all (beginners) conversant with the process before any other change.

**Comment by tolgaerdonmez** [comment]
@johnjacobkenny I totaly agree. I think it would be an ease to everyone if we split it.

**Comment by johnjacobkenny** [comment]
This will be picked up in some time, may not be done immediately though

**Comment by vasudeveloper001** [comment]
I think this should be done by this week's end. So that beginners can continue to work here, but those who simply want to go ahead with development can work on other repos directly without much baggage. This will help track the issues and pull requests in a better manner.

**Comment by proful** [comment]
Agree @vasudeveloper001
