### ISSUE TITLE
Table is broken in TEAM.md file.

### ISSUE THREAD

**Issue by pranavgoel29** [twindle-co/twindle#365]
## Please check the TEAM.md file  and solve the table issue 

Also there are some dublicate lines in the beginner section in TEAM.md file.
Remove them too.

To close this issue automatically when your PR get merged you can write, `closes #365` in comment of your pull request.

I have attached a screenshot of current TEAM.md file.

![image](https://user-images.githubusercontent.com/48860494/96463206-15ef1c00-1244-11eb-93b9-1357f1edde66.png)

**Comment by Harsha-Ambati** [comment]
I have made changes!!
