### ISSUE TITLE
Sending mail using AWS SES

### ISSUE THREAD

**Issue by proful** [twindle-co/twindle#390]
Prerequisites:

- JavaScript (intermediate)

AWS - not needed. I will guide

Let me know who wants to take this task?

interested to send email to list of ppl

Request:-
```
{
  "to": ["abc@aa.com", "xyz@aa.com"],
  "from": "tw@aa.dd",
  "subject": "hi",
  "body": "xyz"
}
```

REST Endpoint => Lambda => SES

**Comment by vasudeveloper001** [comment]
I want to know about it. Intermediate JavaScript means what level exactly because I am interested in AWS?

**Comment by tolgaerdonmez** [comment]
I've used AWS nodejs sdk before, what are you willing to do ?

**Comment by proful** [comment]
interested to send email to list of ppl

**Comment by tolgaerdonmez** [comment]
Are we going to create a lambda function or is there an existing service for it

**Comment by tolgaerdonmez** [comment]
I believe this could solve the problem [source](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/ses-examples-sending-email.html)

```javascript
// Load the AWS SDK for Node.js
var AWS = require('aws-sdk');
// Set the region 
AWS.config.update({region: 'REGION'});

// Create sendEmail params 
var params = {
  Destination: { /* required */
    CcAddresses: [
      'EMAIL_ADDRESS',
      /* more items */
    ],
    ToAddresses: [
      'EMAIL_ADDRESS',
      /* more items */
    ]
  },
  Message: { /* required */
    Body: { /* required */
      Html: {
       Charset: "UTF-8",
       Data: "HTML_FORMAT_BODY"
      },
      Text: {
       Charset: "UTF-8",
       Data: "TEXT_FORMAT_BODY"
      }
     },
     Subject: {
      Charset: 'UTF-8',
      Data: 'Test email'
     }
    },
  Source: 'SENDER_EMAIL_ADDRESS', /* required */
  ReplyToAddresses: [
     'EMAIL_ADDRESS',
    /* more items */
  ],
};

// Create the promise and SES service object
var sendPromise = new AWS.SES({apiVersion: '2010-12-01'}).sendEmail(params).promise();

// Handle promise's fulfilled/rejected states
sendPromise.then(
  function(data) {
    console.log(data.MessageId);
  }).catch(
    function(err) {
    console.error(err, err.stack);
  });


```

**Comment by proful** [comment]
Raise a PR https://github.com/twindle-co/twindle-scripts

Clean it up a bit. 

I have lots of features surrounding this SES. This is extremely important. 

If you are interested I can give some guidance on AWS if you haven't used it.

**Comment by praveen2896** [comment]
Hi @proful i am also interested in this task

**Comment by tr0mbl3y** [comment]
i too would like to learn AWS

**Comment by tolgaerdonmez** [comment]
> Raise a PR https://github.com/twindle-co/twindle-scripts
> 
> Clean it up a bit.
> 
> I have lots of features surrounding this SES. This is extremely important.
> 
> If you are interested I can give some guidance on AWS if you haven't used it.
@proful 
Yeah, it would be good. I've just used a minor part of the AWS. I'm still a stranger to it. Guidance would be helpful.
I could send a PR but can you then test the code, whether it sends the emails or not.

**Comment by tolgaerdonmez** [comment]
@proful I sent a PR to twindle-scripts

**Comment by proful** [comment]
If you can try using your account it would be great.

**Comment by tolgaerdonmez** [comment]
> If you can try using your account it would be great. Let me know if you need any help. We can talk about it.
> 
> I too happy to test it out.

I try if possible :)

**Comment by proful** [comment]
in the future, it can be re-opened.

Now cleaning up issues.
