### ISSUE TITLE
We need a logo!

### ISSUE THREAD

**Issue by johnjacobkenny** [twindle-co/twindle#4]
People! We need a logo 😃

Let out your artistic side and create away! Send your suggestions here!!! 🥳

**Comment by johnjacobkenny** [comment]
e.g. add your suggestions  like this
![image](https://user-images.githubusercontent.com/19240564/95939297-5dffe000-0df9-11eb-80c6-93a78514e853.png)

And we can show whether we like it by using emojis. No need to comment that I like this or that, it will add clutter.

![image](https://user-images.githubusercontent.com/19240564/95939340-796aeb00-0df9-11eb-9156-8b9a2e0d8a25.png)

**Comment by MrVoicer** [comment]
![twindle logo](https://user-images.githubusercontent.com/28817838/95946003-4a5c7580-0e09-11eb-9398-4514a1f4fbf4.png)

**Comment by toocoolsachin** [comment]
Hi, I have an idea, maybe we can do is twitter bird taking a thread in her beak or something like that. I am not good at logo designing, maybe anyone here, if like this idea, can design it.

**Comment by MrVoicer** [comment]
![twindle logo2](https://user-images.githubusercontent.com/28817838/95950358-01f58580-0e12-11eb-8144-33e543188403.png)

**Comment by cankocman** [comment]
![twindle](https://user-images.githubusercontent.com/49498453/95952158-45df8f00-0e00-11eb-8827-5d8f3809f7e4.png)

**Comment by cankocman** [comment]
![twindle2](https://user-images.githubusercontent.com/49498453/95952720-4b89a480-0e01-11eb-8678-a16c2c25defa.png)

**Comment by cankocman** [comment]
![twindle3](https://user-images.githubusercontent.com/49498453/95954068-6d842680-0e03-11eb-9b27-131453b86e41.png)
Minor changes. Arrow is a bit lower than before.

**Comment by kambleaa007** [comment]
![02c853be-384e-4b9f-9b2b-640561bf5921_200x200](https://user-images.githubusercontent.com/19818679/95957823-d8425b80-0e1d-11eb-88fa-c4a2f78f329f.png)

Twindle is Here

**Comment by QuiiBz** [comment]
Still WIP
![image](https://user-images.githubusercontent.com/43268759/95960481-13d02c00-0e04-11eb-8d5c-ca3954b8cea2.png)

**Comment by pranavgoel29** [comment]
![Logo mockup](https://user-images.githubusercontent.com/48860494/95960968-117cca80-0e22-11eb-808c-dee33ee5f8d4.png)

**Comment by niveth09** [comment]
### 
![Logo-Twindle (1)](https://user-images.githubusercontent.com/19762119/95970805-0039bb00-0e2e-11eb-823f-6b16eacbf5be.png)

**Comment by MumbiGachomba04** [comment]
![20201014_120422_0000](https://user-images.githubusercontent.com/45368931/95975748-39b6fa00-0e1f-11eb-84b8-92c8f2216032.jpg)

**Comment by kambleaa007** [comment]
> ![image](https://user-images.githubusercontent.com/43268759/95960481-13d02c00-0e04-11eb-8d5c-ca3954b8cea2.png)
> Still WIP

can you put that bird, as dot of i

**Comment by tusharkashyap63** [comment]
![Twindle (2)](https://user-images.githubusercontent.com/65089058/95988591-bd381180-0e46-11eb-9450-e50b422fb8a6.png)

This logo is for dark backgrounds.

**Comment by sammjainn** [comment]
![3](https://user-images.githubusercontent.com/46999417/95990157-c924d300-0e48-11eb-9ee4-9ae094758442.png)
![2](https://user-images.githubusercontent.com/46999417/95990237-e22d8400-0e48-11eb-8e14-bbf22321da4c.png)
![1](https://user-images.githubusercontent.com/46999417/95990209-d80b8580-0e48-11eb-8f64-486d8645ed5c.png)

**Comment by sammjainn** [comment]
![3](https://user-images.githubusercontent.com/46999417/95990381-10ab5f00-0e49-11eb-84e3-3342948ead2b.png)

**Comment by sammjainn** [comment]
![2](https://user-images.githubusercontent.com/46999417/95990411-199c3080-0e49-11eb-991c-0f54ff76eafb.png)

**Comment by sammjainn** [comment]
![1](https://user-images.githubusercontent.com/46999417/95990426-202aa800-0e49-11eb-9c31-1724d38276a1.png)

**Comment by aesthytik** [comment]
![twindle-logo](https://user-images.githubusercontent.com/26917061/96067207-dd071e00-0eb6-11eb-94fe-88ab68b51046.png)

(For lighter backgrounds)

We can have twindle text beneath with some brandguidelines if provided.
I have used #14AFBC as primary color

**Comment by RafaelBatman55** [comment]
> ![twindle-logo](https://user-images.githubusercontent.com/26917061/96067207-dd071e00-0eb6-11eb-94fe-88ab68b51046.png)
> 
> (For lighter backgrounds)
> 
> We can have twindle text beneath with some brandguidelines if provided.
> I have used #14AFBC as primary color

Good one! But maybe will be better if you remove the first line. Can you try?

**Comment by aesthytik** [comment]
> > ![twindle-logo](https://user-images.githubusercontent.com/26917061/96067207-dd071e00-0eb6-11eb-94fe-88ab68b51046.png)
> > (For lighter backgrounds)
> > We can have twindle text beneath with some brandguidelines if provided.
> > I have used #14AFBC as primary color
> 
> Good one! But maybe will be better if you remove the first line. Can you try?

Sure !!! will send an updated version with first line removed in some time:)

**Comment by aesthytik** [comment]
@RafaelBatman55 updated 😄. Looks better now though

![twindle](https://user-images.githubusercontent.com/26917061/96137344-2c326a80-0f1a-11eb-946c-0cc511e5338e.png)

**Comment by niveth09** [comment]
![image (11)](https://user-images.githubusercontent.com/19762119/96220305-1e2a2b80-0fa6-11eb-84c2-06445c6a0ac3.png)

**Comment by sammjainn** [comment]
![image](https://user-images.githubusercontent.com/46999417/96263533-bcd37e00-0fe0-11eb-97f7-107e57b37367.png)
changed bird to ball of yarn. any other thing can be placed in the centre as well (like book)

**Comment by EYRAM565** [comment]
![Twindle-logo](https://user-images.githubusercontent.com/68958520/96339377-42603800-108c-11eb-9456-01b29a1f65c5.jpg)

**Comment by PuruVJ** [comment]
Is the logo finalized? Is there chance for change?

**Comment by UnevenCoder** [comment]
no not yet

**Comment by PuruVJ** [comment]
Here's one from me. Inspired from Microsoft's FLuent Design(a bit)

![twindle logo from Puru Vijay](https://i.imgur.com/iPgIzEq.png)

**Comment by shekhar10feb** [comment]
> 
> 
> Here's one from me
> ![twindle logo from Puru Vijay](https://camo.githubusercontent.com/6f120adc13f3f071fb26e97ba8ba8e1d9f61cb5a/68747470733a2f2f692e696d6775722e636f6d2f695067497a45712e706e67)

Good work

**Comment by proful** [comment]
@PuruVJ good work. Your logo working great

**Comment by pranavgoel29** [comment]
> ![Twindle (2)](https://user-images.githubusercontent.com/65089058/95988591-bd381180-0e46-11eb-9450-e50b422fb8a6.png)
> 
> This logo is for dark backgrounds.

@tusharkashyap63 Please add your twitter handle

**Comment by tusharkashyap63** [comment]
> > ![Twindle (2)](https://user-images.githubusercontent.com/65089058/95988591-bd381180-0e46-11eb-9450-e50b422fb8a6.png)
> > 
> > This logo is for dark backgrounds.
> 
> @tusharkashyap63 Please add your twitter handle
> 

https://twitter.com/tusharkashyap63?s=09

**Comment by pranavgoel29** [comment]
@PuruVJ @EYRAM565 @sammjainn @niveth09 @aesthytik @kambleaa007 @MumbiGachomba04 @QuiiBz @cankocman @MrVoicer 

Everyone please add your twitter handle below your logo.

**Comment by niveth09** [comment]
![New Project (6)](https://user-images.githubusercontent.com/19762119/96409363-c805f400-1202-11eb-989b-e5501051b08c.png)
![Untitled design (9)](https://user-images.githubusercontent.com/19762119/96442725-352c8000-1229-11eb-90b9-fc98b4bb6940.png)

@Nivetharathnav2

**Comment by aesthytik** [comment]
> Nivetharathnav2

add it as a link pls

**Comment by JoelVinayKumar** [comment]
![twindle_logo](https://user-images.githubusercontent.com/16177724/96561132-cad51780-12dc-11eb-9ef8-75653e60f358.png)

The idea is that tweet bird delivered file through cloud. The logo is just different shapes together. Can suffice plenty of color combinations and as it is small, can be accommodated in any area on a web page, printed document.

https://twitter.com/JoelVinayKumar

**Comment by pranavgoel29** [comment]
## Logo with different type style

![image](https://user-images.githubusercontent.com/48860494/96573613-0d522080-12ec-11eb-9ad3-66237fc05ae2.png)

https://twitter.com/Pranavgoel_29

**Comment by tr0mbl3y** [comment]
![twindlelogo](https://user-images.githubusercontent.com/72851843/96578402-c287d700-12f2-11eb-922b-e835c13aa3ad.png)
by:@tr0mbley_

**Comment by teckiegeek** [comment]
Have a look at my design.
![twindle (1)](https://user-images.githubusercontent.com/36566559/96584453-2354e680-12d6-11eb-9cf1-b37773bd3c28.png)

**Comment by teckiegeek** [comment]
Have a look at my design.
![twindlelogo](https://user-images.githubusercontent.com/36566559/96584759-965e5d00-12d6-11eb-96be-195f3ab237aa.png)

**Comment by piratelicorne** [comment]
well.. this will be mine :) ![twindle](https://user-images.githubusercontent.com/52439373/96584997-9ba2b400-12a4-11eb-971a-a8a4ace73f16.png)

**Comment by cankocman** [comment]
> ![twindle2](https://user-images.githubusercontent.com/49498453/95952720-4b89a480-0e01-11eb-8678-a16c2c25defa.png)
>

@proful my twitter is @TheRam05

**Comment by PuruVJ** [comment]
I'm probably spamming with so many logos, but here's another iteration 😁
![](https://i.imgur.com/6EgaovP.png)

**Comment by teckiegeek** [comment]
Another one from me @iamtolopade


![twindle-logo](https://user-images.githubusercontent.com/36566559/96624723-084d9b00-1305-11eb-9104-453d8b8dab75.png)

**Comment by teckiegeek** [comment]
Another one from me @iamtolopade

![twin-dle](https://user-images.githubusercontent.com/36566559/96624778-21564c00-1305-11eb-944b-351edceb6330.png)

**Comment by teckiegeek** [comment]
A warmer logo from me @iamtolopade
![twindle-logo](https://user-images.githubusercontent.com/36566559/96641678-faa40f80-131c-11eb-97d5-4ac7405486f1.png)

**Comment by Harsha-Ambati** [comment]
![circle-cropped (1)](https://user-images.githubusercontent.com/47480010/96688881-4c8d7980-139f-11eb-8d72-805bf20aeadd.png)

**Comment by shekhar10feb** [comment]
![Logo](https://user-images.githubusercontent.com/72906055/96716343-89b73300-13c2-11eb-99cf-a842b695cb61.png)
A logo from me @MontygSharma

**Comment by johnjacobkenny** [comment]
Logo from me https://twitter.com/johnjacobkenny @johnjacobkenny
Lol not so much a logo. Probably an illustration for the website
![twindle](https://user-images.githubusercontent.com/19240564/96721277-82475800-13c9-11eb-80c4-ce1dda6448ea.png)

**Comment by Sheetal777** [comment]
![twi(2)](https://user-images.githubusercontent.com/52107802/96866928-a8343180-1489-11eb-8b93-e1322f511c0d.png)
A logo from me! @Sheetal777

**Comment by Sheetal777** [comment]
![twi(4)](https://user-images.githubusercontent.com/52107802/96869307-ebdc6a80-148c-11eb-8eb8-14f4a1dec10d.png)
A logo from me! @Sheetal777 
https://twitter.com/_sheetal_p

**Comment by Sheetal777** [comment]
![twi(5)](https://user-images.githubusercontent.com/52107802/96870089-0105c900-148e-11eb-89b1-8e1383cca849.png)
Logo #2 from @Sheetal777 
https://twitter.com/_sheetal_p

**Comment by frankiefab100** [comment]
TWINDLE logo. My entry

![Twindle](https://user-images.githubusercontent.com/46662771/96946006-16531580-14d7-11eb-98ef-2821215af0e7.png)

**Comment by niveth09** [comment]
![download (11)](https://user-images.githubusercontent.com/19762119/97098909-56b5bd80-16a8-11eb-8e78-698d5cf2363a.png)

**Comment by aesthytik** [comment]
> ![download (11)](https://user-images.githubusercontent.com/19762119/97098909-56b5bd80-16a8-11eb-8e78-698d5cf2363a.png)
> https://twitter.com/Nivetharathnav2

good one nivetha. unique and creative 👌🏻

**Comment by niveth09** [comment]
> > ![download (11)](https://user-images.githubusercontent.com/19762119/97098909-56b5bd80-16a8-11eb-8e78-698d5cf2363a.png)
> > https://twitter.com/Nivetharathnav2
> 
> good one nivetha. unique and creative 👌🏻

Thanks a lot @aesthytik 😄

**Comment by JoelVinayKumar** [comment]
Thus can't be any better 😍

**Comment by niveth09** [comment]
> Thus can't be any better 😍

Thanks @JoelVinayKumar

**Comment by proful** [comment]
Any logo with out bird symbol.

No need to inspire by Twitter. 

I want the logo to based on beginner, team, collaboration, learning theme.

No text. Minimal shapes.

**Comment by Sheetal777** [comment]
Find me [Sheetal](https://twitter.com/_sheetal_p)
![twi(7)](https://user-images.githubusercontent.com/52107802/97186071-d9cd3580-17c6-11eb-9290-4ad46991f1eb.png)

**Comment by Sheetal777** [comment]
Logo #4 by [Sheetal](https://twitter.com/_sheetal_p)
![twi(8)](https://user-images.githubusercontent.com/52107802/97188022-10a44b00-17c9-11eb-9c1d-93a983ae0c27.png)

**Comment by Sheetal777** [comment]
Logo #4 by [Sheetal](https://twitter.com/_sheetal_p)
![twi(8)](https://user-images.githubusercontent.com/52107802/97188207-477a6100-17c9-11eb-9945-bde6f78a8966.png)

**Comment by Sheetal777** [comment]
Logo #4 by [Sheetal](https://twitter.com/_sheetal_p)
![twi new](https://user-images.githubusercontent.com/52107802/97188648-c1124f00-17c9-11eb-8b02-00eb6cf9d598.png)

**Comment by niveth09** [comment]
![Background](https://user-images.githubusercontent.com/19762119/97270944-f19fca80-1855-11eb-9858-7f030de23aba.png)

**Comment by teckiegeek** [comment]
Hello team, so did we finally select a logo for twindle out of these samples?

**Comment by johnjacobkenny** [comment]
Not yet

**Comment by PuruVJ** [comment]
This hasn't had any activity since a month and half. Closing it now.

If anybody wants to submit new logo, we can always reopen this issue.
