### ISSUE TITLE
FAQ

### ISSUE THREAD

**Issue by piratelicorne** [twindle-co/twindle#40]
Let's update the FAQ page. @Sheetal777

**Comment by proful** [comment]
FAQ is very important Sheetal.

Please actively work on the FAQ. Make sure you capture the questions and don't worry about answers.

**Comment by Sheetal777** [comment]
Yes, @proful We will take care of that part. Thank you for assigning.

**Comment by piratelicorne** [comment]
> This is what we got so far.

FAQs (Twindle)
------------------------------------

### General

⭐️ What is our tech stack?
- HTML, CSS & Java.
- No framework.
- No extra dependency.

⭐️ How tasks will be distributed?
- We will came up with a process to distribute tasks.
- Basically, there will be 4 parts: 
A) Beginner
B) Independent
C) Active
D) Expert
- Tasks will be distributed accordingly in small groups.

⭐️ When will we start working on this?
- We can start within a week because there are many beginners who would need assistance. Hang on with us :)

⭐️ Is there any pre-requisite to be a part of Twindle?
- No, you can contribute to the project in these ways:
 Team: Helping each other, speaking up, pair programming, making and sharing videos (for this project).
 Github: Updating the first PR and README.md, posting questions, or discussing in the issues created.

### Google Meet

⭐️Rules
- Mute yourself
- Unmute only if you are speaking
- Stay in a noise-free environment
- If you are in a noisy environment don't speak

⭐️ What will be the Google Meet timing?
- 5 pm IST

⭐️ How to know what happened during that Google meet if I missed?
- Someone will take notes and share it with the team.

### Github

⭐️ What to do next after creating a GitHub account?
- Fork the project from this link -> https://github.com/twindle-co/twindle
- Create the first PR (We will do a guide/video for this) in the master (main) branch.

⭐️ How to fork?
- We'll do a video about it, and we can share the link in this answer.

⭐️ How to create first PR?
- video > https://drive.google.com/file/d/1JUercd6IrXbeKd2PlhNh0tD5je4WAKUy/view

⭐️ What are the two necessary tasks for being a part of Twindle (through Github)?
- Make your file in 'firstpr' folder in https://github.com/twindle-co/twindle with: <your-name>.md, commit, and raise a PR #1
- Make few changes in <your-name>.md file, commit, and use a "CLI" to raise PR#2

### Logo

⭐️ Where to make the logo from?
- May use free platforms like Canva, Gimp, or Inkspace
- Use photoshop (if you already have the software)

⭐️ How to share the logo I made?
- Comment on the issue #4 "We need a logo" raised by johnjacobkenny
- Share in the respective twitter group you belong to.

⭐️ Is it necessary to make a logo?
- No, it is just a part of the project. So, if you are not comfortable with it, its okay.

**Comment by proful** [comment]
Excellent work!!

**Comment by therealJimoh** [comment]
> This is what we got so far.
> 
> FAQs (Twindle)
> General 👥
> What is our tech stack?
> 
> HTML, CSS & Javascript.
> No framework.
> No extra dependency.
> How tasks will be distributed?
> 
> We will came up with a process to distribute tasks. 🕑
> Basically, there will be 4 parts:
> A) Beginner
> B) Independent
> C) Active
> D) Expert
> Tasks will be distributed accordingly in small groups.
> When will we start working on this?
> 
> We can start within a week because there are many beginners who would need assistance. Hang on with us :)
> Is there any pre-requisite to be a part of Twindle?
> 
> No, you can contribute to the project in these ways:
> Team: Helping each other, speaking up, pair programming, making and sharing videos (for this project).
> Github: Updating the first PR and README.md, posting questions, or discussing in the issues created.
> Google Meet 📹
> Rules
> 
> Mute yourself
> Unmute only if you are speaking
> Stay in a noise-free environment
> If you are in a noisy environment don't speak
> What will be the Google Meet timing?
> 
> 5 pm IST
> How to know what happened during that Google meet if I missed?
> 
> Someone will take notes and share it with the team.
> Github 
> What to do next after creating a GitHub account?
> 
> Fork the project from this link
> Create the first PR (We will do a guide/video for this) in the master (main) branch.
> How to fork?
> 
> We'll do a video about it, and we can share the link in this answer.
> How to create first PR?
> 
> Pictures of step by step here
> Video of PR steps: 
> What are the two necessary tasks for being a part of Twindle (through Github)?
> 
> Make your file in 'firstpr' folder in https://github.com/twindle-co/twindle with: .md, commit, and raise a PR #1
> Make few changes in .md file, commit, and use a "CLI" to raise PR#2
> Logo 🎨
> Where to make the logo from?
> 
> May use free platforms like Canva, Gimp, or Inkspace
> Use photoshop (if you already have the software)
> How to share the logo I made?
> 
> Comment on the issue #4 "We need a logo" raised by johnjacobkenny
> Share in the respective twitter group you belong to.
> Is it necessary to make a logo?
> 
> No, it is just a part of the project. So, if you are not comfortable with it, its okay.

**Comment by therealJimoh** [comment]
> This is what we got so far.
> 
> FAQs (Twindle)
> General 👥
> What is our tech stack?
> 
> HTML, CSS & Java.
> No framework.
> No extra dependency.
> How tasks will be distributed?
> 
> We will came up with a process to distribute tasks. 🕑
> Basically, there will be 4 parts:
> A) Beginner
> B) Independent
> C) Active
> D) Expert
> Tasks will be distributed accordingly in small groups.
> When will we start working on this?
> 
> We can start within a week because there are many beginners who would need assistance. Hang on with us :)
> Is there any pre-requisite to be a part of Twindle?
> 
> No, you can contribute to the project in these ways:
> Team: Helping each other, speaking up, pair programming, making and sharing videos (for this project).
> Github: Updating the first PR and README.md, posting questions, or discussing in the issues created.
> Google Meet 📹
> Rules
> 
> Mute yourself
> Unmute only if you are speaking
> Stay in a noise-free environment
> If you are in a noisy environment don't speak
> What will be the Google Meet timing?
> 
> 5 pm IST
> How to know what happened during that Google meet if I missed?
> 
> Someone will take notes and share it with the team.
> Github 
> What to do next after creating a GitHub account?
> 
> Fork the project from this link
> Create the first PR (We will do a guide/video for this) in the master (main) branch.
> How to fork?
> 
> We'll do a video about it, and we can share the link in this answer.
> How to create first PR?
> 
> Pictures of step by step here
> Video of PR steps: 
> What are the two necessary tasks for being a part of Twindle (through Github)?
> 
> Make your file in 'firstpr' folder in https://github.com/twindle-co/twindle with: .md, commit, and raise a PR #1
> Make few changes in .md file, commit, and use a "CLI" to raise PR#2
> Logo 🎨
> Where to make the logo from?
> 
> May use free platforms like Canva, Gimp, or Inkspace
> Use photoshop (if you already have the software)
> How to share the logo I made?
> 
> Comment on the issue #4 "We need a logo" raised by johnjacobkenny
> Share in the respective twitter group you belong to.
> Is it necessary to make a logo?
> 
> No, it is just a part of the project. So, if you are not comfortable with it, its okay.

I think the answer to the first question is an error. We are using Javascript and not Java.

**Comment by piratelicorne** [comment]
corrected 😅

**Comment by proful** [comment]
I think wiki is not good idea.

Use https://github.com/twindle-co/twindle/blob/main/docs/FAQ.md

Send me PR

**Comment by proful** [comment]
Question: I joined today what shall I do?

- First PR
- Second PR
- Third PR

some more detailed steps helpful for new joining. Onboarding instructions.

**Comment by piratelicorne** [comment]
done in #242
