### ISSUE TITLE
Creating a HTML to PDF conversion in AWS Lambda

### ISSUE THREAD

**Issue by tolgaerdonmez** [twindle-co/twindle#400]
@proful like we discussed puppeteer could be heavy for lambda functions, I believe phantomjs would be heavy to, hence it is also using headless browser in the background. 
I saw a package in @praveen2896's pull request #365 he uses a package called [html-to-pdf](https://www.npmjs.com/package/html-to-pdf) which is a wrapper around a java library called Flyingsaucer. Perhaps it can be more lightweight but I'm not sure.

**Comment by tolgaerdonmez** [comment]
Actually it is also possible to just create the html page of the twit thread and the user itself can print the page to pdf in the browser or a button that saves the page in the front-end. Just an idea.

**Comment by tolgaerdonmez** [comment]
We could use web assembly maybe, also an idea

**Comment by proful** [comment]
Give it a try various approaches.

For phase 1 we will go npm route, so puppeteer is great.

Keep exploring different options. Raise a PR if you get any break through. Having the relevant source code in repo helps to iterate.

**Comment by tr0mbl3y** [comment]
![inpdf](https://user-images.githubusercontent.com/72851843/96712550-f0395280-13bc-11eb-8120-835eeb27ffee.png)
i added  a button so that user itself can print pdf.

**Comment by proful** [comment]
in the future, it can be re-opened.

Now cleaning up issues.
