### ISSUE TITLE
Creating a CLI in nodejs, which libraries to use, let's discuss!

### ISSUE THREAD

**Issue by tolgaerdonmez** [twindle-co/twindle#401]
I want to learn more about CLIs in nodejs.
Before I've created a CLI using inquirer you can see it [https://github.com/tolgaerdonmez/project-chef](here)
But this uses a prompt style so.

I want to use things such as args, flags. Which lib to use for simple CLIs.
Let's discuss and learn. 😁

**Comment by proful** [comment]
Ours is very simple and less options.

I am open to any suggestions. Raise PR😊

**Comment by michaelcosj** [comment]
I think we should go with [yargs](http://yargs.js.org/), it has a lot of features that I believe would be very useful.
I've made a small node app that showcases some of the features at PR #336

**Comment by johnjacobkenny** [comment]
I have seen this library called [React Ink](https://github.com/vadimdemedes/ink). Haven't used it at all but may be interesting to some even though we don't take it up

**Comment by proful** [comment]
I am fine with yargs created by @billgufran
