### ISSUE TITLE
Move franklinulrich.md to firstpr directory

### ISSUE THREAD

**Issue by frankiefab100** [twindle-co/twindle#403]
The file franklinulrich.md is not in  firstpr directory

![screenshot of the repo](https://user-images.githubusercontent.com/46662771/96656227-495ea300-1337-11eb-916f-16dcc9df2872.jpg)

**Comment by lh536** [comment]
I did it... waiting for PR review.

**Comment by pranavgoel29** [comment]
ok

**Comment by pranavgoel29** [comment]
> I did it... waiting for PR review.

Please mention someone in your PR so someone can take a look in it.
