### ISSUE TITLE
Auto assign merge conflict label

### ISSUE THREAD

**Issue by proful** [twindle-co/twindle#406]
- "merge conflict" label should be auto-assigned

- PR should be assigned back to the original author

- mention the author 
`"@proful please fix the merge conflict"`

**Comment by arthurbuhl** [comment]
We can also look into this GitHub action which checks all open Pull Requests for merge conflicts and marks them with a Github label. Also, once a conflict is resolved the label is automatically removed.

https://github.com/marketplace/actions/auto-label-merge-conflicts

**Comment by johnjacobkenny** [comment]
I'm looking into this and #407

**Comment by johnjacobkenny** [comment]
I have tried to integrate some sample actions in `/.github/workflows/`. It's not really working out.

There seems to be some limitations with the github workflow as documented here
https://github.community/t/github-actions-are-severely-limited-on-prs/18179/2

I don't know if that is the cause. Does anyone have some experience with this

**Comment by arthurbuhl** [comment]
In PR #425 it seems to work fine.

Also, can you try updating the `yml` code like:

```yml
on:
  pull_request:
    branches:
      - main
```

instead of

```yml
on:
  pull_request_target:
    branches: [ main ]
```

Docs: https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#example-using-multiple-events-with-activity-types-or-configuration

**Comment by johnjacobkenny** [comment]
@arthurbuhl I think the action is working. I didn't make this change yet.
