### ISSUE TITLE
Run the below programs and reply screenshot of output

### ISSUE THREAD

**Issue by proful** [twindle-co/twindle#408]
## Instructions

- Sync the project to get the latest copy
- Run below projects
- In the comment below put the screenshot of your output
- **ONE USER ONLY ONE COMMENT.** Edit your entry to update.

[![**YOUTUBE** Run other developer code](https://img.youtube.com/vi/BStPJrqOaEk/0.jpg)](https://youtu.be/BStPJrqOaEk)

## JavaScript/Node.js

[CLI to generate epub](https://github.com/twindle-co/twindle/tree/main/playground/cli/cli-epub) - `/playground/cli/cli-epub`

[JSON 2 PDF by @praveen2896 ](https://github.com/twindle-co/twindle/tree/main/playground/cli/jsonToPDF) - `/playground/cli/jsonToPDF`

[Markdown by @UnevenCoder](https://github.com/twindle-co/twindle/tree/main/playground/cli/markdown) - `/playground/cli/markdown`

[PDF using puppeteer by @tolgaerdonmez ](https://github.com/twindle-co/twindle/tree/main/playground/cli/pdf-from-html-cli) - `/playground/cli/pdf-from-html-cli`

[PDF from json @sammjainn ](https://github.com/twindle-co/twindle/tree/main/playground/cli/pdf-from-json) - `/playground/cli/pdf-from-json`

[Twindle CLI @michaelcosj ](https://github.com/twindle-co/twindle/tree/main/playground/cli/twindle_cli_node) -`/playground/cli/twindle_cli_node`

[Hello World PDF](https://github.com/twindle-co/twindle/tree/main/playground/cli/twindle_hello_world_pdf) - `/playground/cli/twindle_hello_world_pdf`

[Express Server by @kingsley-einstein ](https://github.com/twindle-co/twindle/tree/main/server) - `/server`

## HTML

[Run HTML views](https://github.com/twindle-co/twindle/tree/main/playground/twindleco) - `/playground/twindleco`

**Comment by johnjacobkenny** [comment]
## /playground/cli/cli-epub
![image](https://user-images.githubusercontent.com/19240564/96675510-a3d41f80-1388-11eb-85a7-06b73f5bdd98.png)
![image](https://user-images.githubusercontent.com/19240564/96675550-bc443a00-1388-11eb-9ac4-d97d6822f463.png)

## /playground/cli/jsonToPDF
this isn't working for me, I don't have java installed
![image](https://user-images.githubusercontent.com/19240564/96675784-50160600-1389-11eb-9b9f-ab9240ed42de.png)

Remaining I will update here.

**Comment by proful** [comment]
![image](https://user-images.githubusercontent.com/354596/96677100-9cc60500-13ba-11eb-9ce9-3ec84108299a.png)

**Comment by naveenkala** [comment]
# /playground/cli/cli-epub
![play1](https://user-images.githubusercontent.com/65217331/96678055-886c1300-138e-11eb-8fed-6d8a437eebba.jpg)


# /playground/cli/jsonToPDF
![play2](https://user-images.githubusercontent.com/65217331/96678418-45f70600-138f-11eb-8227-cf12bdf5e798.jpg)

# Will update for remaining

**Comment by wgaurav** [comment]
![IMG_20201021_112442](https://user-images.githubusercontent.com/67326005/96678874-33310100-1390-11eb-8a2d-27bc3b2aaaab.jpg)

**Comment by praveen2896** [comment]
/playground/cli/twindle_hello_world_pdf
![img2](https://user-images.githubusercontent.com/20437146/96680595-6d4fd200-1393-11eb-853b-c279707d1b2e.JPG)
![img1](https://user-images.githubusercontent.com/20437146/96680600-6f199580-1393-11eb-9b2d-5743bcce76ee.JPG)
/playground/cli/pdf-from-html-cli
![output](https://user-images.githubusercontent.com/20437146/96681263-99b81e00-1394-11eb-8b84-4bd11e98a97f.JPG)
![img4](https://user-images.githubusercontent.com/20437146/96681272-9d4ba500-1394-11eb-97dc-128a207881aa.JPG)

**Comment by EYRAM565** [comment]
playground/cli/jsonToPDF/output.html

![Screenshot (11)](https://user-images.githubusercontent.com/68958520/96682605-f73a7380-1370-11eb-9c63-6e8138e9762f.png)
![Screenshot (12)](https://user-images.githubusercontent.com/68958520/96682612-f86ba080-1370-11eb-8780-7ff5403e8ea3.png)
![Screenshot (13)](https://user-images.githubusercontent.com/68958520/96682614-f9043700-1370-11eb-9ca2-0b2f79aedcdc.png)

**Comment by tolgaerdonmez** [comment]
# I get an error when running /playground/cli/cli-epub

<img width="998" alt="image" src="https://user-images.githubusercontent.com/45141388/96681208-851d5b00-137f-11eb-9496-ffa104464d82.png">

# /playground/cli/jsonToPDF

<img width="796" alt="image" src="https://user-images.githubusercontent.com/45141388/96681535-18ef2700-1380-11eb-8f56-6b689748c10b.png">

#  /playground/cli/markdown

<img width="796" alt="image" src="https://user-images.githubusercontent.com/45141388/96681639-4a67f280-1380-11eb-8bcd-9df17e00a901.png">

# /playground/cli/pdf-from-html-cli
<img width="681" alt="image" src="https://user-images.githubusercontent.com/45141388/96681714-666b9400-1380-11eb-9cf3-6ea3acae922a.png">

#  /playground/cli/pdf-from-json
<img width="667" alt="image" src="https://user-images.githubusercontent.com/45141388/96681807-87cc8000-1380-11eb-8a6b-a8c16667729a.png">

# /playground/cli/twindle_cli_node
<img width="789" alt="image" src="https://user-images.githubusercontent.com/45141388/96681955-c19d8680-1380-11eb-928e-0337ac8e4da7.png">

#  /playground/cli/twindle_hello_world_pdf
<img width="672" alt="image" src="https://user-images.githubusercontent.com/45141388/96682022-ded25500-1380-11eb-9c14-be2aa0c16f4b.png">

#  /server
<img width="528" alt="image" src="https://user-images.githubusercontent.com/45141388/96682078-fdd0e700-1380-11eb-8221-c3c5d2dd28bd.png">

# /playground/twindleco
<img width="1183" alt="Untitled-1" src="https://user-images.githubusercontent.com/45141388/96683213-8308cb80-1382-11eb-9222-ab4762f953ac.png">

**Comment by teckiegeek** [comment]
![image](https://user-images.githubusercontent.com/36566559/96712555-3c719c00-1397-11eb-9489-7c9cd5898c44.png)

The section circled red needs to be responsive. I have not been able to do this because I am still learning how to make responsive websites. Can someone who is very good at making website responsive do this? Thank you.

**Comment by Na-ilah** [comment]
![image](https://user-images.githubusercontent.com/29338040/96720582-d9860200-13a2-11eb-8c80-849e100c685e.png)

**Comment by Mar-code** [comment]
![Screenshot (12)](https://user-images.githubusercontent.com/64645089/96736047-1dcdce00-13b4-11eb-8bfe-2c0485045ddf.png)
![Screenshot (13)](https://user-images.githubusercontent.com/64645089/96736107-2d4d1700-13b4-11eb-8d98-0f0aa08c2d11.png)
![Screenshot (14)](https://user-images.githubusercontent.com/64645089/96736119-30480780-13b4-11eb-9f77-9eefc22cb56e.png)
![Screenshot (15)](https://user-images.githubusercontent.com/64645089/96736161-3b029c80-13b4-11eb-8723-4d5fb37b2b91.png)
![Screenshot (16)](https://user-images.githubusercontent.com/64645089/96736173-3d64f680-13b4-11eb-890c-c638f5d0d773.png)

**Comment by Mar-code** [comment]
![Screenshot (18)](https://user-images.githubusercontent.com/64645089/96737541-b44ebf00-13b5-11eb-8e6a-03884ceb86e0.png)
![Screenshot (19)](https://user-images.githubusercontent.com/64645089/96737548-b6188280-13b5-11eb-9d34-fc5336f2e19c.png)
![Screenshot (20)](https://user-images.githubusercontent.com/64645089/96737551-b6188280-13b5-11eb-864f-e738cb40d35b.png)
![Screenshot (21)](https://user-images.githubusercontent.com/64645089/96737556-b6b11900-13b5-11eb-937c-c49ed54274da.png)
![Screenshot (22)](https://user-images.githubusercontent.com/64645089/96737561-b7e24600-13b5-11eb-9c47-6204207ecaa8.png)
![Screenshot (23)](https://user-images.githubusercontent.com/64645089/96737571-badd3680-13b5-11eb-8277-2ea228043e5e.png)
![Screenshot (24)](https://user-images.githubusercontent.com/64645089/96737574-bc0e6380-13b5-11eb-8e3b-0222b3da62f8.png)
![Screenshot (25)](https://user-images.githubusercontent.com/64645089/96737576-bca6fa00-13b5-11eb-9bbb-2de7afce78de.png)

**Comment by pranavgoel29** [comment]
##Getting error when running /playground/cli/cli-epub

![image](https://user-images.githubusercontent.com/48860494/96746414-c72cb800-13e4-11eb-945a-986c49fd9db2.png)

**Comment by ni3-kdm** [comment]
## Header
- Output:
![image](https://user-images.githubusercontent.com/72256599/96743324-7f586180-13e1-11eb-9ba9-7e9bf1f4d08d.png)
![image](https://user-images.githubusercontent.com/72256599/96750666-d7936180-13e9-11eb-826c-4d17cc26d352.png)
![image](https://user-images.githubusercontent.com/72256599/96750703-e4b05080-13e9-11eb-84da-46b1103db9ab.png)
![image](https://user-images.githubusercontent.com/72256599/96750740-f09c1280-13e9-11eb-9341-ee74415dd25b.png)
![html](https://user-images.githubusercontent.com/72256599/96750920-2e00a000-13ea-11eb-961a-cde442114c03.png)
![image](https://user-images.githubusercontent.com/72256599/96750984-41137000-13ea-11eb-8faf-02c2288978b8.png)
![html_demo](https://user-images.githubusercontent.com/72256599/96751045-57b9c700-13ea-11eb-919f-3ed9baa508c3.png)
![html_demo_1](https://user-images.githubusercontent.com/72256599/96751108-6bfdc400-13ea-11eb-8134-a76a845f1832.png)
![h_d_2](https://user-images.githubusercontent.com/72256599/96751182-80da5780-13ea-11eb-8597-58ef368a3378.png)
![h_d_3](https://user-images.githubusercontent.com/72256599/96751254-93549100-13ea-11eb-9cfe-00b070c74b54.png)


## Markdown
- Output
![image](https://user-images.githubusercontent.com/72256599/96746679-0f4bda80-13e5-11eb-9494-77e45dc8f5b3.png)

## JSON to PDF
- Output
![image](https://user-images.githubusercontent.com/72256599/96746969-5f2aa180-13e5-11eb-8f38-775874fb14a7.png)

## cli-epub (Note: Supported only for epub for now as per mentioned in readme.md)
- Installation:
![image](https://user-images.githubusercontent.com/72256599/96747785-57b7c800-13e6-11eb-9110-c05c8495e08a.png)
- Output
![image](https://user-images.githubusercontent.com/72256599/96748492-37d4d400-13e7-11eb-867f-2bbd16e1b9f2.png)
![image](https://user-images.githubusercontent.com/72256599/96748514-40c5a580-13e7-11eb-939e-6b59640a232e.png)

### pdf from html
- Output
![image](https://user-images.githubusercontent.com/72256599/96748973-dfea9d00-13e7-11eb-8cb5-d3431dc8d144.png)

### pdf from json
- Output
![image](https://user-images.githubusercontent.com/72256599/96749376-5c7d7b80-13e8-11eb-9f37-dabe53e5dbd3.png)

### twindle cli node
- Output
![image](https://user-images.githubusercontent.com/72256599/96750058-2c82a800-13e9-11eb-91ab-1cca398cabc0.png)

### twindle hello world
- Output
![image](https://user-images.githubusercontent.com/72256599/96750567-b3d01b80-13e9-11eb-8ef4-ed5bd614572a.png)

**Comment by stamenkovic-dev** [comment]
### /playground/twindleco/header/
![image](https://user-images.githubusercontent.com/72743233/96850251-e49a6a00-1456-11eb-9dfa-5548decc01bf.png)
![image](https://user-images.githubusercontent.com/72743233/96850339-fbd95780-1456-11eb-8cfa-2a61bf91be07.png)
![image](https://user-images.githubusercontent.com/72743233/96850456-21fef780-1457-11eb-923a-5dfb3518021a.png)
![image](https://user-images.githubusercontent.com/72743233/96850584-43f87a00-1457-11eb-973a-d0cb850abc49.png)
![image](https://user-images.githubusercontent.com/72743233/96850710-6c807400-1457-11eb-8c87-074266661444.png)
![image](https://user-images.githubusercontent.com/72743233/96850790-7f934400-1457-11eb-8895-497ecea21f70.png)
![image](https://user-images.githubusercontent.com/72743233/96850820-9174e700-1457-11eb-82f9-3f58e8e18572.png)

### /playground/twindleco/homepage/
![image](https://user-images.githubusercontent.com/72743233/96850999-cb45ed80-1457-11eb-9a1a-b653157446b3.png)
![image](https://user-images.githubusercontent.com/72743233/96851099-ef093380-1457-11eb-9b9c-e3ded2c7bbde.png)
![image](https://user-images.githubusercontent.com/72743233/96851188-0ba56b80-1458-11eb-8618-85c10a34849c.png)

**Comment by Yexiansen66** [comment]
/playground/cli/cli-epub
![61600b28e5326ee71ae6cbe649bfd38](https://user-images.githubusercontent.com/58055517/96947591-2d652800-1516-11eb-8342-1a12a5141861.png)

**Comment by wgaurav** [comment]
![IMG_20201021_112442](https://user-images.githubusercontent.com/67326005/96950505-18819800-1508-11eb-85c9-94dc6c5233a2.jpg)

**Comment by piratelicorne** [comment]
`/playground/cli/cli-epub`
<img width="1083" alt="Screen Shot 2020-10-27 at 01 35 48" src="https://user-images.githubusercontent.com/52439373/97265496-bfaa4c00-17f4-11eb-95d7-a4accdb4364a.png">

`/playground/cli/json-to-pdf-cli/` ⚠️  this route changed
<img width="1024" alt="Screen Shot 2020-10-27 at 01 41 11" src="https://user-images.githubusercontent.com/52439373/97265941-81615c80-17f5-11eb-85f8-f67978b952f3.png">
