### ISSUE TITLE
Organize into proper folder

### ISSUE THREAD

**Issue by proful** [twindle-co/twindle#409]
![image](https://user-images.githubusercontent.com/354596/96668086-24554900-13a6-11eb-81bd-8855f1d69e64.png)

## Folder

- header
- footer
- banner
- classification
- email
- team
- product

![image](https://user-images.githubusercontent.com/354596/96668758-92e6d680-13a7-11eb-9ea8-f8951aacf46e.png)

**Comment by lh536** [comment]
I think I did it... #410 Waiting for PR review.
