### ISSUE TITLE
Documentation: How to sync the main repo and own repo in GitHub.

### ISSUE THREAD

**Issue by praveen2896** [twindle-co/twindle#41]
To sync the main repo and own repo,

1. pointing to the main repo and pull from it, for that create a new remote in local for pointing the main repo . 
    `git remote add upstream https://github.com/twindle-co/twindle.git`
2. To download all the changes and commits from main Repo.
    `git fetch upstream`
3. The current branch will be updated to reflect the merge.
    `git merge upstream/main`
4. push the changes to own repository.
     `git push origin main`

**Comment by johnjacobkenny** [comment]
Great, @praveen2896 thanks for documenting this! @Sheetal777 or anyone else could verify?

**Comment by thunder-coding** [comment]
You have two options
- On your Git in VS Code, click on the three dot option and click push/pull
                                      OR
- In your terminal do this 'git push' or 'git pull'

Pull will get the latest changes from GitHub
And push will send your latest changes to GitHub

**Comment by johnjacobkenny** [comment]
@thunder-coding Could you collaborate on making sure this is a step by step explanation so that a newbie can understand? The discussion is about how to keep the forked repo in sync before creating PRs

**Comment by johnjacobkenny** [comment]
https://github.com/twindle-co/twindle/pull/8#issuecomment-708329032 may also be helpful

**Comment by arthurbuhl** [comment]
An important step is missed here.

Before you can [sync your fork](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/syncing-a-fork) with an upstream repository, you must configure a remote that points to the upstream repository in Git.

Here are the steps: [Configuring a remote for a fork](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/configuring-a-remote-for-a-fork)

**Comment by SwatiRaoDataEnthusiast** [comment]
AzureAD+SwatiAnandRao@LAPTOP-MJRBVINQ MINGW64 ~/Desktop/GIT/twindle (main)
$ git push origin main
****remote: Permission to twindle-co/twindle.git denied to SwatiRaoDataEnthusiast.
fatal: unable to access 'https://github.com/twindle-co/twindle/': The requested
URL returned error: 403****
I am getting above error when I am trying to push into origin?

**Comment by pranavgoel29** [comment]
You are making a commit directly to main repo. You have to first commit to your forked repo then you can make a PR from Github.

I have attached some snaps below.

Here you can see my origin is my forked repo link. You can check your's by running `git remote -v`.

![image](https://user-images.githubusercontent.com/48860494/96140210-5174a800-0f1d-11eb-839b-21e9444130fd.png)

Then after making changes you can run `git status` commands to check what changes you have made.

![image](https://user-images.githubusercontent.com/48860494/96140829-fdb68e80-0f1d-11eb-8475-7c14b1ae0793.png)

Here you can see I have made some changes to 'pranav.md' file.

So to push these changes to my forked repo I can run these commands.

1. `git add .`
2. `git commit -m "Updated pranav.md"`
3. `git push -u origin main`

![image](https://user-images.githubusercontent.com/48860494/96140581-b7612f80-0f1d-11eb-910d-6f52ecc90635.png)


Now they will be reflected to my forked repo.

![image](https://user-images.githubusercontent.com/48860494/96141389-96e5a500-0f1e-11eb-8ad4-4f07f35e35b2.png)


Now you can make a PR.

![image](https://user-images.githubusercontent.com/48860494/96141491-b250b000-0f1e-11eb-925a-f2b0445cf84d.png)

**Comment by pranavgoel29** [comment]
@johnjacobkenny Please pin this issue, as it is hard to find it now.

**Comment by johnjacobkenny** [comment]
Could someone follow up on getting this into FAQ on a priority

**Comment by MumbiGachomba04** [comment]
> @SwatiRaoDataEnthusiast
> 
> You are making a commit directly to main repo. You have to first commit to your forked repo then you can make a PR from Github to the main repo.
> 
> I have attached some snaps below.
> 
> Here you can see my origin is my forked repo link. You can check your's by running `git remote -v`.
> 
> ![image](https://user-images.githubusercontent.com/48860494/96140210-5174a800-0f1d-11eb-839b-21e9444130fd.png)
> 
> Then after making changes you can run `git status` commands to check what changes you have made.
> 
> ![image](https://user-images.githubusercontent.com/48860494/96140829-fdb68e80-0f1d-11eb-8475-7c14b1ae0793.png)
> 
> Here you can see I have made some changes in 'pranav.md' file.
> 
> So to push these changes to my forked repo I can run these commands.
> 
> 1. `git add .`
> 2. `git commit -m "Updated pranav.md"`
> 3. `git push -u origin main`
> 
> ![image](https://user-images.githubusercontent.com/48860494/96140581-b7612f80-0f1d-11eb-910d-6f52ecc90635.png)
> 
> Now they will be reflected to my forked repo.
> 
> ![image](https://user-images.githubusercontent.com/48860494/96141389-96e5a500-0f1e-11eb-8ad4-4f07f35e35b2.png)
> 
> Now you can make a PR.
> 
> ![image](https://user-images.githubusercontent.com/48860494/96141491-b250b000-0f1e-11eb-925a-f2b0445cf84d.png)


Just to add onto what @pranavgoel29  has said, you can change the path for origin using  
`git remote set-url origin _your forked repo url here_`

**Comment by johnjacobkenny** [comment]
@MumbiGachomba04 next time you can use the "Quote reply" option in the menu for any comment

**Comment by proful** [comment]
It should be closed?

**Comment by johnjacobkenny** [comment]
#450 if anyone picks up can close both issues

**Comment by proful** [comment]
@johnjacobkenny documentation related thing can be moved to appropriate file under docs & this issue can be closed.

**Comment by johnjacobkenny** [comment]
I'll close this since there is another issue to add it to docs #450
