### ISSUE TITLE
Google meet link?

### ISSUE THREAD

**Issue by johnjacobkenny** [twindle-co/twindle#414]
Yesterday before our discord meeting I had made a change to https://github.com/twindle-co/twindle/tree/main/docs

![image](https://user-images.githubusercontent.com/19240564/96681027-34642d00-1394-11eb-817a-397dbc9357e6.png)

But during the discord call we had some limitations. If we are continuing with google meet, could some one take up editing it back to have the meet link.

@proful please share your thoughts and the final confirmed meet link

**Comment by proful** [comment]
Use old one and update the docs

**Comment by naveenkala** [comment]
I will change it back.

**Comment by naveenkala** [comment]
Done  https://github.com/twindle-co/twindle/pull/416

**Comment by johnjacobkenny** [comment]
> Done #416

Closed through this

@naveenkala next time in the PR description you can write "closes #issue number" to auto close issue when pr is merged.
