### ISSUE TITLE
PR 4 Instructions

### ISSUE THREAD

**Issue by proful** [twindle-co/twindle#417]
1.  Upload your profile image into `/docs/images/team` folder
2. Give the name same as your first pr file name & use extension jpg, jpeg or png e.g., 'proful.png'
3. Edit TEAM.md to link to your image. Someone experienced with markdown come up with an initial design (size & placement). Other follow.

**This will improve your knowledge of merging.**

**Comment by teckiegeek** [comment]
Is this good to go or do we need to wait for @Akshay2996 to finish his task?

**Comment by Na-ilah** [comment]
Done 1 and 2. Need help with 3

**Comment by johnjacobkenny** [comment]
@Na-ilah dm me on twitter or discord

**Comment by Na-ilah** [comment]
@johnjacobkenny Okay, I am on twitter now

**Comment by vasudeveloper001** [comment]
I just added the link to my github avatar in the 3rd PR table.

**Comment by Akshay2996** [comment]
> Is this good to go or do we need to wait for @Akshay2996 to finish his task?

Hi @techgeek16 Me & @pranavgoel29 both have completed our task in hand. Just upload your image & follow what others are doing. If you have any problem DM me on [Twitter](https://twitter.com/AkshayS2909) regarding it.

**Comment by piratelicorne** [comment]
@lorennaleon @GorettiRivera :)
