### ISSUE TITLE
Issues encountered during Run the below programs and reply screenshot of output #408

### ISSUE THREAD

**Issue by proful** [twindle-co/twindle#418]
Report all issues here for #408 .

1 post per user - keep editing & updating.

First, explain the issue.
After you resolve mention how you resolve that.

**Comment by tusharkandpal** [comment]
![problem1](https://user-images.githubusercontent.com/66052835/96722755-59c05d80-13cb-11eb-914a-d4479140810f.JPG)

# Problem

I guess I need to install node.js.
Can somebody guide me through the initial steps?

**Comment by johnjacobkenny** [comment]
## /playground/cli/jsonToPDF
this isn't working for me, I don't have java installed
![image](https://user-images.githubusercontent.com/19240564/96675784-50160600-1389-11eb-9b9f-ab9240ed42de.png)

I'm assuming it will work if I install java. If anyone else encounters the same, please try installing.

**Comment by Mar-code** [comment]
![Screenshot (17)](https://user-images.githubusercontent.com/64645089/96735738-c7f92600-13b3-11eb-8abd-bd25ce1f47ce.png)

the epub and twitter_cli_node gave those errors

**Comment by Mar-code** [comment]
i already installed the node modules from vs code

**Comment by johnjacobkenny** [comment]
@Mar-code there probably isn't a `start` script mentioned in `package.json` file. Usually this can be run by using `node index.js`.

**Comment by pranavgoel29** [comment]
> ![Screenshot (17)](https://user-images.githubusercontent.com/64645089/96735738-c7f92600-13b3-11eb-8abd-bd25ce1f47ce.png)
> 
> the epub and twitter_cli_node gave those errors

To start

`node index -o <file format> -n <filename>`

**Comment by pranavgoel29** [comment]
## Getting error when running /playground/cli/cli-epub

![image](https://user-images.githubusercontent.com/48860494/96746414-c72cb800-13e4-11eb-945a-986c49fd9db2.png)

# I have solved the above error by installing the yargs package
write `npm i yargs` in your Terminal to solve this error

![image](https://user-images.githubusercontent.com/48860494/96750212-51771b00-13e9-11eb-81ce-9a89bf2e37fe.png)

**Comment by johnjacobkenny** [comment]
> ## Getting error when running /playground/cli/cli-epub
> 
> ![image](https://user-images.githubusercontent.com/48860494/96746414-c72cb800-13e4-11eb-945a-986c49fd9db2.png)
> 
> # I have solved the above error by installing the yargs package
> write `npm i yargs` in your Terminal to solve this error
> 
> ![image](https://user-images.githubusercontent.com/48860494/96750212-51771b00-13e9-11eb-81ce-9a89bf2e37fe.png)
> 

I think all the packages are mentioned in package.json file so you just need to run mom install which will install yargs and any other dependencies
