### ISSUE TITLE
Sending pdf, epub etc. to Kindle 

### ISSUE THREAD

**Issue by tolgaerdonmez** [twindle-co/twindle#426]
We could create a option to directly send created document to kindle.
There is a whitelist in the users amazon account, which allows from which email can kindle receive docs. There should be a guide to add twindle to users whitelist, so that we can send them the created doc.

**Comment by cankocman** [comment]
Yeah good idea. We can easily do that!

**Comment by tolgaerdonmez** [comment]
Want to create a guide for it ?

**Comment by proful** [comment]
Looking for PR on this?

**Comment by proful** [comment]
in the future, it can be re-opened.

Now cleaning up issues.
