### ISSUE TITLE
Adding Images in TEAM.md File

### ISSUE THREAD

**Issue by Akshay2996** [twindle-co/twindle#427]
![image](https://user-images.githubusercontent.com/37118877/96740007-0c012080-13de-11eb-9988-b01c5473288e.png)

@proful Do see if this is okay to put images like this

**Comment by Akshay2996** [comment]
![image](https://user-images.githubusercontent.com/37118877/96740173-3521b100-13de-11eb-972f-136e46df3317.png)

See also this. Your image is manually done from images folder while I took the photo from my github page & posted the link there.

**Comment by Akshay2996** [comment]
This is the updated & more clear version

![image](https://user-images.githubusercontent.com/37118877/96742286-584d6000-13e0-11eb-8f1a-00e83fb4d872.png)

**Comment by pranavgoel29** [comment]
### What about this?

![image](https://user-images.githubusercontent.com/48860494/96778920-ebe75680-1409-11eb-996c-43eaaef540e7.png)

**Comment by proful** [comment]
Both look good and I am fine with any one style. Raise a PR.

**Comment by pranavgoel29** [comment]
ok

**Comment by teckiegeek** [comment]
Well done Akshay! I like the first two styles! Great job!

**Comment by proful** [comment]
@Akshay2996 raise the PR

**Comment by Akshay2996** [comment]
I have decided to select @pranavgoel29 design for the markdown. It looks clean & I will be making changes & then raise a PR.

**Comment by arthurbuhl** [comment]
Keeping the images width & height to 40-50px would be nice I think, otherwise the `md` will fill up very fast and users might have scroll whole day to get to the bottom. Just wanted to share my views regarding this.

**Comment by Akshay2996** [comment]
Also see that my name is breaking because it's bigger & coming in two lines instead.

@pranavgoel29 if there's a workaround to this please see otherwise we should create a separate image column instead.

![image](https://user-images.githubusercontent.com/37118877/96834256-52e32a80-145f-11eb-8d62-b3b4a5715f4b.png)

**Comment by pranavgoel29** [comment]
To solve this we have to make a separate column for images

**Comment by pranavgoel29** [comment]
> @pranavgoel29 Do see your code because I'm unable to see your image & proful's even though they are there in the Team folder.
> And the alignment in the other image is also not happening.
> 
> ![image](https://user-images.githubusercontent.com/37118877/96833548-43171680-145e-11eb-9121-4f26fb238d58.png)
> 
> ![image](https://user-images.githubusercontent.com/37118877/96833714-81143a80-145e-11eb-9823-02c98871134a.png)
> 
> 

Have you wrote your's in markdown?
