### ISSUE TITLE
Youtube thumbnail for each video 

### ISSUE THREAD

**Issue by proful** [twindle-co/twindle#434]
Create thumbnail for the video uploaded.

Anyone can make thumbnail for any video. 

Examples of a good thumbnail. 

![Screenshot_20201022_111714](https://user-images.githubusercontent.com/354596/96803570-6f2f9900-1458-11eb-8724-11988cc90b61.jpg)

Example of a bad thumbnail 

![Screenshot_20201022_112002](https://user-images.githubusercontent.com/354596/96803654-9e460a80-1458-11eb-9822-e2581bce3a3a.jpg)

**Comment by johnjacobkenny** [comment]
I think @UnevenCoder was doing something on this?

**Comment by proful** [comment]
He is creating YouTube channel banner.

I need more hand for each video. So that video will look professional to new user.

**Comment by johnjacobkenny** [comment]
How does this look? We can try different variants, one for the daily meetings, and others for discussions, etc.

![youtube](https://user-images.githubusercontent.com/19240564/96879525-c9048300-1499-11eb-81c2-1cd06c57acdf.png)

**Comment by Na-ilah** [comment]
This looks, I suggest we move "twindle logo, where beginners contribute to open source " higher and then indent the second text "discussion with Tolga" to differentiate. 
Overall, great job ...

**Comment by proful** [comment]
@johnjacobkenny please implement @Na-ilah suggestions.

Post that kindly apply on YouTube channel.

**Comment by johnjacobkenny** [comment]
@Na-ilah how about now?

![youtube](https://user-images.githubusercontent.com/19240564/96887665-6ebbf000-14a2-11eb-8ab3-49acf42c0b85.png)

**Comment by Na-ilah** [comment]
This is better. Do you think we should change the font style of the second text "Discussion with  Tolga" ? To make differentiation easier?

**Comment by johnjacobkenny** [comment]
One problem is that the text isn't constant. Depending on the video title, it could be longer or shorter

**Comment by Na-ilah** [comment]
Alright... this works anyways :-)

**Comment by johnjacobkenny** [comment]
@Na-ilah I have tried to set the title for a few videos, just see how it looks. Also please ping me on twitter or discord.

**Comment by johnjacobkenny** [comment]
I am sharing the base svg file (https://github.com/twindle-co/twindle/blob/main/assets/youtube.svg) if anyone else would like to give it a try. I am also updating the thumbnails for a few of the videos so that we can get some comments from others.

**Comment by frankiefab100** [comment]
It's okay, submission for new logos is it till going on?

**Comment by Na-ilah** [comment]
I tried a new design for the thumbnail please check it out and give recommendations

![youtube_thumbnail](https://user-images.githubusercontent.com/29338040/97113731-930b0d00-16ec-11eb-8c8f-eb657cb0560a.png)

**Comment by chiomavera** [comment]
Arrangement are good but I think I prefer the previous color. I suggest that this current arrangement of text is use with the previous color.

**Comment by chiomavera** [comment]
> I tried a new design for the thumbnail please check it out and give recommendations
> 
> ![youtube_thumbnail](https://user-images.githubusercontent.com/29338040/97113731-930b0d00-16ec-11eb-8c8f-eb657cb0560a.png)

Arrangement are good but I think I prefer the previous color. I suggest that this current arrangement of text is use with the previous color.

**Comment by Na-ilah** [comment]
@chiomavera how about now?
![youtube_thumbnail2](https://user-images.githubusercontent.com/29338040/97114379-7cff4b80-16f0-11eb-8c3f-7ff0e38f51f3.png)

**Comment by johnjacobkenny** [comment]
@Na-ilah try to make the text for all the types of combinations on YouTube e.g. discussion, daily meeting, etc.

And just fyi the reason I made "where" and "contribute to" in a softer and lighter font is because that is not very important in that phrase. The important part is made intentionally bigger and more prominent esp with the choice of colors.

If anyone else has thoughts on these designs please comment. @frankiefab100 @sarathkumar6 @JoelVinayKumar

**Comment by Na-ilah** [comment]
![How to files](https://user-images.githubusercontent.com/29338040/97274467-fbfd9c80-1834-11eb-8920-e234dc14b629.png)
![madhu](https://user-images.githubusercontent.com/29338040/97274468-fd2ec980-1834-11eb-89b0-721583797b92.png)
![daily call](https://user-images.githubusercontent.com/29338040/97274474-fe5ff680-1834-11eb-9770-8dc4f20eb739.png)
@johnjacobkenny here are some sample files for the three types of videos we have so far on youtube

**Comment by johnjacobkenny** [comment]
@Na-ilah Looks good!

@proful I have a silly idea, which could be added to twindle-scripts. Do you want to create any automation (maybe a cli) for generating these types of images so that you can just run the cli to generate the custom image, so that anyone who is creating the youtube video can have the consistent logo.

**Comment by Na-ilah** [comment]
Thanks for the coaching @johnjacobkenny  😃

**Comment by proful** [comment]
There are 4 to 5 already have access. I don't mind to add if anyone is interested.

**Comment by sippeybro** [comment]
Size?

**Comment by johnjacobkenny** [comment]
@sippeybro this is about the static thumbnail for youtube video. We are not yet into creating an intro sequence within the video. If you'd like to may create an issue for that :partying_face:

**Comment by proful** [comment]
thumbnail designed bt @johnjacobkenny and @Na-ilah good enough
