### ISSUE TITLE
Github how to create table markdown

### ISSUE THREAD

**Issue by johnjacobkenny** [twindle-co/twindle#435]
Content by @arthurbuhl 

The issue is to display table we need the middle part like:

```md
| Name       | Description |
| ---------- | ----------- |
| A | B |
```

This looks like:

| Name       | Description |
| ---------- | ----------- |
| A | B |

<hr/>

But in your commit you have deleted the middle part `| ---------- | ----------- |` like:

```md
| Name       | Description |
| A | B |
```

Due to which it looks now like:

| Name       | Description |
| A | B |

<hr/>

So, just add that middle part back again and the Table format will work fine. Thanks!

_Originally posted by @arthurbuhl in https://github.com/twindle-co/twindle/pull/413#issuecomment-713753281_

**Comment by proful** [comment]
Please move to resources section/articles

**Comment by johnjacobkenny** [comment]
@twindle-co/developer if anyone wants to take this up?
