### ISSUE TITLE
Github Actions - Add documentation link

### ISSUE THREAD

**Issue by johnjacobkenny** [twindle-co/twindle#440]
We have a bot setup and its code is in `.github/workflows`. When there is a PR, and a conflict it will send this message currently.

![image](https://user-images.githubusercontent.com/19240564/96847832-45cf3700-1471-11eb-84f1-c99ef9e5f866.png)

Please alter the message so that it is more user friendly and also links to documentation explaining how to resolve the conflict.

**Comment by palashmon** [comment]
In case anyone is working on this issue, please note resolving merge conflicts docs can be found here: 

- [Resolving-merge-conflicts Wiki](https://github.com/twindle-co/twindle/wiki/Resolving-merge-conflicts)
- [Twindle Docs](https://github.com/twindle-co/twindle/issues/273)

Hope it helps!

**Comment by proful** [comment]
Move to docs
