### ISSUE TITLE
Github Actions - change the merge conflict tag

### ISSUE THREAD

**Issue by johnjacobkenny** [twindle-co/twindle#441]
The code for this action is in `.github/workflows`. When there is a merge conflict this adds a tag to the PR without any human intervention.

![image](https://user-images.githubusercontent.com/19240564/96848357-f4737780-1471-11eb-984c-53b15d97ae01.png)

But it should be 
![image](https://user-images.githubusercontent.com/19240564/96848698-5fbd4980-1472-11eb-88cc-0142283ac597.png)

**Comment by Akshay2996** [comment]
@johnjacobkenny Based on my search regarding this issue I couldn't find anything but I will list some resources where we might be able to figure something out.

**Resource**
- [Github Actions Workflow Syntax](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions)
- [Github Actions Official Docs](https://docs.github.com/en/free-pro-team@latest/actions)

**Comment by johnjacobkenny** [comment]
@Akshay2996 actually for this use case it was a text string change that was needed, which I left open to anyone else interested in giving it a try. Hence the labels `good first issue` and `help wanted`.

And I had made the change some time in between and forgot to update here! Sorry!

**Comment by Akshay2996** [comment]
No problem @johnjacobkenny Atleast I got to look at what Github actions are & will definitely try to learn & understand them for the future.

**Comment by johnjacobkenny** [comment]
Awesome! That was the intention :smiley:
