### ISSUE TITLE
Redirection issue from "twindle.co" to "www.twindle.co"

### ISSUE THREAD

**Issue by vijaya-bhaskar** [twindle-co/twindle#449]
### **Twindle website "twindle.co" not redirecting to "www.twindle.co"**

Currently if you try to open twindle.co for first time in a browser it will not open.
You can type "www.twindle.co" to open the site.

And once you open the site using "www.twindle.co" then twindle.co also opens. Because your browser now knows where to go.

Hi @proful please use [this link](https://in.godaddy.com/community/Managing-Domains/Need-help-on-redirecting-www-to-non-www/td-p/45214) to redirect twindle.co to "www.twindle.co" so that both work even at first time.

**Comment by proful** [comment]
Thank you @vijaya-bhaskar

I will try tomorrow.

**Comment by proful** [comment]
done
