### ISSUE TITLE
How to sync to the main repo from Visual Studio Code?

### ISSUE THREAD

**Issue by shekhar10feb** [twindle-co/twindle#458]
Here, I am assuming that you have already connected your **GitHub** account with the **Visual Studio Code**.

**Step 1:** First, Open the folder in **Visual Studio Code**, which is connected to your **GitHub** account.

![Screen1](https://user-images.githubusercontent.com/72906055/96881417-e1759d00-149b-11eb-932f-16e1fd2844c1.JPG)

**Ste 2:** Then, click on the **Source Control** button

![Screen2](https://user-images.githubusercontent.com/72906055/96881465-eb979b80-149b-11eb-91f0-dc08aa8db16b.JPG)

**Step 3:** After clicking the **Source Control Button**, you will see **Three dots**, click it then a **Dropdown** will appear like shown below, 

![Screen3](https://user-images.githubusercontent.com/72906055/96881506-f81bf400-149b-11eb-9fd2-939b3aff9626.png)

**Step 4:** Click **Pull, Push** button then another **Dropdown** will appear where you have to click **Pull from...** button

![Screen4](https://user-images.githubusercontent.com/72906055/96881545-023df280-149c-11eb-800f-f634c1856065.png)

**Step 5:** Here, you will see a **Box** with two options and you have to select **Upstream** option because **Origin** option is what you set it from your **GitHub** account, where you forked it from the main branch. Click **Upstream** option two times and wait for some times. Now your local repository is synced with main repo.

![Screen5](https://user-images.githubusercontent.com/72906055/96881590-0ec24b00-149c-11eb-95d5-6e6b8adb2b7a.png)

**Comment by johnjacobkenny** [comment]
Looks good to start with. You can also create an article in `docs/articles` and add a link in the main project readme so that it can be seen on the website.

**Comment by shekhar10feb** [comment]
> 
> 
> Looks good to start with. You can also create an article in `docs/articles` and add a link in the main project readme so that it can be seen on the website.

Ok, I am doing
