### ISSUE TITLE
Help needed for Code Splitting  

### ISSUE THREAD

**Issue by praveen2896** [twindle-co/twindle#469]
# Want to split the code into small pieces

[https://github.com/twindle-co/twindle/tree/main/playground/cli/json-to-pdf](url)

**Comment by proful** [comment]
@praveen2896 give more details on what you want other to do

**Comment by praveen2896** [comment]
> @praveen2896 give more details on what you want other to do


sure  @proful

**Comment by praveen2896** [comment]
I put all things like converting tempalte to html ,html to pdf stuffs in just one file [script.js](https://github.com/twindle-co/twindle/blob/main/playground/cli/json-to-pdf/script.js) . 

Need suggestions on how to split script.js into small pieces .

![snippet1](https://user-images.githubusercontent.com/20437146/96986179-ee979800-153e-11eb-99bb-64776cd7671c.JPG)

**Comment by vijaya-bhaskar** [comment]
@praveen2896 Lets do this! Ping me in discord.

**Comment by sarathkumar6** [comment]
@praveen2896 Feel free to reach out to me to file scaffolding.
