### ISSUE TITLE
Pull Request Issue

### ISSUE THREAD

**Issue by shekhar10feb** [twindle-co/twindle#476]
At the time of PR, there are two checks occur but there is some problem now with the second check. Every time it creates error.  
![Pic1](https://user-images.githubusercontent.com/72906055/97000807-ea767500-1554-11eb-9225-ad89b9349cef.JPG)

**Comment by Mar-code** [comment]
I think the error is because you need 2 approval before your pull request can be accepted

**Comment by johnjacobkenny** [comment]
This could be caused by the issue in the first interaction action. See issue here actions/first-interaction#23
