### ISSUE TITLE
Landing Page Inspiration

### ISSUE THREAD

**Issue by JoelVinayKumar** [twindle-co/twindle#477]
https://www.figma.com/file/34YX1uk6ZVhQWVzLyjzUdG/Twindle?node-id=0%3A1

Team, This issue is to encourage use of figma for our design part and make a thread for landing pages of other websites which we can be inspired.

![Team](https://user-images.githubusercontent.com/16177724/97008553-9b364180-1560-11eb-9029-e735fc0cc9ac.png)
![Team - Dark Mode](https://user-images.githubusercontent.com/16177724/97008554-9bced800-1560-11eb-98d2-21daf52c92db.png)
![Home - Dark Mode](https://user-images.githubusercontent.com/16177724/97008557-9c676e80-1560-11eb-8b40-5d8ec4447f32.png)
![Home - Light Mode](https://user-images.githubusercontent.com/16177724/97008560-9d000500-1560-11eb-933b-252b077d2116.png)

**Comment by Akshay2996** [comment]
Amazing work @JoelVinayKumar 🔥. Also look [Dribbble](https://dribbble.com/) for some landing page inspiration. Keep up the good work.

**Comment by johnjacobkenny** [comment]
This is lit 🔥 I'm on board!

**Comment by Mar-code** [comment]
This is dope.  I can implement this design with React

**Comment by vasudeveloper001** [comment]
@Mar-code We are not using React or any big library. Just plain HTML, CSS, and JavaScript.

**Comment by Mar-code** [comment]
Ohh,  alright that makes sense.

**Comment by JoelVinayKumar** [comment]
This is very light-weight UI. Doesn't take much to code in HTML or CSS.

**Comment by proful** [comment]
https://dribbble.com/shots/13955707-Candidate

https://dribbble.com/shots/14267126-Travel-Landing-Page-UX-UI-Design

https://dribbble.com/shots/14375856-landing-page-homepage

https://dribbble.com/shots/14359951-Fitness-Landing-Page

https://dribbble.com/shots/13934987-Ekokubki-Landing-Page

https://dribbble.com/shots/13023346-AI-Dashboard-Website-Design

https://dribbble.com/shots/14241343-marketing-web-ui-landing-page

**Comment by RafaelBatman55** [comment]
> https://www.figma.com/file/34YX1uk6ZVhQWVzLyjzUdG/Twindle?node-id=0%3A1
> 
> Team, This issue is to encourage use of figma for our design part and make a thread for landing pages of other websites which we can be inspired.
> 
> ![Team](https://user-images.githubusercontent.com/16177724/97008553-9b364180-1560-11eb-9029-e735fc0cc9ac.png)
> ![Team - Dark Mode](https://user-images.githubusercontent.com/16177724/97008554-9bced800-1560-11eb-98d2-21daf52c92db.png)
> ![Home - Dark Mode](https://user-images.githubusercontent.com/16177724/97008557-9c676e80-1560-11eb-8b40-5d8ec4447f32.png)
> ![Home - Light Mode](https://user-images.githubusercontent.com/16177724/97008560-9d000500-1560-11eb-933b-252b077d2116.png)

I loved your 'dark mode' icon!

**Comment by pranavgoel29** [comment]
I am late for this but here is my design. 😅

![Web 1920 – 1](https://user-images.githubusercontent.com/48860494/97630867-2b3f2400-1a56-11eb-9da7-a68c12dbdf44.png)
![Web 1920 – 2](https://user-images.githubusercontent.com/48860494/97630869-2d08e780-1a56-11eb-8b37-3751b6153c9b.png)
![Web 1920 – 3](https://user-images.githubusercontent.com/48860494/97630875-2e3a1480-1a56-11eb-846c-2844f81e95aa.png)
![Web 1920 – 4](https://user-images.githubusercontent.com/48860494/97630887-31cd9b80-1a56-11eb-9fb0-b568014f7684.png)

**Comment by pranavgoel29** [comment]
I am late for this but here is my design. 😅

![Web 1920 – 1](https://user-images.githubusercontent.com/48860494/97630867-2b3f2400-1a56-11eb-9da7-a68c12dbdf44.png)
![Web 1920 – 2](https://user-images.githubusercontent.com/48860494/97630869-2d08e780-1a56-11eb-8b37-3751b6153c9b.png)
![Web 1920 – 3](https://user-images.githubusercontent.com/48860494/97630875-2e3a1480-1a56-11eb-846c-2844f81e95aa.png)
![Web 1920 – 4](https://user-images.githubusercontent.com/48860494/97630887-31cd9b80-1a56-11eb-9fb0-b568014f7684.png)

**Comment by pranavgoel29** [comment]
Updated the colours.

![Web 1920 – 1](https://user-images.githubusercontent.com/48860494/97700767-5ff0c100-1ad2-11eb-9bd7-fd4b297f031d.png)
![Web 1920 – 2](https://user-images.githubusercontent.com/48860494/97700783-64b57500-1ad2-11eb-967a-f2d0899efc08.png)
![Web 1920 – 3](https://user-images.githubusercontent.com/48860494/97700785-65e6a200-1ad2-11eb-969c-10da710f5067.png)
![Web 1920 – 4](https://user-images.githubusercontent.com/48860494/97700787-667f3880-1ad2-11eb-99c5-7c35a53da7ca.png)

**Comment by pranavgoel29** [comment]
Updated colours

![Web 1920 – 1](https://user-images.githubusercontent.com/48860494/97701717-dc37d400-1ad3-11eb-8892-f9d6f544a3e0.png)
![Web 1920 – 2](https://user-images.githubusercontent.com/48860494/97701721-de019780-1ad3-11eb-8e0d-b89fef1bdb66.png)
![Web 1920 – 3](https://user-images.githubusercontent.com/48860494/97701723-de9a2e00-1ad3-11eb-8657-6018ba56eae4.png)
![Web 1920 – 4](https://user-images.githubusercontent.com/48860494/97701724-dfcb5b00-1ad3-11eb-921b-d49e2cfba209.png)

**Comment by proful** [comment]
Landing page finalized by @JoelVinayKumar
