### ISSUE TITLE
[Documentation]: Pull Request description format

### ISSUE THREAD

**Issue by ni3-kdm** [twindle-co/twindle#480]
## Description
- Most of the times issues are linked with pull request but having one line description of task/issue will give quick detailed idea to reviewer/new developer to understand.

## Technical Approach
- What technical approaches followed to implement the task/issue?

## Manual Testing
- Add all the tested scenarios.
- This will give quick overview of covered scenarios to reviewer/new developer to understand and report missing scenarios.

## UI Updates
- Good to have a screenshot of UI changes for quick preview.
- For no UI changes, add **N/A** in this section.

**Comment by ni3-kdm** [comment]
**_[Note: Add/update missing points]_**

**Comment by arthurbuhl** [comment]
This template can be use for #101

**Comment by proful** [comment]
@ni3-kdm perfect initiative

**Comment by proful** [comment]
We have simple PR template good for now
