### ISSUE TITLE
Github action greetings.yml failing for every new PR

### ISSUE THREAD

**Issue by arthurbuhl** [twindle-co/twindle#481]
It seems that GitHub action `greetings.yml` has been failing recently for every new PR.

- https://github.com/twindle-co/twindle/pull/468/checks?check_run_id=1296861443
- https://github.com/twindle-co/twindle/pull/475/checks?check_run_id=1298920223
- https://github.com/twindle-co/twindle/pull/471/checks?check_run_id=1296984147

This might be related to https://github.com/actions/first-interaction/issues/10

We should remove this Github action for now until this known bug is fixed.

**Comment by Akshay2996** [comment]
@johnjacobkenny see this issue because @ni3-kdm also raised this issue & I also did some research on it & found out it's the problem from the main script from which we are taking this script.

**Comment by Akshay2996** [comment]
One solution I found is to use this greeting message bot which is available on [Github](https://github.com/kaxil/boring-cyborg)

Do see if it's working if any of you have the time?

**Comment by proful** [comment]
Raise a PR to disable /remove it temporaril.
