### ISSUE TITLE
One of the Github actions are failing - Important - Disable or remove the Github action Greeting

### ISSUE THREAD

**Issue by Mira-Alf** [twindle-co/twindle#485]
I noticed that one of the action checks greeting was failing. I am not familiar with Github actions/workflow. But I was trying to look at the logs to see what changed between when it was working and failing

When actions were successful:
![image](https://user-images.githubusercontent.com/64691316/97063555-05310400-15be-11eb-9824-c8ad8244f98b.png)

When actions began failing:
![image](https://user-images.githubusercontent.com/64691316/97063610-4a553600-15be-11eb-8f4c-19c98bc4551f.png)

It looks like an upgrade issue - anyone who is familiar with Github workflow please take a look. I will try some more googling to see what can be done. But this seems to be a show stopper for people trying to commit files. Needs to be looked at right away.

**Comment by Mira-Alf** [comment]
Okay now I feel foolish - even without the checks passing, PRs are being approved and being merged. So yes if it is not that critical, we can let it go. But I was curious as to why it was failing. If someone finds the solution and why the checks were not passing, please mention it as a comment on this issue. And close this issue. Thanks guys!

**Comment by proful** [comment]
@Mira-Alf why can't we remove the file @johnjacobkenny
