### ISSUE TITLE
[Tip] Add your GitHub Profile image

### ISSUE THREAD

**Issue by palashmon** [twindle-co/twindle#492]
### Get your GitHub Profile image

- You can easily add your GitHub profile image without uploading any images to local `/docs/images/team`, by appending `.png` to the URL of your GitHub's profile to get redirected to your avatar. So, if your GitHub profile url is like `https://github.com/proful` for example, then you can get your avatar using `https://github.com/proful.png`, just adding `.png` at the end.

### More Examples:

1. **Actual Avatar (full size)**

    Image Url:
	```html
	https://github.com/proful.png
	```
	Markdown:
	```md
    ![avatar](https://github.com/proful.png)
    ```
    Display like:

    ![avatar](https://github.com/proful.png)

<hr/>

2. **Resized Avatar (200 px)**

    Image Url:
	```html
	https://github.com/proful.png?size=200
	```
	Markdown:
	```md
    ![avatar](https://github.com/proful.png?size=200)
    ```
    Display like:

    ![avatar](https://github.com/proful.png?size=200)

<hr/>

2. **Resized Avatar (40 px)**

    Image Url:
	```html
	https://github.com/proful.png?size=40
	```
	Markdown:
	```md
    ![avatar](https://github.com/proful.png?size=40)
    ```
    Display like:

    ![avatar](https://github.com/proful.png?size=40)

**Comment by Akshay2996** [comment]
Hi @palashmon many people don't have an Image on **Github** that is why there is an alternative approach taken.

I also think that Github images should be the way to do because we don't need to create a specific folder for the images and keep it in our repo.

What do you think about this @proful should we use this way given to us?

**Comment by proful** [comment]
For team.md it is not necessary as we are adding image for learning purpose and to experience merge conflicts.

However you can use this approach to the team page you are building.

**Comment by arthurbuhl** [comment]
I think this is a amazing tip to know as a beginners, as we can now use this approach as a fallback image for all the users until they can upload main image to the local or incase they don't want to upload the same image they already have in GitHub profile. Also, this tip can be used for any future projects by the beginners while they are building something related to GitHub Api/profile.

**Comment by proful** [comment]
implemented
