### ISSUE TITLE
Create twindle-cli project under playground/cli

### ISSUE THREAD

**Issue by proful** [twindle-co/twindle#505]
![image](https://user-images.githubusercontent.com/354596/97132034-d66f8500-1799-11eb-9bb2-a93fbb4e83f9.png)

- copy the pdf program here
- copy the epub program here
- copy the MD program here
- copy the CLI program here

**Comment by michaelcosj** [comment]
I'll like to take this up

**Comment by proful** [comment]
@vijaya-bhaskar @johnjacobkenny this task is going to be important to encourage everyone to work together.

**Comment by johnjacobkenny** [comment]
@proful yes I agree! :partying_face: 

@michaelcosj let's get the minimum out and then we can organize and split some tasks for others

**Comment by michaelcosj** [comment]
@johnjacobkenny 
I just sent in a PR #536 
I created the twindle-cli folder in playground/cli and added the folders into it

**Comment by proful** [comment]
Please don't close this issue. Next step is to copy other relevant code here.
