### ISSUE TITLE
Article on publishing a package to npm

### ISSUE THREAD

**Issue by johnjacobkenny** [twindle-co/twindle#506]
Might be interesting for anyone wanting to try out publishing to npm. Anyone can do this, just need an npm account!

https://zellwk.com/blog/publish-to-npm/

**Comment by praveen2896** [comment]
I created one sample package in npm - lucifier-package , thanks @johnjacobkenny

**Comment by proful** [comment]
@johnjacobkenny please move it to resources/docs folder

**Comment by johnjacobkenny** [comment]
Done
