### ISSUE TITLE
Vote for Alpha Version of Design for Landing Page

### ISSUE THREAD

**Issue by vasudeveloper001** [twindle-co/twindle#509]
This is the issue thread where we will be voting for the alpha version of design for landing page. Post the screenshots of your design here to put it up for voting, so that we can start with front-end landing coding for demo product from next week to work on. 

The aim is to start the synchronous working on single codebase from next week so must choose a bare minimum common design and proceed with making that the main codebase for HTML5, CSS3, and JavaScript for now.

**Comment by vasudeveloper001** [comment]
**vasudeveloper001 design for pre-launch and post-launch landing page**

**Pre-Launch Landing Page**
![vasudeveloper001-pre-launch](https://user-images.githubusercontent.com/56103269/97170577-ef843000-17b1-11eb-8b39-27e7e847e107.png)

**Post-Launch Landing Page**
![vasudeveloper001-post-launch](https://user-images.githubusercontent.com/56103269/97170585-f317b700-17b1-11eb-9670-351e2137c9f7.png)

**Comment by vasudeveloper001** [comment]
**Design Submitted by @frankiefab100 **

![frankiefab100](https://user-images.githubusercontent.com/56103269/97170653-12164900-17b2-11eb-9d92-4ac92bcb1571.png)

**Comment by vasudeveloper001** [comment]
**Design by @JoelVinayKumar**

![JoelVinayKumar](https://user-images.githubusercontent.com/56103269/97170752-383be900-17b2-11eb-8642-cc9445a9f1af.jpg)

**Comment by JoelVinayKumar** [comment]
@vasudeveloper001  This is not my design. Mine is here:
https://www.figma.com/file/34YX1uk6ZVhQWVzLyjzUdG/Twindle?node-id=0%3A1

**Comment by vasudeveloper001** [comment]
> @vasudeveloper001 This is not my design. Mine is here:
> https://www.figma.com/file/34YX1uk6ZVhQWVzLyjzUdG/Twindle?node-id=0%3A1

Ok. Please paste the screenshots here or figma link is fine as well
