### ISSUE TITLE
Spike Twitter api fetch tweets 

### ISSUE THREAD

**Issue by proful** [twindle-co/twindle#511]
Write a hello world program for fetching tweets.

Use v1 or v2. 

Try not to use any node module. Also don't commit twitter API key!!

Bonus points after the minimum implementation --> cli with arguments
1. the API key
1. the thread URL

**Comment by johnjacobkenny** [comment]
Anyone taking this up can take a look at `https://github.com/twindle-co/twindle/tree/main/playground/mock` for some useful content

**Comment by Mira-Alf** [comment]
Michael and i are working on this.

**Comment by arthurbuhl** [comment]
> Try not to use any node module. Also don't commit twitter API key!!

We can also use [dotenv](https://www.npmjs.com/package/dotenv) package to create environment variables and hide the API keys.

Here is great [blog post](https://medium.com/@thejasonfile/using-dotenv-package-to-create-environment-variables-33da4ac4ea8f) regarding it. Thanks.

**Comment by johnjacobkenny** [comment]
Nice quick blog post!
