### ISSUE TITLE
Create Team and their tasks

### ISSUE THREAD

**Issue by piratelicorne** [twindle-co/twindle#531]
**Currently members**
- [x] Mentors selection. 
- [ ] Make Teams of 15 +-  members, this will give better view for management.
- [ ] Set tasks for every teams, could be similar tasks for each team.
- [ ] Create activities as live sessions or videos according to topics.

**Newcomers**
Update the ONBOARDING with:
- [ ] Set a group of people that will be available to be contacted and give an introduction.
- [ ] "Join a Team" option

@vijaya-bhaskar @EYRAM565

**Comment by piratelicorne** [comment]
We have mentors! 🥳

HTML & CSS
-------------
Sarath
Vijaya Bhaskar
Melissa

JavaScript
-------------
Kenny
Mira Alfassa
Vijaya Bhaskar

**Comment by Akshay2996** [comment]
I can also mentor people with HTML & CSS @piratelicorne

**Comment by johnjacobkenny** [comment]
And I think @JoelVinayKumar also volunteered

**Comment by piratelicorne** [comment]
> I can also mentor people with HTML & CSS @piratelicorne

I added you :) thank you!

**Comment by lh536** [comment]
@piratelicorne how can I join a team?

**Comment by piratelicorne** [comment]
to a team? we are going to group people! or to help grouping?

**Comment by proful** [comment]
Closing this. Please co-ordinate in twitter or discord group.
