### ISSUE TITLE
Inconsistent Image widths in TEAM.md

### ISSUE THREAD

**Issue by arthurbuhl** [twindle-co/twindle#533]
## Description

Image widths and height are not consistent for everyone in **TEAM.md** file. Images are set to different sizes like 100, 60, 80px. We need to maintain some consistency here and just use one resolution for all the images.

**My vote is for**: 80x80 px (_as most images are set to this resolution_).

Please let discuss on this and come to a conclusion and then someone can make a PR to fix them all and get it merged asap. We might need to add this point also to the CR Checklist.

## Attach Screenshot

![Twindle_github_issue](https://user-images.githubusercontent.com/40258253/97341143-aebc1200-18aa-11eb-9971-3ca28499ef75.png)

**Comment by RafaelBatman55** [comment]
I agree with your suggestion. 80x80px is enough to recognize our pretty faces. 🤣

I can be resposible for this PR after more people discuss here btw

**Comment by proful** [comment]
Agree for 80x80 px

**Comment by arthurbuhl** [comment]
@twindle-co/developer: Please everyone cast your vote, whenever you are free once.

@RafaelBatman55: Sure will assign the issue to you once the discussion is over. 

Thanks.

**Comment by johnjacobkenny** [comment]
Yes I agree too

**Comment by naveenkala** [comment]
I agree too.

**Comment by Neaz-Mahmood** [comment]
80 x 80 looks good

**Comment by EYRAM565** [comment]
80 x 80

**Comment by RafaelBatman55** [comment]
PR #553 created!

Please review! I'm not sure if Intermediate group images were all changed.

**Comment by proful** [comment]
Merged the PR by @RafaelBatman55
