### ISSUE TITLE
Demonstration: HTML & CSS demo for newbies

### ISSUE THREAD

**Issue by ad3rinto** [twindle-co/twindle#541]
Challenge: Newbies may get lost in the amount of work that is on going and feel unable to contribute 

This demonstration is an online session performed by a developer to walk beginners through the HTML and CSS codes of the agreed user interface ( or any of the options) so that beginners understand a bit more how the code translates to the visual representation.

This session will be:

1. Recorded
2. performed over discord (or google meet)
3. An HTML/CSS channel will be created on discord for follow up
4. Time - TBD

**Comment by geowen74** [comment]
thanks but what time is it

**Comment by piratelicorne** [comment]
🙋🏽‍♀️

**Comment by proful** [comment]
Shekhar Ranjan -- HTML
Melissa - CSS
tr0mbley - JavaScript
Nitin Kadam - HTML, CSS, JS, Git

**Comment by teckiegeek** [comment]
I'm sorry I'm just reading this message and I'm currently on a very tight schedule. I've never done a video but I will find time to do one soon.

**Comment by vasudeveloper001** [comment]
This will be helpful for someone like me who is new to open source

**Comment by proful** [comment]
Closing this. Please co-ordinate in twitter or discord group.
