### ISSUE TITLE
Improving Twitter API Integration Code - Handling Error Scenarios

### ISSUE THREAD

**Issue by Mira-Alf** [twindle-co/twindle#552]
- Handling error scenarios -
Timeout Errors, 400/401 Authorization issues, Older than 7 days tweet issues
- Migrate to ES6 - code looks cluttered with require and module.exports syntax - would be better to use import and export keywords - how to test on node.js using the ES6 keywords? I am no JS expert
- Need to check if newer tweets are available - to update the thread?? track the tweet_id of the tweets - get the last tweet and check conversation thread again?? Would this be useful?

@johnjacobkenny @proful others please comment

**Comment by proful** [comment]
@Mira-Alf please create multiple issues

**Comment by Mira-Alf** [comment]
Possible error scenarios:

1. Timeout Errors due to connectivity issues
2. 400/401 responses - possible reasons are Authorization issue, incorrect tweet id or user handle, tweet deleted and so on.
3. Older than 7 days tweet issues - incomplete set of tweets will be returned in the thread

What should we do in each of the scenarios in the code? Code should be updated accordingly.

**Comment by Mira-Alf** [comment]
@PuruVJ has started working on this. Once his code has been submitted, we can test the error scenarios mentioned here and close this issue.

**Comment by proful** [comment]
Closing this issue. This is very generic. We can be specific.
