### ISSUE TITLE
Improving Twitter API Integration Code - Updating an existing thread feature?

### ISSUE THREAD

**Issue by Mira-Alf** [twindle-co/twindle#555]
### Updating an existing tweet thread
We will not probably need this. But I want to cover this scenario in case a future need arises. 
Easy enough to accomplish this by tracking the tweet_id and conversation_id in the custom twitter response that we create for pdf rendering.
So given a conversation_id, we need to find tweets later than a specific tweet_id. We may need to modify the twit_thread.json format a little. Need some direction on this.

**Comment by PuruVJ** [comment]
Been inactive for 6 days. Is it resolved yet?

If it is, then please Close it.

**Comment by proful** [comment]
@Mira-Alf @PuruVJ  any progress?

**Comment by PuruVJ** [comment]
I still don't understand what this is for 😅
