### ISSUE TITLE
Help figuring out how to use prettier?

### ISSUE THREAD

**Issue by Mira-Alf** [twindle-co/twindle#558]
If I want to enforce the coding style listed in prettierrc what steps should I follow?
* Do npm install all the eslint dependencies listed in package.json. ( 8 packages )
* How should I use the fix feature? Any examples will be appreciated. I tried looking at the documentation page:
[Documentation for prettier-eslint](https://www.npmjs.com/package/prettier-eslint)

Any small pointers will be appreciated.

**Comment by Akshay2996** [comment]
@Mira-Alf I am unable to grasp the overall question you are conveying here but based on my understanding here is the solution.

- If you are using **VS Code** you can install the extension **Prettier** which will handle the rest for you.

Feel free to follow on regarding the issue at hand. And also post this issue in the twitter & discord channel too.

**Comment by arthurbuhl** [comment]
I think we will need a documentation and YouTube videos mentioning all the steps of Eslint & prettier setup using VS Code soon, otherwise it might become a difficult tool to implement for the beginners.

**Comment by proful** [comment]
For now removed dependency of prettier & eslist just to lower the barrier of entry
