### ISSUE TITLE
Landing page enhancements needed

### ISSUE THREAD

**Issue by vasudeveloper001** [twindle-co/twindle#562]
**Problems**
- [x] Remove the -webkit and -mz lines from our style.css file in /twindle-web/style.css
- [ ] Enhance the banner design and put it on the web page.
- [ ] Retrieve the emails from form - form submission using JavaScript to Google Excel sheet.
- [x] Replace lorem ipsum with the real working text.

@twindle-co/html-css

**Comment by proful** [comment]
@vasudeveloper001 @JoelVinayKumar please elaborate.
So that @cankocman can pick and work!

**Comment by vasudeveloper001** [comment]
**Enhance the banner design and put it on the web page.**

This point is concerned with the main section in the code. See if you can come up with some more unique and clear design and layout for this section that doesn't feel empty. Submit for others to review and if others like it, it will be merged. Background color will remain what it is for now.
