### ISSUE TITLE
Wiki page for running the CLI Application

### ISSUE THREAD

**Issue by Mira-Alf** [twindle-co/twindle#566]
The following wiki page has been created for the steps to run the CLI application:
[Running the Twindle CLI Application](https://github.com/twindle-co/twindle/wiki/Steps-for-Running-the-Twindle-CLI-Application)

The wiki assumes that NodeJS is already installed and the end user is familiar with running NodeJS applications. If anyone wants to update the wiki for how to do that, please feel free to do that.

@johnjacobkenny can you add documentation label to this issue?

**Comment by proful** [comment]
Very good @Mira-Alf

npm install dotenv

No need to install one by one


npm install

Will install everything

**Comment by Mira-Alf** [comment]
@proful oops, I didnt know npm install will install everything.. Thanks, will edit the wiki

**Comment by johnjacobkenny** [comment]
@Mira-Alf you can use backticks to indicate code blocks. It makes it much more readable. e.g. `npm install`

**Comment by Mira-Alf** [comment]
@johnjacobkenny I guess you edited the wiki. I know I am being a pain with this markdown format. Sorry.

**Comment by johnjacobkenny** [comment]
@Mira-Alf I can see that you like perfection (trust me, I used to be like that) but in my personal experience perfection as a goal has only pulled me down. Now the metric I try to optimize for is progress. 

All I mean is that you can improve, and we are all here to improve, and we improve by making mistakes. :smiley:  You don't have to apologize :sweat_smile:

**Comment by proful** [comment]
Wiki looks good!
