### ISSUE TITLE
10 steps for creating your first pull request.

### ISSUE THREAD

**Issue by vijaya-bhaskar** [twindle-co/twindle#57]
I hope the following screenshots will help with your first pull request.

Firstly create your account on github and goto twindle repository page [here](https://github.com/twindle-co/twindle)
Now you can follow the following steps.

Step 1
![1](https://user-images.githubusercontent.com/5336488/96012183-7b689480-0e61-11eb-94b9-289c30811210.png)

Step 2
![2](https://user-images.githubusercontent.com/5336488/96012298-9a672680-0e61-11eb-8aa5-2c35611d6a77.png)

Step 3
![3](https://user-images.githubusercontent.com/5336488/96012404-b10d7d80-0e61-11eb-82d0-8a1fa147f7cd.png)

Step 4
![4](https://user-images.githubusercontent.com/5336488/96012445-bc60a900-0e61-11eb-8305-08d03a22fc85.png)

Step 5
![5](https://user-images.githubusercontent.com/5336488/96012476-c4b8e400-0e61-11eb-818d-705dafbe5cc1.png)

Step 6
![6](https://user-images.githubusercontent.com/5336488/96012512-ce424c00-0e61-11eb-8a03-a4d9d9e12d57.png)

Step 7
![7](https://user-images.githubusercontent.com/5336488/96012535-d4382d00-0e61-11eb-9b2c-319407fa7758.png)

Step 8
![8](https://user-images.githubusercontent.com/5336488/96012559-da2e0e00-0e61-11eb-8b1d-c7cfd39bccee.png)

Step 9
![9](https://user-images.githubusercontent.com/5336488/96012586-e0bc8580-0e61-11eb-906f-5577f5c2b075.png)

Step10
![10](https://user-images.githubusercontent.com/5336488/96012608-e619d000-0e61-11eb-9869-84e739b4b808.png)

**Comment by pranavgoel29** [comment]
@vijaya-bhaskar can you add some different colour in the background of text then it will be more easier to read the comments you added 😄

**Comment by vijaya-bhaskar** [comment]
I agree @pranavgoel29 but I cant add background color to the text now :)
But you can click on the image to open in a new window which would be clear.
Next time I will take that into consideration. Thank you.

**Comment by pranavgoel29** [comment]
@vijaya-bhaskar ok, no problem. 😄

**Comment by piratelicorne** [comment]
I think it's awesome and well explained! I did a video for it too, I'll post it here [![Watch the video]()](https://drive.google.com/file/d/1JUercd6IrXbeKd2PlhNh0tD5je4WAKUy/view)

Points covered:
- Create a reverse PR (from the twindle repo to yours, so you can get the updates) via Github
- Creat a file via Github
- Create PR (from your repo to twindle)

These steps are recommended only for the first pull request, since the task is only about creating one file without conflict.

**Comment by Mar-code** [comment]
Thanks, it was very helpful

**Comment by RafaelBatman55** [comment]
Thank you so much for this kind of tutorial! It will be quite useful!

**Comment by teckiegeek** [comment]
This is brilliant. Thank you so much for all these! Now I will be more confident to participate.

**Comment by geowen74** [comment]
woow I love it marvelous work. it is well explained. thank you

**Comment by proful** [comment]
Awesome Vijaya. Great step by step instructions.

**Comment by Abiolagbode** [comment]
this was really helpful, keep up with the good work team

**Comment by johnjacobkenny** [comment]
@vijaya-bhaskar 💯❤️

**Comment by piratelicorne** [comment]
This was referenced in the FAQ document and updated in the PR #89  ✅

**Comment by johnjacobkenny** [comment]
Please close this issue if completed

**Comment by johnjacobkenny** [comment]
This has been added into the website at https://twindle-co.github.io/twindle/docs/articles/creating-first-pull-request.html and in the repo at `/docs/articles/creating-first-pull-request.md`.
