### ISSUE TITLE
Older Tweets from Twitter

### ISSUE THREAD

**Issue by Mira-Alf** [twindle-co/twindle#571]
Hello all, here is an interesting Github repo I came across for fetching older tweets from a user timeline. 

Code written in Python - I am not familiar with Python, some one take a look and see if it can be used by us.. The code doesnt use the Twitter API for fetching the tweets: 
[Github repository to fetch older tweets](https://github.com/Jefferson-Henrique/GetOldTweets-python)

@vijaya-bhaskar maybe this will help?

**Comment by tolgaerdonmez** [comment]
It is using something like jquery, its name is pyquery 🙂

**Comment by vijaya-bhaskar** [comment]
Actually using Tweepy which is a popular twitter python library we can get the old tweet content.
I just tried with a Dec 25th 2018 tweet -- https://twitter.com/i/web/status/1077617314818912257
@Mira-Alf we can discuss on this.

![tweepy_test](https://user-images.githubusercontent.com/5336488/97903644-5c289d00-1d65-11eb-9d12-f3ce0393947d.png)

**Comment by PuruVJ** [comment]
Fixed now! Check out #693 #692
