### ISSUE TITLE
twindle-cli not working

### ISSUE THREAD

**Issue by proful** [twindle-co/twindle#574]
![image](https://user-images.githubusercontent.com/354596/97976761-39f35580-1e1f-11eb-92f0-68960dacb950.png)

@Mira-Alf @PuruVJ @tolgaerdonmez

**Comment by tolgaerdonmez** [comment]
I think it is a handled error message, does there any output in the pdf?

**Comment by proful** [comment]
nope!
I realized that twitter id doesn't exist. Better error message help instead of error 😀

**Comment by PuruVJ** [comment]
Right. I'll look into it.
