### ISSUE TITLE
twindle-cli sending pdf to kindle 

### ISSUE THREAD

**Issue by proful** [twindle-co/twindle#579]
Any approach is fine.

@tolgaerdonmez

**Comment by tolgaerdonmez** [comment]
@proful 

I'm not decided what to use now but, I couldn't setup the [**calibre cli**](https://manual.calibre-ebook.com/develop.html#macos-development-environment) to my path on macos, that bothered me so much, can you help me solve that ?"

**Comment by proful** [comment]
It's early morning here. I will explore few options today after 5-6hr.

**Comment by tolgaerdonmez** [comment]
Okay, thanks

**Comment by tolgaerdonmez** [comment]
I sent the pdf to kindle directly using email, and shows that kindle alone supports pdfs, but really in a pdf format instead of a readible book like I sent converted it by calibre.

![image](https://user-images.githubusercontent.com/45141388/98030261-ce5eb780-1e21-11eb-8d45-5bed12db083f.png)

**Comment by tolgaerdonmez** [comment]
> It's early morning here. I will explore few options today. We can have quick call today after 5-6hr ?

I solved this, I was having an issue special to my case, no need to look to this problem.

**Comment by tolgaerdonmez** [comment]
I did everything, other than sending the document to kindle using nodemailer, I think we need to set the attachment contentType encoding and such suitable to kindle because the same file works when I send with gmail. Help please!

**Comment by proful** [comment]
@tolgaerdonmez I have configured nodemailer.config.json doesn't seems to work!

No error

**Comment by tolgaerdonmez** [comment]
@proful 

So you need to add calibre command line tools to path to use node-calibre,
Add this to path: `/Applications/calibre.app/Contents/MacOS`

And also I can send mail using Nodemailer but the kindle doesn't recognize the book, which sent from Nodemailer.

**Comment by proful** [comment]
@tolgaerdonmez fixed that path issue and now same stage as you

**Comment by tolgaerdonmez** [comment]
@proful I couldn't get smtp-client to run, either it doesn't do auth, or just waits till timeout.

**Comment by tolgaerdonmez** [comment]
Now it sent, but none I receive.

![image](https://user-images.githubusercontent.com/45141388/98075969-6db19800-1e7e-11eb-9a19-36f81dbe2cd6.png)

Normally in Nodemailer I set the port to **465** but here it doesn't work unless **587**.

**Comment by proful** [comment]
hmm keep trying. I will also keep experimenting. 
@PuruVJ also looking
@johnjacobkenny can also help if he get time

**Comment by tolgaerdonmez** [comment]
Okay, it runs.
But when I sent mail to **tolgaerdonmez@gmail.com** doesn't receive
when I sent to **tolgaerdonmez@weblendir.com** it does recieve

**Comment by proful** [comment]
@tolgaerdonmez push the code. Don't overwrite node mailer code.

**Comment by tolgaerdonmez** [comment]
> @tolgaerdonmez push the code. Don't overwrite node mailer code.

I'm trying to add attachments, and afterwards sending it to kindle

**Comment by tolgaerdonmez** [comment]
@proful  I couldn't solve any further right now, I created a pr including it. someone could solve it :)
Pr #594

**Comment by proful** [comment]
no worries @tolgaerdonmez good progress :)
Merged ur PR

**Comment by tolgaerdonmez** [comment]
> no worries @tolgaerdonmez good progress :)
> Merged ur PR

thanks, hope we'll solve this problem. A question in my mind, can we send to kindle using AWS SES ? If it is possible I'll try it.

**Comment by proful** [comment]
Sure that is possible and a great idea

**Comment by tolgaerdonmez** [comment]
We could upload the created pdf's the S3 buckets

**Comment by johnjacobkenny** [comment]
So here is the process I went through,

Initially I sent a test email from my gmail. This worked.
Then Proful directed me on how to run the code, and I was able to send the email from my gmail id. However amazon was sending failure message for each email sent.

So I thought about taking a look at the raw email content to see if there are any differences. Using this option, I downloaded both emails.
![image](https://user-images.githubusercontent.com/19240564/98116438-45518a00-1ece-11eb-94e1-91e7352dfdd4.png)

So now I have the original one sent from gmail inbox, and the one sent from twindle.

![image](https://user-images.githubusercontent.com/19240564/98116943-0cfe7b80-1ecf-11eb-8241-b68aa6fba71b.png)

1. email sent through gmail
1. email sent through twindle cli
1. content type - multipart/mixed
1. content type - application/pdf

So I suspected that the content-type could be the issue. So I added a text field to the email sent by nodemailer. The mail now sent included the content type multipart/mixed and I did not receive any rejection mail. Waiting for @proful to verify though.

**Comment by Mira-Alf** [comment]
Amazing Kenny. True brain of a debugger.

**Comment by tolgaerdonmez** [comment]
@johnjacobkenny Verrrry awesome job kenny, I'm astonsihed. I also thought the mime type as thr problem but couldnt learn the truth:)
👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻

**Comment by proful** [comment]
Great efforts @johnjacobkenny

I spent few hours but couldn't figure out myself.

You debugging approach is spot on.

**Comment by johnjacobkenny** [comment]
Closed using PR #599

**Comment by johnjacobkenny** [comment]
If anyone can try, please run the code

**Comment by johnjacobkenny** [comment]
@proful Also just to mention if anyone who is trying has 2FA enabled for Gmail, they should generate an app password from google https://support.google.com/accounts/answer/185833?hl=en it is straightforward, they will generate a separate password which you can use instead of your usual gmail password.
