### ISSUE TITLE
Automate Readme.md

### ISSUE THREAD

**Issue by JoelVinayKumar** [twindle-co/twindle#595]
If some new contributor visits twindle, they will need to know the exact stack we're working on. This will help them decide if they want to join us or not. This is just a suggestion from me. We can market our project better through this. Refer sample image 1
We can also include one column of all our daily calls as a playlist and show like the second image.
[Readme.md](https://github.com/twindle-co/twindle/blob/main/README.md) -> Edit this READme.md including the tech stack like below one.

Here is the sample image 1:
![image](https://user-images.githubusercontent.com/16177724/98082592-00622f00-1e9f-11eb-8f76-17d0d5d3e2ed.png)

Here is the sample image 2:
![image](https://user-images.githubusercontent.com/16177724/98096941-542a4380-1eb2-11eb-82a9-a02f224117e9.png)

Refer this [Readme.md](https://github.com/codeSTACKr/codeSTACKr/blob/master/README.md)

Follow this tutorial if you have any doubt: 
[![Create Awesome Github Readme](http://i3.ytimg.com/vi/ECuqb5Tv9qI/hqdefault.jpg)](https://youtu.be/ECuqb5Tv9qI)

**Comment by proful** [comment]
I am fine with this. We can merge the PR if any one raises it..

**Comment by RafaelBatman55** [comment]
I can be responsible for this PR.

**Comment by johnjacobkenny** [comment]
@RafaelBatman55 go ahead

**Comment by johnjacobkenny** [comment]
Curious if this is working as expected?

![image](https://user-images.githubusercontent.com/19240564/98648994-03f12c80-235d-11eb-92eb-97619a3a6961.png)

**Comment by proful** [comment]
this is also broken

**Comment by RafaelBatman55** [comment]
I tried to keep in this list just the Google Meet's video playlist, but didn't work. 👎 

Hopefully @Akshay2996 checked this problem and prepared PR #743 (already merged).

**Comment by johnjacobkenny** [comment]
Yes I think so
