### ISSUE TITLE
Github pages not working

### ISSUE THREAD

**Issue by johnjacobkenny** [twindle-co/twindle#600]
![image](https://user-images.githubusercontent.com/19240564/98122447-a1201100-1ed6-11eb-9cc2-a5b0f2e834be.png)
![image](https://user-images.githubusercontent.com/19240564/98122461-a7ae8880-1ed6-11eb-833c-85a60af464cb.png)

**Comment by johnjacobkenny** [comment]
![image](https://user-images.githubusercontent.com/19240564/98649052-1b301a00-235d-11eb-83b9-89438e7e3472.png)

Fixed it. I had emailed github support asking what the problem was. They mentioned its in `docs/articles/sync-to-main-repo.md`. I took a look and it had two `---` lines in it. I think jekyll was having trouble detecting both as front matter or something along those lines.

**Comment by proful** [comment]
That's great @johnjacobkenny
