### ISSUE TITLE
Error running refactored cli code

### ISSUE THREAD

**Issue by johnjacobkenny** [twindle-co/twindle#601]
![image](https://user-images.githubusercontent.com/19240564/98124727-94e98300-1ed9-11eb-883d-00d89c34c1af.png)

I think I need to run `npm i` in the core folder as well, but would be nice if something can be done about this.

**Comment by tr0mbl3y** [comment]
@johnjacobkenny : like install all required  dependencies automatically would be a nice feature

**Comment by proful** [comment]
twindle-core not needed at this stage

**Comment by johnjacobkenny** [comment]
@proful the twitter api stuff has been moved to core 😅

So it worked after I did npm install in twindle-core

**Comment by johnjacobkenny** [comment]
> @johnjacobkenny : like install all required  dependencies automatically would be a nice feature

There is something called yarn workspaces which I think solves this, but that would be getting ahead of ourselves...

**Comment by proful** [comment]
Yes @PuruVJ reverted his changes. So it is working now.

**Comment by johnjacobkenny** [comment]
Great!
