### ISSUE TITLE
Update website according to new design

### ISSUE THREAD

**Issue by JoelVinayKumar** [twindle-co/twindle#603]
Here is the new design for our website. You can contribute to this under `twindle-web`

### Figma
Figma will help you with CSS and measurements.  
https://www.figma.com/file/34YX1uk6ZVhQWVzLyjzUdG/Twindle?node-id=0%3A1

### Guidelines
* There is absolutely no need to stick to measurement
* But, please stick to:
   - alignment
   - colors
   - font
   - font weight

These are the mockups. Comment below for any change/enhancement/whatever 😛
We will skip dark mode as of now. 
![Phase 1 - Light Mode - New](https://user-images.githubusercontent.com/16177724/98138579-42b05e00-1ee9-11eb-8e6e-e63874b10e82.png)

**Comment by teckiegeek** [comment]
I am completely blown away. Welldone team!
