### ISSUE TITLE
Change export html format

### ISSUE THREAD

**Issue by JoelVinayKumar** [twindle-co/twindle#604]
Here is the new design for our document. You can contribute to this under twindle-cli

### Figma
Figma will help you with CSS and measurements.
https://www.figma.com/file/34YX1uk6ZVhQWVzLyjzUdG/Twindle?node-id=0%3A1

### Guidelines
* There is absolutely no need to stick to measurement
* But, please stick to:
  - alignment
  - colors
  - font
  - font weight

These are the mockups. Comment below for any change/enhancement/whatever 😛
PS: There is an image in middle which didn't get exported.

![A4 paper format](https://user-images.githubusercontent.com/16177724/98141459-a7b98300-1eec-11eb-89c5-ae712342a22e.png)
![A4 paper format -Dark Mode](https://user-images.githubusercontent.com/16177724/98141711-eea77880-1eec-11eb-90d1-c0fae4cc2293.png)

**Comment by tolgaerdonmez** [comment]
This is a good idea, although for the docs, which we are sending to tidible, only need a proper font size, and spacing. Just though it was worth mentioning.
good designs 👍🏻👍🏻

**Comment by proful** [comment]
Agree with @tolgaerdonmez

**Comment by PuruVJ** [comment]
@JoelVinayKumar We need only white background, as our primary target is Kindle.

It would be great if you could recommend some minimalistic designs keeping the same layout as below
![image](https://user-images.githubusercontent.com/47742487/98461433-13903a00-21d2-11eb-8a24-e89fd9da275e.png)

**Comment by JoelVinayKumar** [comment]
You can follow this design. Just remove Twindle thread as heading

**Comment by JoelVinayKumar** [comment]
The same design I gave can be made monochrome as well

**Comment by PuruVJ** [comment]
I think we need to add a logo and stylised font, to show off a little branding. Can you propose minimalist design based on that?

A little screenshot with an SVG of logo or something would do.

**Comment by UnevenCoder** [comment]
maybe something on the corners ?

**Comment by PuruVJ** [comment]
I'm thinking a logo, and the text Twindle alongside it at the top. Nothing too grand, just some simple branding
