### ISSUE TITLE
Node v14 for the development stage

### ISSUE THREAD

**Issue by PuruVJ** [twindle-co/twindle#614]
If the title scared you, I implore you to keep an open mind.

I suggest that we the active devs on the coding side(primarily the CLI), for the duration of development, keep the de-facto version of Node JS to be the current LTS, which is v14.15.0

![image](https://user-images.githubusercontent.com/47742487/98186742-6ef1cc00-1f35-11eb-9e85-f5149d40a438.png)

### Why

Quite simple: **Optional Chaining**

Due to the nature of the twitter API, its easy to end up with spaghetti like this:

```js
responseJSON && responseJSON.data && responseJSON.data[0] && responseJSON.attachments && reponseJSON.attachments.media_key
``` 

The above snippet is nearly identical to the code I've run into when trying to write the script to render the images, Gifs rendering into the PDF. And there are going to be much more complex situations, not in that specific code, but the whole CLI codebase when we go into much stricter error checking and handling.

This issue is best resolved using something like Babel or Typescript, but adding a build tool at this stage won't be smart move, as we're still in a more-or-less onboarding and education stage for the beginners.

Optional chaining and Nullish Coalescing operator  were added in Node 14.
![image](https://user-images.githubusercontent.com/47742487/98187786-b711ee00-1f37-11eb-86ca-67968b3a6a03.png)

### How

So it is my suggestion that we set the default Node version as v14 during the development stage(a month or 2 probably), so it will give the CLI devs like me, @tolgaerdonmez , @Mira-Alf , @johnjacobkenny , @proful much more breathing room.

And when the development process is done, for backwards compatability (I say back to Node 10 at most), we can add in babel then, as the final dev base at the time would be solidified to a smaller number of people who actively contribute, and they would be better equipped for some good complexity.

Adding Babel would be inevitable cuz everyone wants to work with imports and cutting edge features, so we'd have to add it later in the process.

### Call to Action

This Issue is more for **voting**. What do you think? Let us know in the comments

**Comment by johnjacobkenny** [comment]
LGTM

**Comment by PuruVJ** [comment]
Sorry?

**Comment by tolgaerdonmez** [comment]
Nice research Puru, good idea. 
But how other people will test the twindle-cli easily ? Isn't it hard for some of us to adjust nvm ? I also never used nvm.

**Comment by PuruVJ** [comment]
@tolgaerdonmez  You can just download NodeJS from the site.

But yes, those who need multiple versions will need nvm. All we need is a `.nvmrc` file in the directory, and the command `nvm use` would do it

**Comment by tolgaerdonmez** [comment]
Oh that's a convenient way of switching around.

**Comment by johnjacobkenny** [comment]
And I think I read somewhere that nvm will automatically pick up the rc file and switch any executions to the correct node version. Just need to verify tho.

**Comment by proful** [comment]
Too much hassle imo 😉

**Comment by arthurbuhl** [comment]
I think for the beginners we should keep things simple and straight to the point for now. Lets not try to make the learning curve too steep for this project.
