### ISSUE TITLE
Default PDF Name if -o not provided

### ISSUE THREAD

**Issue by proful** [twindle-co/twindle#615]
![image](https://user-images.githubusercontent.com/354596/98189533-4683c500-1f69-11eb-89d4-a178fdb49c80.png)

PDF file name should be: levelsio-05-Nov-2020-12-41PM.pdf

`node . -i 1324164916287332353 -o david1`

if -o david1 omitted default PDF file name should be generated.

**Comment by johnjacobkenny** [comment]
#602 contains this

**Comment by proful** [comment]
![image](https://user-images.githubusercontent.com/354596/98225092-65ee1280-1fa8-11eb-98ae-690e39481c59.png)

Default PDF file names need to be intelligent.

> **levelsio-05-Nov-2020-12-41PM.pdf**

**Comment by johnjacobkenny** [comment]
Sure, I'll let someone pick it up
