### ISSUE TITLE
PDF Profile information needs work

### ISSUE THREAD

**Issue by proful** [twindle-co/twindle#620]
![image](https://user-images.githubusercontent.com/354596/98198084-493be580-1f7c-11eb-80f6-9de99caa31c7.png)
![image](https://user-images.githubusercontent.com/354596/98198104-5527a780-1f7c-11eb-8e54-4b25ed64abc5.png)

**Comment by johnjacobkenny** [comment]
I think @JoelVinayKumar has added some design for this

**Comment by PuruVJ** [comment]
Fixed 
![image](https://user-images.githubusercontent.com/47742487/98461449-30c50880-21d2-11eb-878a-a0cded62b681.png)
