### ISSUE TITLE
PDF Multiple pages issues

### ISSUE THREAD

**Issue by proful** [twindle-co/twindle#621]
![image](https://user-images.githubusercontent.com/354596/98198185-8011fb80-1f7c-11eb-9c54-4f05503d3e89.png)

**Comment by johnjacobkenny** [comment]
Here's my hunch on this, we would need to create "virtual pages" using divs stacked against each other. Each of these virtual divs would need top and bottom padding (or some kind of footer). The div height would need to match as per the A5 page height.

**Comment by PuruVJ** [comment]
There's a simpler way. We need to put everything in a table. Printing to PDf respects table. I've seen it firsthand on a script I wrote which did exactly what we are doing to generate a PDF

**Comment by PuruVJ** [comment]
Or we could do this div {page-break-inside: avoid}

**Comment by PuruVJ** [comment]
Hey @proful, can you post the link to this long thread so I may test it?
