### ISSUE TITLE
PDF Time stamp should be readable

### ISSUE THREAD

**Issue by proful** [twindle-co/twindle#622]
![image](https://user-images.githubusercontent.com/354596/98198479-2827c480-1f7d-11eb-9d05-b61bf6bdecce.png)

05 Nov 2020 5 PM IST 

Timezone should be based on user who run the program.

Twitter timestamp are UTC needs to be converted to local TZ.

**Comment by PuruVJ** [comment]
Here: https://github.com/twindle-co/twindle/pull/623

**Comment by PuruVJ** [comment]
DOne finally. Without all those files https://github.com/twindle-co/twindle/pull/626

**Comment by johnjacobkenny** [comment]
@PuruVJ next time in the PR description just add "closes #<issue number>"

**Comment by johnjacobkenny** [comment]
Also, I don't see much value in having the timestamp for all tweets? The main timestamp (or date) should give a good indication

**Comment by PuruVJ** [comment]
I think we should replace the timestamp value of format "MMM d, yyyy h:mm aaaa" with just "MMM d, yyyy"

ie `Nov 12, 2001 12:23 pm` -> `Nov 12, 2001`

(BTW, that above is my birthday 😁🤣)
