### ISSUE TITLE
Automation for the Teams Page

### ISSUE THREAD

**Issue by Akshay2996** [twindle-co/twindle#629]
I have created a Static Card using HTML & CSS for the Teams Page.

**Simple view of the Card**

![image](https://user-images.githubusercontent.com/37118877/98215631-0a9f2e80-1f6e-11eb-8f52-26e2651e011c.png)

---

**When hovering over the card**

![image](https://user-images.githubusercontent.com/37118877/98214855-09213680-1f6d-11eb-81e8-f0a977e528f3.png)

### Task to be done
- [x] Automate/Generate the card using JavaScript
- [x] Fetch the data from the **Persons.js** file to fill the card dynamically.

@ni3-kdm @JoelVinayKumar @vasu001  See if you can help me out in this? I am not getting enough time to work on this but will try to do this whenever I get the time.

Also see if any changes are required cause this is the card that will be generated using javascript. CSS Styling can be done at later stages too.

**Comment by UnevenCoder** [comment]
Could you send the html and css .. will try to do it in js , shouldn't be hard hopefully

**Comment by teckiegeek** [comment]
Nil @ javascript, but I really like this new design. Well done to everyone.

**Comment by UnevenCoder** [comment]
true btw color on hover should be darker blue will match the theme of the website nicely , what do you think ?

**Comment by tolgaerdonmez** [comment]
Hi @Akshay2996, from where you want to fetch the team, I can help you with this.

**Comment by Akshay2996** [comment]
> Could you send the html and css .. will try to do it in js , shouldn't be hard hopefully

**It is already uploaded in the twindle-web inside teams folder.**
It is not hard to generate the card in javascript. It's just we have to call the function generateCard which contains the html. I am quite busy with other work but needed some help so that this can be wrapped up quickly.

**Comment by Akshay2996** [comment]
> Hi @Akshay2996, from where you want to fetch the team, from collabs or organization members ?
> I can help you with this.

Hi @tolgaerdonmez there is a persons.js file inside teams folder which contains an Object from there we can fetch the data dynamically.

**Comment by proful** [comment]
@tolgaerdonmez you can fetch dynamic as well and get in touch with @johnjacobkenny he did some progress

**Comment by Akshay2996** [comment]
Hello everyone, I have created the Automated page for the Teams Page card. See the PR #640 or see the code inside the [team_details](https://github.com/twindle-co/twindle/tree/main/twindle-web/team_details) folder to check if it is working correctly & do review & make some changes in it as you feel like it.

**Comment by Akshay2996** [comment]
> I have created a Static Card using HTML & CSS for the Teams Page.
> 
> **Simple view of the Card**
> 
> ![image](https://user-images.githubusercontent.com/37118877/98215631-0a9f2e80-1f6e-11eb-8f52-26e2651e011c.png)
> 
> **When hovering over the card**
> 
> ![image](https://user-images.githubusercontent.com/37118877/98214855-09213680-1f6d-11eb-81e8-f0a977e528f3.png)
> 
> ### Task to be done
> * [x]  Automate/Generate the card using JavaScript
> * [ ]  Fetch the data from the **Persons.js** file to fill the card dynamically.
> 
> @ni3-kdm @JoelVinayKumar @vasu001 See if you can help me out in this? I am not getting enough time to work on this but will try to do this whenever I get the time.
> 
> Also see if any changes are required cause this is the card that will be generated using javascript. CSS Styling can be done at later stages too.

One of the two tasks is done.

**Comment by johnjacobkenny** [comment]
@Akshay2996 take a look at https://javascript.info/template-element

**Comment by tolgaerdonmez** [comment]
@Akshay2996 we could fetch the team members from github api ?
We could then use either contributers or only the ones in the twindle-co organization ?

**Comment by proful** [comment]
@tolgaerdonmez go ahead and raise a PR.

We can update the person file with your script via cron task or github action daily or something like that

**Comment by Akshay2996** [comment]
> @Akshay2996 we could fetch the team members from github api ?
> We could then use either contributers or only the ones in the twindle-co organization ?

Yes @tolgaerdonmez we can do it that way too. I think that will be a great approach.

**Comment by teckiegeek** [comment]
Bravo! @Akshay2996

**Comment by Akshay2996** [comment]
@tolgaerdonmez I am looking into Github Api & have some questions

One Problem:
- Card I created has Url link for linkedin & other Website & a title.
- Using Github Api will restrict us with the github profile page of the user that we can use to fetch data if it is possible.

See this if we can have a workaround for this problem & also right now I'm unable to use Github Api.

- Getting the user details can be done like this -> [Github User twindle-co](https://api.github.com/users/twindle-co)
- Getting the users Repos can be done like this -> [Github User twindle-co Repos](https://api.github.com/users/twindle-co/repos)

**PS: I think this will be hard from the way I see it but We have to thorougly research Github Api so that we can fully utilize it's potential**

**Comment by JoelVinayKumar** [comment]
Guess restricting to github profile is fine. People want to follow other developers, they will find the profile and they can find further info in their profiles

**Comment by tolgaerdonmez** [comment]
> Guess restricting to github profile is fine. People want to follow other developers, they will find the profile and they can find further info in their profiles

I believe so

**Comment by tolgaerdonmez** [comment]
@Akshay2996 what problem did you have while using github api, I could handle the api requests if you want. Let's discuss about it, I'll ping you on discord today, when I'm available.

**Comment by Akshay2996** [comment]
> @Akshay2996 what problem did you have while using github api, I could handle the api requests if you want. Let's discuss about it, I'll ping you on discord today, when I'm available.

Me & @UnevenCoder are working on it Tolga. We have figure something out. Kudos to @UnevenCoder for this.

**Comment by UnevenCoder** [comment]
![image](https://user-images.githubusercontent.com/49345531/98461178-15023800-21bb-11eb-831b-c218041650f1.png)
I got rate limited ... can't say the reason 😆 

 think this many parameters are enough :

full name
location
github link 
company 
blog 
bio
twitter_username
Avatar of course too  

the only thing that's affecting right now is load speed but I have decreased it but will still try to make a more efficient solution

the coding part is still having some errors after I can get it to run will post it here : )

**Comment by johnjacobkenny** [comment]
Check out this https://blog.covid19india.org/2020/09/04/architecture/

**Comment by Akshay2996** [comment]
> I have created a Static Card using HTML & CSS for the Teams Page.
> 
> **Simple view of the Card**
> 
> ![image](https://user-images.githubusercontent.com/37118877/98215631-0a9f2e80-1f6e-11eb-8f52-26e2651e011c.png)
> 
> **When hovering over the card**
> 
> ![image](https://user-images.githubusercontent.com/37118877/98214855-09213680-1f6d-11eb-81e8-f0a977e528f3.png)
> 
> ### Task to be done
> * [x]  Automate/Generate the card using JavaScript
> * [x]  Fetch the data from the **Persons.js** file to fill the card dynamically.
> 
> @ni3-kdm @JoelVinayKumar @vasu001 See if you can help me out in this? I am not getting enough time to work on this but will try to do this whenever I get the time.
> 
> Also see if any changes are required cause this is the card that will be generated using javascript. CSS Styling can be done at later stages too.

**Second Task** is achieved by @UnevenCoder Now the code refinement is needed & see if it is working properly for all the cases.

Kudos👏 to Ameen

!{image](https://cdn.discordapp.com/attachments/774583774184865812/775057427753205800/unknown.png)

**Comment by tolgaerdonmez** [comment]
Happy to see this😊

**Comment by johnjacobkenny** [comment]
Good job everyone!

**Comment by UnevenCoder** [comment]
Codes more human friendly now 
https://github.com/twindle-co/twindle/pull/750

Would be great if someone could review it .
