### ISSUE TITLE
Removing Emojis, Unicode characters when creating for kindle

### ISSUE THREAD

**Issue by tolgaerdonmez** [twindle-co/twindle#631]
These characters should be deleted, kindle shows them as missing characters, which disrupts the experience.

**Comment by PuruVJ** [comment]
I've fixed the Emojis(Just like Twitter SVGs they are now). Don't know about Unicode characters.
![IMG-1193](https://user-images.githubusercontent.com/47742487/98226209-ba2ecd80-1f7b-11eb-86ea-f28a823966db.JPG)

**Comment by tolgaerdonmez** [comment]
Oh okay this is solved that :), nice job!
