### ISSUE TITLE
CLI Should Log sending to Kindle successful

### ISSUE THREAD

**Issue by proful** [twindle-co/twindle#636]
![image](https://user-images.githubusercontent.com/354596/98239836-b0798a00-1fbc-11eb-835d-75370d645c7b.png)

**Comment by Mira-Alf** [comment]
Does this look good?
`Your file ${filename} has been sent to Kindle email address ${kindleEmail}`

**Comment by proful** [comment]
Perfect

**Comment by johnjacobkenny** [comment]
Closed by #638
