### ISSUE TITLE
CLI Should log propper error message if env file is not configured correctly

### ISSUE THREAD

**Issue by proful** [twindle-co/twindle#637]
![image](https://user-images.githubusercontent.com/354596/98239948-d99a1a80-1fbc-11eb-9992-9b0470782f86.png)

**Comment by Mira-Alf** [comment]
This is a fetch error? When did this happen exactly? I am still not satisfied with the error mechanism.. Just not sure how to fix the code. I am from a Java background and exception handling is seamless there.. But here I dont have sufficient information. Will try to research to see if there are good ways to handle these kinds of errors.

**Comment by Mira-Alf** [comment]
So I dug in to the code and found that :
`try {
    // this next line is wrong
    let tweets = require("./twitter/twitter_responses/response-version2-tweetthread.json");
    if (!mock) tweets = await getTweetsFromTweetId(tweetId);

    const outputFilePath = getOutputFilePath(outputFilename);
    await Renderer.render(tweets, format, outputFilePath);

    if (kindleEmail) {
      await sendToKindle(kindleEmail, outputFilePath);
    }
  } catch (e) {
    console.error(e);
  }`
console.error(e) is probably printing this? So what do you think is the best way to fix this?

**Comment by johnjacobkenny** [comment]
You could take a look at https://javascript.info/try-catch#error-object to understand more about the error object and how to handle the specific case.

**Comment by PuruVJ** [comment]
We have added a lot of validation and better error handling. Should we close it?

**Comment by proful** [comment]
I will verify and close
