### ISSUE TITLE
CLI puppetter when is rest coming?😊

### ISSUE THREAD

**Issue by proful** [twindle-co/twindle#644]
![image](https://user-images.githubusercontent.com/354596/98313998-36cbb580-2029-11eb-9dad-44b66af424f9.png)

8 tweets I can see!

**Comment by PuruVJ** [comment]
I'll help with that. We just need to make the viewport accomodate much more things like I showed yesterday.

**Comment by PuruVJ** [comment]
I've made the viewport much bigger, so we can get all the tweets now. Off Course, still need to check for the "Show Thread" button and click it, though that's upto @vijaya-bhaskar.

Close this Issue if you're satisfied with your initial request😊

**Comment by PuruVJ** [comment]
The rest has come 😁!

#692 #693
