### ISSUE TITLE
CLI fetch kindle email from .env file

### ISSUE THREAD

**Issue by proful** [twindle-co/twindle#651]
![image](https://user-images.githubusercontent.com/354596/98328947-1ca2cf00-204b-11eb-9ba6-f41b6a5a3cf1.png)

- store kindle email in .env file
- send to kindle if `-s` option passed. No need to pass email explicitely

**Comment by tolgaerdonmez** [comment]
I actually did that myself while testing but forgot to create a good version for pr 😁, gonna send a pr now.

**Comment by PuruVJ** [comment]
I'll create a PR. If empty -s is passed, it will automatically default to the .env file

**Comment by tolgaerdonmez** [comment]
I did this, forgot to send the pr

**Comment by tolgaerdonmez** [comment]
must be closed
