### ISSUE TITLE
CLI Error in fetching url

### ISSUE THREAD

**Issue by proful** [twindle-co/twindle#656]
![image](https://user-images.githubusercontent.com/354596/98347618-bd08eb80-206b-11eb-9636-0e88f17792db.png)

![image](https://user-images.githubusercontent.com/354596/98347829-0fe2a300-206c-11eb-957d-6ba73dd65615.png)

https://twitter.com/vijaya_bhaskar_/status/1324626012265734144

@PuruVJ @vijaya-bhaskar

**Comment by proful** [comment]
![image](https://user-images.githubusercontent.com/354596/98348789-4ec52880-206d-11eb-886b-8fc0aed2e32b.png)
https://twitter.com/johnjacobkenny/status/1324561342292897792

**Comment by pranavgoel29** [comment]
I am getting same message, and I think @PuruVJ is working on it.

**Comment by pranavgoel29** [comment]
> I am getting same message, and I think @PuruVJ is working on it.

I have tried it once again and I am still getting this error.

![image](https://user-images.githubusercontent.com/48860494/98361627-e3ba2880-2051-11eb-978d-83de3d3eef78.png)

**Comment by PuruVJ** [comment]
I'm not getting any errors other than the API not registering recent tweets at. Closing this.
