### ISSUE TITLE
Twitter API not fetching recent tweets

### ISSUE THREAD

**Issue by PuruVJ** [twindle-co/twindle#657]
I'm encountering a very weird issue. Whenever I try to run a very recent tweet(like less than an hour or so), it simple won't search it and return `search_results: 0`.

This seems to be quite variable. 

Try this command for instance

```bash
node . -i 1324638941983567872 -o puru
```
Do it ASAP to see the behavior, then try one a few hours old.

I need your help @Mira-Alf @tolgaerdonmez

**Comment by tolgaerdonmez** [comment]
sorry, I'm not at home right now :/

**Comment by pranavgoel29** [comment]
## Getting this error message.

![image](https://user-images.githubusercontent.com/48860494/98353362-380adb80-2045-11eb-9555-afd8d359d700.png)

**Comment by PuruVJ** [comment]
> ## Getting this error message.
> ![image](https://user-images.githubusercontent.com/48860494/98353362-380adb80-2045-11eb-9555-afd8d359d700.png)

Already fixed on my end. This isn't the problem

**Comment by pranavgoel29** [comment]
> > ## Getting this error message.
> > ![image](https://user-images.githubusercontent.com/48860494/98353362-380adb80-2045-11eb-9555-afd8d359d700.png)
> 
> Already fixed on my end. This isn't the problem

ok 😄

**Comment by PuruVJ** [comment]
False alarm. Fetching recent tweets was never the problem, the error was coming out when I was trying to map an empty **search** response, which was inevitable for single tweets. It has been fixed now.
