### ISSUE TITLE
Handlebars element rendering messing up

### ISSUE THREAD

**Issue by PuruVJ** [twindle-co/twindle#662]
Here's some code in the `Thread.hbs`:

```html
          {{#if linkWithImage}}
            <a href="{{linkWithImage.expanded_url}}" class="link-box-anchor">
              <div class="link-box">
                <div class="link-img-container">
                  <img src="{{linkWithImage.images.1.url}}" />
                </div>
                <div class="link-box-content">
                  <div class="link-box-content-heading">
                    Link content here
                  </div>
                </div>
              </div>
            </a>
          {{/if}}
```

You can see than `a` is the parent of `div.link-box` here in this code. Well when it is rendered as html content, this is happening:
![image](https://user-images.githubusercontent.com/47742487/98380931-3bb35800-206f-11eb-8fe1-c7dce4ef9dee.png)

See? The order of elements is reversed.

I don't know what is happening. But we need this resolved to have effective rendering of links.

**Comment by PuruVJ** [comment]
Fixed, with some hacks.

Wrapping `a` in `<div>` worked

**Comment by Mira-Alf** [comment]
Awesome @PuruVJ. When I read this issue, I was wondering how we can nest div block tags inside an a tag which is inline.. But then read some more and understood that in HTML 5 this is permitted. So good, that you have fixed this.. Do you think inline vs block elements was causing this issue?
