### ISSUE TITLE
CLI Error message needs cleanup

### ISSUE THREAD

**Issue by proful** [twindle-co/twindle#666]
![image](https://user-images.githubusercontent.com/354596/98430098-5208f480-20ff-11eb-8817-7e3d6ce7052b.png)

Only below message should be displayed. Can it appear in RED color with some emoji?
> tweet-older-than-7-days: The tweet must not be older than 7 days.

**Comment by PuruVJ** [comment]
I disagree. As this, as a CLI is programmer centric application, we'd need to know where the error is originating from.

**Comment by PuruVJ** [comment]
Though we can make it red

**Comment by proful** [comment]
in DEV=true mode print any trace.

Developers also human being 😊
