### ISSUE TITLE
CLI Puppeter output broken

### ISSUE THREAD

**Issue by proful** [twindle-co/twindle#667]
`
node . -i 1002103360646823936 -p
`
![image](https://user-images.githubusercontent.com/354596/98430156-bc219980-20ff-11eb-9ce0-fa23ddb25a6e.png)

- it is opening chrome browser. it should not!
- avoid printing log message
- throwing error

@PuruVJ

**Comment by PuruVJ** [comment]
cc @vijaya-bhaskar

**Comment by johnjacobkenny** [comment]
@PuruVJ I think this could be because of the change you made to create custom filename?

**Comment by PuruVJ** [comment]
That's not me, I think

**Comment by PuruVJ** [comment]
I'll have to look into how his code works and uses the renderer. Probably his structure needs to sync with the recent modifications I made.

**Comment by Mira-Alf** [comment]
Is there some good links to understand how puppeteer works to fix this behavior. I can always google but I wont know if it is a good/correct solution. I have submitted some preliminary code to parse out tweet content for an array of tweets. If this part gets fixed, I can test out that module and fix some error handling in that part of the code.

**Comment by PuruVJ** [comment]
Fixed now! #692 #693
