### ISSUE TITLE
CLI PDF Image rendering - Image cut

### ISSUE THREAD

**Issue by proful** [twindle-co/twindle#668]
`node . -i 1324461127040929793`

Images are rendering properly.

Instead of cutting is it possible to display a larger image on one separate page instead of splitting.

[david_perell-Nov-6-2020.pdf](https://github.com/twindle-co/twindle/files/5504209/david_perell-Nov-6-2020.pdf)

**Comment by PuruVJ** [comment]
If it was a svelte template(Or something that offers reactivity), I would have been able to do some weird hacks, but here, you would have to write plain JS with selectors and callback, without dependencies, which I'm not comfortable about.

My opinion: I don't think image cutting is worse than just showing lot of blank space, cuz that is what would be the output.

**Comment by PuruVJ** [comment]
This is put off for now, being too complex.

But anyone who wishes to help is welcome. Just do your thing, Open a PR, and we'll test this feature extensively.

**Comment by PuruVJ** [comment]
Mira partially solved it. We need to do something about huge content, but can be discussed in an another issue
