### ISSUE TITLE
Suggestions for Twitter module refactor

### ISSUE THREAD

**Issue by johnjacobkenny** [twindle-co/twindle#669]
Apart from the cleanup that @Mira-Alf is doing in the twitter module, just wanted to share some thoughts about twitter module refactoring. I have not understood all of the existing code, but would need help from @Mira-Alf and @PuruVJ to get this into a correct shape. Here is a suggested structure. Please share thoughts based on your understanding of the code, whether it will fit into this kind of abstraction.

![image](https://user-images.githubusercontent.com/19240564/98440373-57c20280-211e-11eb-9224-29c256a418cc.png)

- `api` (or `service`?) - would handle all the API related content - including the fetch call, the API endpoint, the parameters for the API - and may export only two methods? - one to fetch a specific tweet, and the other to fetch the conversation.
- `scraping` - would hold the puppeteer code, and this folder may have sub folders with utils, etc specific for it.
- `transformations` - would hold any of the methods used to convert the twitter response into a different format (maybe for handlebars consumption)
- `utils`
- `vaildations` - I think there are a few functions used to check the response and generate errors, they could go here.

In the end, this module may expose a couple functions which may be `getTweetThreadFromAPI(threadId)` and `getTweetThreadFromPuppeteer(threadId)` which will return a common format which may be consumed by the handlebars template. Or if we could export a single function which will pick twitter API or puppeteer intelligently, that would be the best.

All of this is from my limited understanding, please discuss below so that we can refine it.

### Update
We had a meeting to discuss about this. Outcome is to move forward with the proposed folder structure. @johnjacobkenny  will take up the refactor in a parallel branch so that the main branch stays stable.
https://www.youtube.com/watch?v=x0v_6QOWAzI

**Comment by proful** [comment]
@johnjacobkenny I 💯 agree with your limited understanding.

PR 😇

**Comment by johnjacobkenny** [comment]
> @johnjacobkenny I  agree with your limited understanding.
> 
> PR

Haha :rofl:

**Comment by johnjacobkenny** [comment]
Me and @Mira-Alf are planning a 5PM IST call today through Zoom. If anyone is interested, may ping either of us for the link.

**Comment by proful** [comment]
Please record and publish the link before hand to discord and Twitter group

**Comment by johnjacobkenny** [comment]
Okay

**Comment by piratelicorne** [comment]
Ohh I just read this 😅

**Comment by johnjacobkenny** [comment]
I have pushed some changes to https://github.com/twindle-co/twindle/tree/twitter-module-refactor

@Mira-Alf @PuruVJ can start taking a look at the code. I am not yet pleased with the entire codebase, but just want to know if it works and all the scenarios are correctly captured.

**Comment by PuruVJ** [comment]
Nice work @johnjacobkenny

**Comment by johnjacobkenny** [comment]
So this is working on my local machine, I clean wiped my twindle repo and setup everything from scratch, and it works perfectly! And this has been merged into main branch.

Everyone great work!!

**Comment by proful** [comment]
Great efforts everyone 👍
