### ISSUE TITLE
Puppeeter bug

### ISSUE THREAD

**Issue by proful** [twindle-co/twindle#674]
![image](https://user-images.githubusercontent.com/354596/98433632-d74ed200-211c-11eb-8201-11275a37f87d.png)
@vijaya-bhaskar 

naval tweets
`node . -i 1002103360646823936 -p`

**Comment by johnjacobkenny** [comment]
This is the issue that all tweets are being fetched, rather than just the original thread, right?

**Comment by johnjacobkenny** [comment]
Since I am looking into the twitter module refactor, I can't help out with this right now. Anyone else? @twindle-co/developer

**Comment by Mira-Alf** [comment]
I will take a look at this.

**Comment by PuruVJ** [comment]
Been fixed now
