### ISSUE TITLE
CLI send to kindle if -s option provided

### ISSUE THREAD

**Issue by proful** [twindle-co/twindle#675]
![image](https://user-images.githubusercontent.com/354596/98433763-35c88000-211e-11eb-9704-378efdfca3ad.png)

In this case mail shouldn't be sent.

**Comment by PuruVJ** [comment]
I say we make -s a boolean, and take the value only from .env. Much more straightforward.

Or we can simply check if -s is empty, and accordingly not do anything

**Comment by proful** [comment]
donot send to kindle
`node . -i 1002103360646823936 -p`

send to kindle
`node . -i 1002103360646823936 -p -s`

**Comment by PuruVJ** [comment]
So we keep it boolean only, rather than optional string?

**Comment by tolgaerdonmez** [comment]
I think it would be nice like this

s flag is a boolean, if true and email in env exists, send to kindle

also a --kindle-email, flag to enter the email from cli, if this exists always send

if this is okay, I'm gonna try implementing it.

**Comment by proful** [comment]
Sounds good @tolgaerdonmez

**Comment by tolgaerdonmez** [comment]
PR #685
