### ISSUE TITLE
Create resuable JSDoc types

### ISSUE THREAD

**Issue by PuruVJ** [twindle-co/twindle#676]
I've found a way to have make typescript style types in JS using comments only. It will allow us to define the more complex types(Response, tweet object, etc) all in a single file, and the usage would be as simple as

```js

/**
 * @param {TwitterResponse} response
 */
```

Will start work on it ASAP.

Will need reviews by those who have worked with the Twitter API extensively e.g @Mira-Alf

**Comment by PuruVJ** [comment]
Check this out! `process.env` types are here for now
![image](https://user-images.githubusercontent.com/47742487/98507421-90c7b780-2283-11eb-8e17-70819110cbfd.png)

**Comment by proful** [comment]
This looks really cool

**Comment by PuruVJ** [comment]
Thanks.

Wait and watch. You are getting strongly typed code soon.
