### ISSUE TITLE
Fixing PDF page break

### ISSUE THREAD

**Issue by tolgaerdonmez** [twindle-co/twindle#686]
I'm working on some things for this.

**Comment by vasudeveloper001** [comment]
I am trying to change the design of pdf rendering, anyway to see the changes being made to .hbs file design while I am making it?

**Comment by PuruVJ** [comment]
@vasudeveloper001 I spent lot of time working with the hbs file, and the closest I could come was generating a html file in the temporary folder, editing styles in the devtools and the applying them.

Otherwise, it'a all re-running the bloody thing over and over.

**Comment by vasudeveloper001** [comment]
That's what I am trying to do. Generate a temporary HTML file. How to do that?

**Comment by PuruVJ** [comment]
It's already generating on every single build. If you're on Windows, OPen Windows explorar, enter %temp% in the address bar, the temp folder will open. Scroll down, and you'll see a hello.html there.

**Comment by vasudeveloper001** [comment]
Thanks. Got it.

**Comment by johnjacobkenny** [comment]
> It's already generating on every single build. If you're on Windows, OPen Windows explorar, enter %temp% in the address bar, the temp folder will open. Scroll down, and you'll see a hello.html there.

What about other OSes @PuruVJ

**Comment by PuruVJ** [comment]
You'll have to Google "[INSERT YOUR OS NAME HERE] temperory folder"

**Comment by johnjacobkenny** [comment]
I meant, is it implemented for other OSes too. I checked in `/tmp` on my linux machine and it is there. Perhaps add a flag to avoid creating that file for normal execution without dev mode?

**Comment by PuruVJ** [comment]
Yes it is implemented for all OSs (uses tmpdir() from os module)

> Perhaps add a flag to avoid creating that file for normal execution without dev mode?
Hmm I think that would be better, and we should generate it in that folder itself, gitignored

**Comment by proful** [comment]
@tolgaerdonmez any updates?

**Comment by vasudeveloper001** [comment]
@tolgaerdonmez Are you still working on it? Or is it nearly finished?

**Comment by tolgaerdonmez** [comment]
> @tolgaerdonmez any updates?

I couldn't find any time to look any further to this, while dealing with other things, but I have a question on my mind?

Why do we simply make the pdf one page? It doesnt need to be paged I think.

**Comment by PuruVJ** [comment]
> > @tolgaerdonmez any updates?
> 
> I couldn't find any time to look any further to this, while dealing with other things, but I have a question on my mind?
> 
> Why do we simply make the pdf one page? It doesnt need to be paged I think.

PDfs are already paged by default. I don't think we have much say in the matter.

**Comment by johnjacobkenny** [comment]
@tolgaerdonmez are you suggesting that we might provide custom dimensions for the pdf? Can we make it a single long page? 😲

**Comment by tolgaerdonmez** [comment]
Why couldn't we ?

**Comment by PuruVJ** [comment]
I think I found something https://stackoverflow.com/questions/59891836/print-one-long-page-pdf-using-puppeteer

Off course, I still think printing one single page would be suboptimal, as kindle will try to show that 1 page all at once, and will zoom out everything to the point of unreadability

**Comment by proful** [comment]
Please no to single page.

**Comment by PuruVJ** [comment]
Or we'd need to do some preprocessing while emulating the page in print mode, manually set dimensions on images and such to make them fit in one page, copy that markup, replace the page's own markup with the new one, then print it.

I'm thinking this issue is better left to the last 😶

**Comment by vasudeveloper001** [comment]
Let's say we have 100 tweets thread. How many pages are we talking about here in that case? 100?

**Comment by PuruVJ** [comment]
Depends on how long each tweet is. This includes images, embedded tweets, line breaks, etc

**Comment by PuruVJ** [comment]
Closing. Read https://github.com/twindle-co/twindle/issues/668#issuecomment-735322204
