### ISSUE TITLE
Remove try-catch from everywhere other than index.js

### ISSUE THREAD

**Issue by PuruVJ** [twindle-co/twindle#688]
Since there is a try catch error handling in very index.js itself, we don't need try catch in any other functions that run directly and indirectly inside the index.js (Which is all the functions, basically), as all errors and exceptions will be caught by the root try catch itself.

This will clean up the complete code significantly and make everything much more clearer and seemingly modular.

**Comment by Mira-Alf** [comment]
I think I have try catch blocks in a couple of places where fetch is called. I can clean that up.
