### ISSUE TITLE
Twitter module code freeze

### ISSUE THREAD

**Issue by johnjacobkenny** [twindle-co/twindle#698]
Let's focus on porting all extra additions since yesterday evening into the new branch for refactoring.

No more pr for Twitter module into main branch.

@proful @Mira-Alf @PuruVJ @tolgaerdonmez

**Comment by tolgaerdonmez** [comment]
okay

**Comment by PuruVJ** [comment]
Seems good. have you done it or should I make a pr syncing the right stuff?

**Comment by johnjacobkenny** [comment]
I think everything is in place. @Mira is working on her changes

**Comment by johnjacobkenny** [comment]
@Mira-Alf has added her changes and also added most of the changes @PuruVJ had added. I think all that's left is for @PuruVJ to add in the puppeteer latest changes into the twitter module, and delete the `twitter-puppeteer` module. Once that is done and we get a :+1: from @PuruVJ we can merge this in.

@PuruVJ you can also create a PR for the merging in part if you have time
