### ISSUE TITLE
CLI new feature multiple thread in same page

### ISSUE THREAD

**Issue by proful** [twindle-co/twindle#706]
- same author/different author 
- multiple threads
- single pdf

https://twitter.com/steveruizok/status/1284240038394462208
https://twitter.com/steveruizok/status/1286043966253785093

`node . -p -i 1284240038394462208,1286043966253785093 -s`

**Comment by johnjacobkenny** [comment]
We could start publishing books by authors :partying_face:

**Comment by PuruVJ** [comment]
This shit is getting real now!

**Comment by Mira-Alf** [comment]
I was thinking about this implementation.
* Should I throw an error if the two tweet threads are not by the same author?
* How should the PDF format change for this.. Based on that my tweets object structure might change?
* Also I was planning on doing some validation checks and calling the getTweetsById function on each of the tweet ids. But @proful mentioned that we will have to make the code efficient? What better approach can we use? Any ideas?

**Comment by proful** [comment]
I want to have ability to combine multiple threads from multiple authors as well.

**Comment by PuruVJ** [comment]
> I want to have ability to combine multiple threads from multiple authors as well.

Are we making a Twitter book publishing service? 🤣🤣

**Comment by johnjacobkenny** [comment]
> > I want to have ability to combine multiple threads from multiple authors as well.
> 
> Are we making a Twitter book publishing service? 🤣🤣


@proful Puru in his limited understanding might have laughed at your idea, but we might be able to charge premium to users who would like to generate books from their tweets. I can assume there are a few people who would want to get that feature. Many people write a lot on twitter. If they could have their entire history worth of tweets made into a book in one click, isn't that worth paying for ❤️

**Comment by proful** [comment]
We will get tons of paying customers sooner than later 😊

**Comment by PuruVJ** [comment]
> > > I want to have ability to combine multiple threads from multiple authors as well.
> > 
> > 
> > Are we making a Twitter book publishing service? 🤣🤣
> 
> @proful Puru in his limited understanding might have laughed at your idea, but we might be able to charge premium to users who would like to generate books from their tweets. I can assume there are a few people who would want to get that feature. Many people write a lot on twitter. If they could have their entire history worth of tweets made into a book in one click, isn't that worth paying for ❤️

Humor aside, I find this idea really good, @proful and Kenny.

**Comment by frankiefab100** [comment]
Wow! these ideas and suggestions are wonderful
