### ISSUE TITLE
Jest test cases 

### ISSUE THREAD

**Issue by proful** [twindle-co/twindle#709]

**Comment by PuruVJ** [comment]
@johnjacobkenny has already set some up, we'll get through to the end with this

**Comment by proful** [comment]
@PuruVJ we need 80-90% test coverage. As this is extremely important, I count on you to take responsibility.

**Comment by PuruVJ** [comment]
I'll try. But first, I'll have to learn testing 😂

**Comment by johnjacobkenny** [comment]
It should be too easy for you @PuruVJ :partying_face:

**Comment by PuruVJ** [comment]
@johnjacobkenny Thanks for the confidence Kenny. Though I've never done any testing before, Imma do it right for this

**Comment by proful** [comment]
@PuruVJ any updates?

**Comment by PuruVJ** [comment]
Already working on a feature/test branch

**Comment by PuruVJ** [comment]
I'm seriously gonna need help on this. I've never done testing before. I have learned the concepts, but have no idea how to **start** on twindle. I have set up some basic tests, but dunno how to cover every case.

**Comment by johnjacobkenny** [comment]
Cover what you can, others will pitch in

**Comment by proful** [comment]
keep adding few test cases at a time. 

don't close this ticket. we will close this ticket once we have good % of testing

**Comment by PuruVJ** [comment]
This issue is too broad. Should be closed and replaced with smaller and more specific issues, like Github testing, Twitter testing, HN testing, and with a solid, tangible goal in mind(Optional in beginning, and should be added). Progress should be documented there, by referencing the PRs doing this work.
