### ISSUE TITLE
Twitter refactor part: Is this granularity necessary

### ISSUE THREAD

**Issue by PuruVJ** [twindle-co/twindle#710]
I saw a file structure like this in the Twitter refactor:

![image](https://user-images.githubusercontent.com/47742487/98494628-74b41e00-2263-11eb-8f6d-73de15c54c8c.png)

And the contents look like this.
![image](https://user-images.githubusercontent.com/47742487/98494645-7f6eb300-2263-11eb-8b48-86b20977dfcf.png)

My question: Is it really necessary to split them up so much? 
For example, It'll be better to import format directly from date-fns, and it'll convey meaning that it is related to Date formatting only, cuz there might be more formatters later on.

And `const {format} = require('../utils/date')` would be a bit too confusing at first.

And if we're doing this, we better do it right. Let's change the file a bit:
```js
const { format } = require("date-fns");

const formatTimestamp = (timestamp) => format(new Date(timestamp), 'MMM d, yyyy')

module.exports = {
  formatTimestamp,
};

```

What are your thoughts @johnjacobkenny @Mira-Alf  ?

**Comment by johnjacobkenny** [comment]
Yep fully agree. Go for it :+1:

**Comment by Mira-Alf** [comment]
I didn't see this level of modularity. This makes sense.

**Comment by PuruVJ** [comment]
@Mira-Alf No issue. I've replaced existing one with the much better snippet I provided above

**Comment by johnjacobkenny** [comment]
The idea overall was to have a facade around the external library, so that in case we need to switch it out later, we can easily by making changes in a single file.

**Comment by PuruVJ** [comment]
Yes! I agree. I've added cleanup logic, and some more stuff in that single file. kenny's idea was really good.
