### ISSUE TITLE
prettier not working

### ISSUE THREAD

**Issue by proful** [twindle-co/twindle#712]
![prettier 2](https://user-images.githubusercontent.com/354596/98498855-0b9ccc80-229c-11eb-9919-4ab2577a63e3.gif)

as per config "singleQuote": false
Only double quotes should be allowed. Single quotes should be converted to double quotes.

@johnjacobkenny @PuruVJ

**Comment by PuruVJ** [comment]
It's working perfectly for my editor when I press the format shortcut keys.
I've introduced some changes in the twitter branch. When they get merged, it might get fixed for you.

**Comment by proful** [comment]
I had to click Format Document and then select Prettier then it is working

![image](https://user-images.githubusercontent.com/354596/98527502-3a806600-22cf-11eb-9944-edb0fb0851f3.png)

**Comment by PuruVJ** [comment]
Shortcut keys weren't working for you?
