### ISSUE TITLE
Spike: CLI - Integration with user's home folder and guided walkthrough

### ISSUE THREAD

**Issue by johnjacobkenny** [twindle-co/twindle#714]
I am just thinking of the next aspect of the cli. Once a brand new user npm installs twindle, we should be able to do all the initialization for twindle to the user's home folder (on all OSes) and whatever configuration needs to be stored centrally there in some kind of env file.

Also there would need to be some guided steps. The user should be guided through
- how to get the bearer token from twitter developers
- how to setup the kindle to receive email (and associated configuration)
- how to setup email credentials

Once the user has performed these steps, then we would have all the config ready for usage.
Ideally we may expose just the `-i tweetId` flag for easiest UX.

This would require some more thoughts to refine it, before we proceed with implementation.

**Comment by PuruVJ** [comment]
last interaction was 28 days ago.

Inactive issue. Prominent enough that it will resurface again.
