### ISSUE TITLE
Meaningful failure messages

### ISSUE THREAD

**Issue by PuruVJ** [twindle-co/twindle#717]
twitter/api/helpers/fetch.js has this code

```js
  // REVIEW WANTED: What should we do when its not 200? This below is just a workaround for now
  if (response.status !== 200) throw new ApiErrors.NetworkRequestError();
```
If the request fails, it throws the error that there's an error in the network, CHeck your network, etc. But it would give same error if the ID is invalid

![image](https://user-images.githubusercontent.com/47742487/98519941-713a8a00-2297-11eb-8292-13e8394c59c9.png)

How do we tackle this @Mira-Alf @johnjacobkenny?

**Comment by sarathkumar6** [comment]
@PuruVJ What are the other error codes? Based on that we can come up with user friendly error messages.

500 - Sorry, our server is having issues. Please come back later
400 - Bad Request, possibly some useful information on what's wrong with the request.
401 - You're not authorized to access the app

@Mira-Alf @johnjacobkenny @proful

**Comment by johnjacobkenny** [comment]
Yeah, I think that this list looks good to start off with. In addition, we should handle any that the twitter API tells us to.

**Comment by proful** [comment]
Looks good

However these are RESTful error codes. Relevant to CLI?

I don't remember any CLI throw or display these kind of errors.

As long as we use internally I am fine but we need to translate human readable error message to the CLI user.

**Comment by PuruVJ** [comment]
I'm thinking of errors like Invalid Bearer token, or unknown tweet, or something like that. The REST error codes can be answered with the NetworkError itself

**Comment by johnjacobkenny** [comment]
Mira is looking into it and will share her findings

**Comment by palashmon** [comment]
Maybe we can also start exploring other options also like: [winston](https://github.com/winstonjs/winston) or [morgan](https://github.com/expressjs/morgan)

**Comment by Mira-Alf** [comment]
## 200 response by Twitter
* Twitter sends a 200 response code in most cases when a request is successfully processed. But it also returns a 200 success response with an error message in some cases like when tweet id is for a deleted tweet
`{
"errors": [
  {
"detail": "Could not find tweet with ids: [1320717377537929217].",
"title": "Not Found Error",
"resource_type": "tweet",
"parameter": "ids",
"value": "1320717377537929217",
"type": "https://api.twitter.com/2/problems/resource-not-found"
}
],
}`

## Non 200 response code by Twitter: Comprehensive list
* 400-Bad Request: when there is a bad request like for example tweet id is passed as "haha"
* 401-Unauthorized: when there is a missing or an incorrect or invalid access token( when older tokens are invalidated)
* 403-Forbidden: when the token is valid but it is not authorized to access the endpoint, some kind of privileged access
* 404-Not Found: when the endpoint is not found
* 429|500|503-Too many requests|Internal Server Error|Service Unavailable: when all is okay but the token's limits are exceeded or Twitter is overloaded


The question now is should we classify all non 200 error codes returned by Twitter under a single error? Does it make sense to have too much detail? Like for example in the original message by proful he had used "haha" as tweet id and that will throw a 400 error code. What information must be displayed to the user? Throwing a network issue does not make much sense in this case.

Inputs appreciated.

**Comment by Mira-Alf** [comment]
> 
> 
> Maybe we can also start exploring other options also like: [winston](https://github.com/winstonjs/winston) or [morgan](https://github.com/expressjs/morgan)

Nice, so these winston and morgan are logger options? Good. If someone can pick this up and set it up, then I can implement it in all the error scenarios..

**Comment by PuruVJ** [comment]
@Mira-Alf Thanks. I've implemented most of these by testing the API with different paramters. Expect a PR soon.

**Comment by Mira-Alf** [comment]
Great @PuruVJ Thanks!

**Comment by PuruVJ** [comment]
Is this issue resolved fully? Can it be closed?
