### ISSUE TITLE
CLI Rendering link issue - preview image not displaying

### ISSUE THREAD

**Issue by proful** [twindle-co/twindle#723]
![image](https://user-images.githubusercontent.com/354596/98526928-7e26a000-22ce-11eb-8eab-21e4904c8900.png)

![image](https://user-images.githubusercontent.com/354596/98526962-87177180-22ce-11eb-865e-b209aee75ef2.png)

`node . -p -i 1312742534221832192`
[Example Thread](https://twitter.com/steveruizok/status/1312742534221832192)

**Comment by PuruVJ** [comment]
Can you send the link of that thread?

**Comment by PuruVJ** [comment]
This problem hasn't been solved yet. @twindle-co/developer please take a look at this.

Answer lies in rich-rendering.js, in the function `renderOutsiderLinks`. Someone fix it up to not show the box if no link is returned from twitter data

**Comment by shekhar10feb** [comment]
I am working on it.

**Comment by PuruVJ** [comment]
How's the progress going Shekhar?

**Comment by proful** [comment]
@all-contributors please add @shekhar10feb for twindle

**Comment by proful** [comment]
@all-contributors please add @shekhar10feb for code
