### ISSUE TITLE
CLI test folder needs to go up

### ISSUE THREAD

**Issue by proful** [twindle-co/twindle#724]
test folder needs to go one level up.

Now: twindle-cli\twitter\test
Should be: twindle-cli\test

**Comment by johnjacobkenny** [comment]
I'm open to debate whether we need a test folder or we should keep the tests side by side with each file

**Comment by sarathkumar6** [comment]
My two cents: the source code and test specs scaffolded separately address separation of concerns.
Yes, it the project is small and it might sound like why separate it but keeping the enhancements in the mind I feel better to have them in separate folders.

**Comment by johnjacobkenny** [comment]
@sarathkumar6 so we would have one root level `tests` folder which would have multiple files testing each module? Do you think we should have a flat file structure in this `tests` folder?

**Comment by PuruVJ** [comment]
Yeah. We can make a twitter folder inside the tests folder, making everything more centralized. Good idea

**Comment by sarathkumar6** [comment]
@johnjacobkenny The scaffolding I visualize is as below 

src code: `twindle-cli\src\`
     - twitter
     - helper
     - renderer
     - utils
test specs: `twindle-cli\tests\`
      - twitter
     - helper
     - renderer
     - utils

**Comment by PuruVJ** [comment]
> @johnjacobkenny The scaffolding I visualize is flat file structure, as below. So, we can ignore the tests from deploying to prod version and keep the package light weight. Having tests bound to individual module with source code makes it coupled structure. If that makes sense?
> 
> 
> 
> src code: `twindle-cli\src\`
> 
>      - twindle-cli\src\twitter
> 
>      - twindle-cli\src\helper
> 
>      - twindle-cli\src\renderer
> 
>      - twindle-cli\src\utils
> 
> 
> 
> test specs: `twindle-cli\tests\`
> 
>      - twindle-cli\src\twitter
> 
>      - twindle-cli\src\helper
> 
>      - twindle-cli\src\renderer
> 
>      - twindle-cli\src\utils
> 
> 
> 
> This way we can ignore the entire test module when deploying code to prod version.

This is perfect

**Comment by johnjacobkenny** [comment]
> @johnjacobkenny The scaffolding I visualize is flat file structure, as below. So, we can ignore the tests from deploying to prod version and keep the package light weight. Having tests bound to individual module with source code makes it coupled structure. If that makes sense?
> 
> src code: `twindle-cli\src\`
> - twindle-cli\src\twitter
> - twindle-cli\src\helper
> - twindle-cli\src\renderer
> - twindle-cli\src\utils
> 
> test specs: `twindle-cli\test\`
> - twindle-cli\test\twitter
> - twindle-cli\test\helper
> - twindle-cli\test\renderer
> - twindle-cli\test\utils
> 
> This way we can ignore the entire test module when deploying code to prod version.

Yes I agree

**Comment by proful** [comment]
PR 😇

**Comment by johnjacobkenny** [comment]
@PuruVJ you can go for this

**Comment by johnjacobkenny** [comment]
No problem, I have committed this change.
