### ISSUE TITLE
Run twindle-cli and share output below

### ISSUE THREAD

**Issue by johnjacobkenny** [twindle-co/twindle#726]
Could everyone try to take the latest code and run twindle-cli. And please post your screenshots or any issues faced, or doubts :partying_face: 

Here are couple instructions to get started,
1. Pull latest code
2. `cd` into `twindle-cli`
3. run `npm install`

then run the `index.js` file!!

BONUS: show output from Kindle mobile app (free) You can do it

**Comment by proful** [comment]
Here is my output of a thread 



![Screenshot_20201109_235946_com.amazon.kindle.jpg](https://user-images.githubusercontent.com/354596/98544265-dc13b180-22e7-11eb-83f8-66a928898a9a.jpg)

**Comment by EYRAM565** [comment]
![Screenshot (64)](https://user-images.githubusercontent.com/68958520/98546909-519f6380-228f-11eb-94cf-b7a86308262b.png)

**Comment by proful** [comment]
Great @EYRAM565 next try to send to Kindle mobile app

**Comment by vasudeveloper001** [comment]
![image](https://user-images.githubusercontent.com/56103269/98547105-aeb20e00-22bd-11eb-838c-a1f3fe03d5c9.png)

**Comment by EYRAM565** [comment]
okay.

**Comment by proful** [comment]
@EYRAM565 can you please help @vasudeveloper001 in fixing his errors.

**Comment by EYRAM565** [comment]
@vasu001 you have to node . -i then the tweet id -o instead, fetch any id at all no matter the date.

**Comment by vasudeveloper001** [comment]
Done @EYRAM565

**Comment by EYRAM565** [comment]
nice. can you try last months'?

**Comment by vasudeveloper001** [comment]
Wait, let me check. Meanwhile, I recommend this 279 tweets long thread maintained since last 2 years for our use case scenario. We will figure out all the shortcomings with this thread.

https://twitter.com/ARanganathan72/status/924574125938503680

**Comment by vasudeveloper001** [comment]
![image](https://user-images.githubusercontent.com/56103269/98548600-b83c7580-22bf-11eb-9b26-0d356380eb83.png)

**Comment by proful** [comment]
@vasudeveloper001 this is mind blowing thread. I suggest create a issue and we can collect these threads, it will be great for testing 😊

**Comment by proful** [comment]
@vasudeveloper001 add

 -p

At the end of your command and run

**Comment by vasudeveloper001** [comment]
![image](https://user-images.githubusercontent.com/56103269/98550852-9b557180-22c2-11eb-8126-0b5f69c4824e.png)

Worked this time.

**Comment by EYRAM565** [comment]
![Screenshot (66)](https://user-images.githubusercontent.com/68958520/98552079-f624a400-2295-11eb-8bf9-03c9f2fa4501.png)

**Comment by Akshay2996** [comment]
Hello everyone, I am facing issue👇 Don't know how/what to fill in place of tweet Id. Do we need to get access of the twitter api access to see the result? If so, then I have yet to get my twitter api access.

@johnjacobkenny @EYRAM565 Do see & help me out in this.
![image](https://user-images.githubusercontent.com/37118877/98554099-592e2f00-22c6-11eb-8bba-0b3bfc636556.png)

**Comment by johnjacobkenny** [comment]
> Wait, let me check. Meanwhile, I recommend this 279 tweets long thread maintained since last 2 years for our use case scenario. We will figure out all the shortcomings with this thread.
> 
> https://twitter.com/ARanganathan72/status/924574125938503680

Does this run in current implementation

**Comment by tr0mbl3y** [comment]
![Screenshot](https://user-images.githubusercontent.com/72851843/98557945-dc518400-22ca-11eb-9833-a540fa5e7eb9.png)

**Comment by johnjacobkenny** [comment]
> Hello everyone, I am facing issue👇 Don't know how/what to fill in place of tweet Id. Do we need to get access of the twitter api access to see the result? If so, then I have yet to get my twitter api access.
> 
> @johnjacobkenny @EYRAM565 Do see & help me out in this.
> ![image](https://user-images.githubusercontent.com/37118877/98554099-592e2f00-22c6-11eb-8bba-0b3bfc636556.png)
> 

@Akshay2996 tweet id is the last set of numbers in the url when you open any tweet. But right now, yes you need to have the api key to be able to try it out

**Comment by Akshay2996** [comment]
See My PDF file. Didn't expect the cli command to be simple & straight forward to use after getting twitter API access. Great work all around to the Twindle-cli Team & to everyone👏

![image](https://user-images.githubusercontent.com/37118877/98581430-7aebde00-22e7-11eb-9f4c-88ebcbb7be7d.png)

**Comment by michaelcosj** [comment]
I finally got the twitter api access!!
Here are my screenshots of twindle-cli:
![twindle-cli-scrsht](https://user-images.githubusercontent.com/49528393/98604462-fe0b3500-22e3-11eb-95c8-786fece0c2fa.png)
![twindle-cli-thread-pdf1](https://user-images.githubusercontent.com/49528393/98604519-18dda980-22e4-11eb-8545-67e970bf821b.png)
![twindle-cli-thread-pdf2](https://user-images.githubusercontent.com/49528393/98604563-30b52d80-22e4-11eb-9159-a23366957991.png)

**Comment by RafaelBatman55** [comment]
I have some doubts as well.

1. How can I get my twitter api access?
2. What is that 'token'? How can I find?

**Comment by proful** [comment]
@twindle-co/developer someone please help @RafaelBatman55

**Comment by Mira-Alf** [comment]
> I have some doubts as well.
> 
> 1. How can I get my twitter api access?
> 2. What is that 'token'? How can I find?

[Applying for developer access wiki](https://github.com/twindle-co/twindle/wiki/Applying-for-Developer-Access-from-Twitter) 

[Answering questions on Twitter access application](https://github.com/twindle-co/twindle/wiki/How-to-answer-queries-when-applying-for-Developer-Access-from-Twitter) 

Please read these two wiki pages for getting access from Twitter. 

To understand the Twitter API and how it works, read this: [Developers documentation](https://github.com/twindle-co/twindle/wiki/Twitter-Developers-Documentation) 

If you still have questions after reading these, please message on discord board or on Twitter group someone will definitely help.

**Comment by RafaelBatman55** [comment]
Thank you so much! I'll have a lot to study now!

**Comment by lh536** [comment]
This is the process step by step from the beginning.
1. First I copy the folder twindle-cli.

2. Then in a console typed `npm install`

![image](https://user-images.githubusercontent.com/37967244/98799488-2fb3f700-23dd-11eb-920b-37bce362a909.png)

3. Then `node index.js -i 1324987033039745026` and I got this message

![image](https://user-images.githubusercontent.com/37967244/98799861-ab15a880-23dd-11eb-8268-2e24a4825e69.png)

I'm trying to solve this issue, as soon as I get it solve I will post the next step.

**Comment by lh536** [comment]
> > I have some doubts as well.
> > 
> > 1. How can I get my twitter api access?
> > 2. What is that 'token'? How can I find?
> 
> [Applying for developer access wiki](https://github.com/twindle-co/twindle/wiki/Applying-for-Developer-Access-from-Twitter)
> 
> [Answering questions on Twitter access application](https://github.com/twindle-co/twindle/wiki/How-to-answer-queries-when-applying-for-Developer-Access-from-Twitter)
> 
> Please read these two wiki pages for getting access from Twitter.
> 
> To understand the Twitter API and how it works, read this: [Developers documentation](https://github.com/twindle-co/twindle/wiki/Twitter-Developers-Documentation)
> 
> If you still have questions after reading these, please message on discord board or on Twitter group someone will definitely help.

Thank you Mira!

One more question... If I don't misunderstood every member have to apply for developer access on twitter, right?

**Comment by johnjacobkenny** [comment]
Currently, in order to run the cli the user needs to have the token

**Comment by lh536** [comment]
> Currently, in order to run the cli the user needs to have the token

Thank you Kenny! I'm apply for dev-access it right now.

**Comment by shekhar10feb** [comment]
![oliver](https://user-images.githubusercontent.com/72906055/100059468-2309b700-2e51-11eb-9ae2-e1fbdbcc0673.JPG)
