### ISSUE TITLE
Ultimate Thread for testing all our use cases

### ISSUE THREAD

**Issue by vasudeveloper001** [twindle-co/twindle#728]
I hereby suggest this thread with 279 tweets, maintained since last 2 years for testing all our use cases: https://twitter.com/ARanganathan72/status/924574125938503680

Some use cases I can think of:

Able to create a thread of complete tweets using any tweetid in that thread. Basically going upward to pull the first tweet and then scroll to the bottom. Something like that. This will require a new flag, it seems.

**Comment by PuruVJ** [comment]
Holy Crap!! This is a whole book!

Our puppeteer code is simply not ready for this.

Plus, this would definitely fail on Serverless.

We'd need to test our limits.

cc @proful

**Comment by vasudeveloper001** [comment]
@PuruVJ True. You can always trust that person [Prof. Anand] to blow up any platform he goes. Lol

**Comment by Mira-Alf** [comment]
I know this tweet by Anand Ranganath. Good sample tweet @vasu001. There are some more tweets in the Indian political space which we can use but I focused on tech Twitter so far. I think trueindology and saiswaroopa also have such long threads

**Comment by vasudeveloper001** [comment]
I tried finding threads with more than 100 tweets. His threads were the only one that popped up. I think it will push our code to all test limits.

**Comment by tr0mbl3y** [comment]
another 100 + thread 
[](https://twitter.com/SethAbramson/status/925032848582639616)

**Comment by vasudeveloper001** [comment]
This shows that only politics can bring up this much length in twitter. Lol

**Comment by johnjacobkenny** [comment]
Good find @vasudeveloper001

**Comment by tr0mbl3y** [comment]
this is a long Disney thread for movies: 
[long--->](https://twitter.com/disneyplus/status/1183715613266440192)

**Comment by johnjacobkenny** [comment]
@PuruVJ do you think you could include gif in the output 😉

**Comment by PuruVJ** [comment]
@johnjacobkenny I can't add GIF, as it simply wouldn't make sense for Kindle devices, but I'll add a GIF tag and a play button, which will open up Kindle's in built browser

**Comment by PuruVJ** [comment]
The Twitter API limit we have now is 100, so no, I don't think we'd be able to do this. We could make it return the first 100 tweets.

**Comment by johnjacobkenny** [comment]
> The Twitter API limit we have now is 100, so no, I don't think we'd be able to do this. We could make it return the first 100 tweets.

Sounds good, I think the issue I raised might be because of this limit. #730
