### ISSUE TITLE
Add loading spinner while the process is happening

### ISSUE THREAD

**Issue by PuruVJ** [twindle-co/twindle#729]
It would be a nice touch to add something like https://github.com/sindresorhus/ora to improve user experience.

**Comment by arthurbuhl** [comment]
This would be a really nice addition :+1:

**Comment by michaelcosj** [comment]
I'd like to help implement this

**Comment by michaelcosj** [comment]
sorry, closed it by accident

**Comment by proful** [comment]
go ahead raise a PR @michaelcosj

**Comment by PuruVJ** [comment]
@michaelcosj Are you working on it?

**Comment by proful** [comment]
let @michaelcosj work at his own convenience
