### ISSUE TITLE
Explaning First PR to beginners with video demonstration

### ISSUE THREAD

**Issue by vasudeveloper001** [twindle-co/twindle#73]
This is going to be added to FAQ Section explaining first PR steps with video demonstration link to beginners.

Will add by tomorrow.

**Comment by piratelicorne** [comment]
Hi @vasudeveloper001 do you have a video to upload?

**Comment by vasudeveloper001** [comment]
No. I think you uploaded it already. So, I think it's better to close this issue. @piratelicorne
