### ISSUE TITLE
Error in cli

### ISSUE THREAD

**Issue by johnjacobkenny** [twindle-co/twindle#730]
`node index.js -i 924574125938503680 -s -p` (https://twitter.com/ARanganathan72/status/924574125938503680)

**TypeError: Cannot read property 'author_id' of undefined**

I am on latest main branch.

With dev=true
![image](https://user-images.githubusercontent.com/19240564/98619911-2ddd2b80-232a-11eb-88e4-57be3b84d130.png)

And this error comes for older than 7 days tweet

**Comment by PuruVJ** [comment]
How long is this thread??
