### ISSUE TITLE
PDF file name improvement

### ISSUE THREAD

**Issue by proful** [twindle-co/twindle#733]
now
❯ node . -i 1325822584269795331
Your tweets are saved into theSamParr-Nov-10-2020.pdf

expected
❯ node . -i 1325822584269795331 -a core-principles
Your tweets are saved into theSamParr-Nov-10-2020-core-principles.pdf

**Comment by madhusudanbabar** [comment]
I'm working on this

**Comment by vasudeveloper001** [comment]
I added a little improvement for the same where it checks for appendName first to decide whether to add the hyphen (-) at the end of the file or not.
