### ISSUE TITLE
Move test checking to Github Actions

### ISSUE THREAD

**Issue by PuruVJ** [twindle-co/twindle#735]
Right now, tests are run when any commit is made, locally and globally. This is undesirable, as sometimes we need to switch branches to see some code. For that we need to commit the code. This code is very unstable and simply not ready. Git husky simply doesn't allow to commit these if tests are breaking(which they definitely are, cuz the code is simply not ready). This is very inconvenient.

I recommend we move the test checking to Github Actions to check for every PR.

cc @johnjacobkenny

**Comment by johnjacobkenny** [comment]
Yeah I added an action and removed husky. See if that suits our requirement.
