### ISSUE TITLE
Remote design/image missing under " Who We Are " section under twindle-web

### ISSUE THREAD

**Issue by SarveshKadam** [twindle-co/twindle#739]
##### Image is missing under " Who We Are"  section

There no image.png file present under images folder

```
<div id='remote_design'>
        <img src='./images/image.png'/>
      </div>
```

![image](https://user-images.githubusercontent.com/66166738/98644286-4400e100-2356-11eb-8163-56e03a589e57.png)

**Comment by johnjacobkenny** [comment]
Good spot! @vasudeveloper001 @Akshay2996 @UnevenCoder

**Comment by UnevenCoder** [comment]
@teckiegeek has been working on it and testimonials section for some time now 😀, should be creating a pr hopefully tommorow
