### ISSUE TITLE
Explaining Git Branch to beginners with working video demo

### ISSUE THREAD

**Issue by vasudeveloper001** [twindle-co/twindle#74]
Will add a FAQ explaining git branch along with demo video of its working by tomorrow.

**Comment by teckiegeek** [comment]
That will be great! Thank you.

**Comment by vasudeveloper001** [comment]
I am updating the FAQ with these lines:

**What is git branching in git?**
* Git branches are alternative working directory system within git repository. 
* In essence, they are the backbone of version control and code management feature provided by git.
* Here's a video explaining the git branch in short:

This is the file that must be uploaded on Twindle YouTube Channel and linked inside FAQ
[Twindle Git beginner Issue - Branch Tutorial.zip](https://github.com/twindle-co/twindle/files/5386169/Twindle.Git.beginner.Issue.-.Branch.Tutorial.zip)

**Comment by vasudeveloper001** [comment]
@johnjacobkenny See above. I am unable to pull request as one of mine is already present for second PR. Who is uploading the YouTube Video in the channel?

**Comment by johnjacobkenny** [comment]
@proful or @piratelicorne please help with the youtube video

Regarding FAQ, please go through @piratelicorne

**Comment by piratelicorne** [comment]
Ok, I will!

**Comment by piratelicorne** [comment]
This was referenced in the FAQ document and updated in the PR #201  ✅

**Comment by piratelicorne** [comment]
@vasudeveloper001  I think this issue can be closed.
