### ISSUE TITLE
Sending pdf to my kindle email after running the command and this Error: connect ECONNREFUSED 127.0.0.1:465 occured

### ISSUE THREAD

**Issue by EYRAM565** [twindle-co/twindle#741]
![Screenshot (79)](https://user-images.githubusercontent.com/68958520/98650372-b3fc7080-2330-11eb-9638-4131c42ad582.png)

**Comment by proful** [comment]
@twindle-co/developer Error message should be improved!

**Comment by arthurbuhl** [comment]
This can be related to #717

**Comment by EYRAM565** [comment]
The issue has been resolved, for anyone wanting to yahoo mail in sending the twitter thread to kindle app
HOST=smtp.mail.yahoo.com
PORT=465
EMAIL=
PASS=(this will not be the original password to your email but rather the password generated from the Generate app password option under account security in your account info section). In generating the password you select other app in the list of options and give a name to the third party and then generate the password. Make sure you save this password because you will be using it anytime you want to send twitter threads to your kindle app. 
Also make you sure you whitelist the email address that you want to receive files from.

**Comment by proful** [comment]
Excellent @EYRAM565

**Comment by johnjacobkenny** [comment]
@EYRAM565 could you try seeing if the error message is coming correctly for you now? If yes, can close this

**Comment by EYRAM565** [comment]
yes it is .

**Comment by EYRAM565** [comment]
thanks @proful
