### ISSUE TITLE
twitter-api:token-not-passed: Please provide the token

### ISSUE THREAD

**Issue by proful** [twindle-co/twindle#744]
![image](https://user-images.githubusercontent.com/354596/98660670-aaf3b980-2399-11eb-9561-03d134c0182a.png)

@PuruVJ @tolgaerdonmez something goes wroing?

**Comment by tolgaerdonmez** [comment]
It occurs when the auth token is not in the .env file

**Comment by proful** [comment]
![image](https://user-images.githubusercontent.com/354596/98661185-4422d000-239a-11eb-8e11-05211331f721.png)

@tolgaerdonmez it is throwing a misleading error message. It worked for the second try with different id

**Comment by PuruVJ** [comment]
@proful  set DEV=true in .env, send screenshot of those logs, and also please paste the tweet ID here

**Comment by proful** [comment]
`node . -i 1280714011990913024`
![image](https://user-images.githubusercontent.com/354596/98662061-5b15f200-239b-11eb-99bf-38938414cb67.png)

**Comment by PuruVJ** [comment]
cc @Mira-Alf

**Comment by Mira-Alf** [comment]
That's odd. I will take a look at this

**Comment by PuruVJ** [comment]
@Mira-Alf You may wanna take a look at the _renderEmbeddedTweets function in the rich-renderer.js I'm running a getTweetByID there too, so the error might have something to do  with it.

I'm already looking, but would be nice to have an extra pair of eyes
