### ISSUE TITLE
CLI epub the download message should be displayed on DEV=true

### ISSUE THREAD

**Issue by proful** [twindle-co/twindle#748]
![image](https://user-images.githubusercontent.com/354596/98663118-c90ee900-239c-11eb-8f7c-e0a20a8017fb.png)

**Comment by tolgaerdonmez** [comment]
There is an option called `verbose` in the package, and it defaults to `false` but still it prints the logs. I tried setting it manually to`true` & `false` but always prints the logs.

**Comment by PuruVJ** [comment]
Anyone working on this @twindle-co/developer ?

**Comment by tolgaerdonmez** [comment]
The problem with this is the epub-gen module, like you've said the package is a bit broken with the option `verbose`
I'll send a issue but they're not active

**Comment by Mira-Alf** [comment]
Also I noticed some other problems with this regard - when one of the images is not available for download or there is an error while downloading, then the entire epub file gets corrupted. These are issues with the epub-gen NodeJS module

**Comment by PuruVJ** [comment]
I think we need to implement our own algo to download images and replace the src attribute with `data:` path

**Comment by tolgaerdonmez** [comment]
> I think we need to implement our own algo to download images and replace the src attribute with `data:` path

After the svelte components are done, it can be easily handled by our components in svelte

**Comment by PuruVJ** [comment]
This issue is too broad. Closing it in favour of a new issue regarding encoding images.
