### ISSUE TITLE
Colliding issue with some files.

### ISSUE THREAD

**Issue by pranavgoel29** [twindle-co/twindle#75]
### I have synced the repo once again recently and their are two file which are conflicting with each other, one is ['tushar.md'](https://github.com/twindle-co/twindle/blob/main/firstpr/tushar.md) and another one is ['TUSHAR.md'](https://github.com/twindle-co/twindle/blob/main/firstpr/TUSHAR.md) below is the terminal snap to show the error.

<img width="649" alt="conflicting error" src="https://user-images.githubusercontent.com/48860494/96033462-baa4de80-0e7d-11eb-8a86-419af633fe82.png">

### And when I am trying to update one file another one gets automatically updated too and in local machine only one file is visible

![image](https://user-images.githubusercontent.com/48860494/96033821-3c950780-0e7e-11eb-8b68-f44a8c92caed.png)

You can see only one file is present.

![image](https://user-images.githubusercontent.com/48860494/96033995-84b42a00-0e7e-11eb-979d-b8f8e73f6aaf.png)

### **'Possible solution to solve this issue would be using a file naming like 'Firstname_lastname.md'**

**Comment by pranavgoel29** [comment]
@johnjacobkenny Please check this.

**Comment by proful** [comment]
Can you remame the upper case file and raise a PR

**Comment by pranavgoel29** [comment]
@proful I renamed the upper case file to solve this issue.

**Comment by pranavgoel29** [comment]
I am closing this issue as it is solved now.

**Comment by johnjacobkenny** [comment]
Thanks @pranavgoel29 for helping out. I'm guessing that you are on windows. Windows treats files with the same characters as one file. It is not case sensitive. However on *nix machines these are two separate files. That is what happened here.

@piratelicorne Could add this example for our FAQ 🙂

**Comment by pranavgoel29** [comment]
@johnjacobkenny It happened for Mac users too.

**Comment by johnjacobkenny** [comment]
Oh, then I must be wrong about the reason. 😂 If anyone else knows what happened, please comment so that it's documented.

**Comment by pranavgoel29** [comment]
The reason is right but Windows and Mac both do that because they both are case insensitive.

**Comment by piratelicorne** [comment]
I thought it was a Windows issue too, but when I clone it in a Mac, the message of "files collided" appeared, I honestly don't know why. 🧐 it's true that in a Mac you can have 2 different files with the same name but with a difference of upper and lower case, but for some reason when it's downloaded from github, it doesn't recognize as 2 diff files 🤷🏽‍♀️ 
So it's better to avoid it.
