### ISSUE TITLE
Twitter TOS - Scraping may be a problem

### ISSUE THREAD

**Issue by johnjacobkenny** [twindle-co/twindle#752]
![image](https://user-images.githubusercontent.com/19240564/98673630-a0c3c200-237d-11eb-94b5-480237c7128f.png)
https://twitter.com/en/tos

**Comment by Mira-Alf** [comment]
Interesting.. We are only scraping the ids from the page - not the explicit content of Twitter and then using the Twitter API to fetch all data related to the tweets. But I guess this would still be a violation.

**Comment by proful** [comment]
![image](https://user-images.githubusercontent.com/354596/98886293-e0a6b880-24e7-11eb-9f80-04b2081fb027.png)
https://twitter.com/robots.txt

**Comment by proful** [comment]
https://github.com/twintproject/twint/issues/659
https://github.com/twintproject/twint/issues/313
https://github.com/twintproject/twint/issues/241

**Comment by proful** [comment]
We will keep reading more about scrapping & try to avoid using itit.
