### ISSUE TITLE
Cli bug twitter api fetching

### ISSUE THREAD

**Issue by proful** [twindle-co/twindle#756]
![image](https://user-images.githubusercontent.com/354596/98757782-5b58d080-2421-11eb-9129-4673d5874ca2.png)
[Example thread](https://twitter.com/david_perell/status/1307811967428702208)

`node . -i 1307811967428702208`

**Comment by vasudeveloper001** [comment]
I am working on this issue. Others can continue to work as well as festive season started here.

**Comment by Mira-Alf** [comment]
I tried the same tweet id and this issue seems resolved. I think this can be closed.

**Comment by vasudeveloper001** [comment]
Yes, it now seems to be pulling the whole thread.
