### ISSUE TITLE
CLI PDF rendering of embedded tweets

### ISSUE THREAD

**Issue by proful** [twindle-co/twindle#765]
`node . -i 1280714011990913024`
https://twitter.com/elamje/status/1280714011990913024
![image](https://user-images.githubusercontent.com/19240564/98934205-bd8c0100-2507-11eb-9dbf-4b9fce624c60.png)

![image](https://user-images.githubusercontent.com/354596/98796895-05efe400-2460-11eb-933e-4061bf195309.png)

Please add left & right margin to tweet contents

**Comment by proful** [comment]
@shekhar10feb do you want to give it a try?

**Comment by frankiefab100** [comment]
I would like to work on this

**Comment by shekhar10feb** [comment]
> 
> 
> @shekhar10feb do you want to give it a try?

Yes, I will

**Comment by proful** [comment]
@frankiefab100 I will assign another ticket for you

Let @shekhar10feb take care of it

**Comment by frankiefab100** [comment]
Alright

**Comment by proful** [comment]
@shekhar10feb and @frankiefab100 any update?

**Comment by PuruVJ** [comment]
Actually I added the padding long ago 😅
