### ISSUE TITLE
CLI PDF changes to profile

### ISSUE THREAD

**Issue by proful** [twindle-co/twindle#766]
![image](https://user-images.githubusercontent.com/354596/98802841-fd031080-2467-11eb-9a66-a5ccb62da6c9.png)

Move Thread created to after Number of tweets
@frankiefab100 can you start looking at it

**Comment by frankiefab100** [comment]
Okay, I'm going to do that

**Comment by frankiefab100** [comment]
Please where can I locate this?

**Comment by PuruVJ** [comment]
> Please where can I locate this? 

It's in rendering/templates/Thread.hbs

Beware! The CSS there is extremely messy and haphazard, what with me adding rendering features like crazy!

Stay sharp. 

Thanks for your contributions

**Comment by frankiefab100** [comment]
@PuruVJ Alright, thank you.
