### ISSUE TITLE
CLI user fetch thread created date

### ISSUE THREAD

**Issue by proful** [twindle-co/twindle#771]
![image](https://user-images.githubusercontent.com/354596/98881934-43478680-24df-11eb-8277-79d255f6152e.png)
Threadcreated:Mar14,2009
This date should be CLI run date.

`node . -u dvassallo -n 10`

@Mira-Alf you no need to fix this. Let someone new to the codebase fix this.

**Comment by PuruVJ** [comment]
What exactly is the issue here? Shouldn't we be showing the date the thread was created on, in the right place?

**Comment by SarveshKadam** [comment]
@proful Can I take this?

**Comment by PuruVJ** [comment]
> @proful Can I work on this issue?

Anyone is free to jump in and tweak stuff. In fact we encourage it😉

**Comment by SarveshKadam** [comment]
@PuruVJ Do correct me if I'm wrong. I think this is related to hbs templates under the 'renderer' folder.
Let me know

**Comment by PuruVJ** [comment]
> @PuruVJ Do correct me if I'm wrong. I think this is related to hbs templates under the 'renderer' folder.
> 
> Let me know

The date generation and manipulation happens in the file I started above. You'll find a statement don't datetime formatting. It needs to be changed to the current date.

**Comment by tr0mbl3y** [comment]
in utils/date.js u have to do this --> `const formatTimestamp = () => format(new Date(), "MMM d, yyyy");` this will give current date.

**Comment by proful** [comment]
It should be set to today's date only when passing user ID.

No changes when reading threads

**Comment by tr0mbl3y** [comment]
woops! that i didn't notice let me see

**Comment by PuruVJ** [comment]
> in utils/date.js u have to do this --> `const formatTimestamp = () => format(new Date(), "MMM d, yyyy");` this will give current date.

No no! This is a common util function and should stay so. The change needs to happen in user_timeline.js only. formatTimestamp(new Date().toString()) should do it.

**Comment by tr0mbl3y** [comment]
i made changes in `useer-timeline-endpoint.js`
previous: ` resp.common.created_at = formatTimestamp(user.created_at);`
now: ` resp.common.created_at = formatTimestamp(new Date());`
now its working

**Comment by tr0mbl3y** [comment]
> > in utils/date.js u have to do this --> `const formatTimestamp = () => format(new Date(), "MMM d, yyyy");` this will give current date.
> 
> No no! This is a common util function and should stay so. The change needs to happen in user_timeline.js only. formatTimestamp(new Date().toString()) should do it.

yes i realised that i was changing the whole global function which would change dates everywhere

**Comment by PuruVJ** [comment]
@tr0mbl3y Good work! make your PR, we'll review and merge it.
