### ISSUE TITLE
CLI PDF rendering twitter profile clickable link

### ISSUE THREAD

**Issue by proful** [twindle-co/twindle#772]
![image](https://user-images.githubusercontent.com/354596/98882409-42632480-24e0-11eb-8197-de80d0e34ce1.png)
`node . -u dvassallo -n 10`
Make dvassallo clickable link. https://twitter.com/dvassallo

**Comment by SarveshKadam** [comment]
@proful Would like to work on this

**Comment by frankiefab100** [comment]
@SarveshKadam you can go ahead

**Comment by SarveshKadam** [comment]
@proful Is this the expected change, made the username clickable, and it navigates to the Twitter profile in PDF as shown below.

![username](https://user-images.githubusercontent.com/66166738/99141381-e7ad0280-2670-11eb-8dca-db6b4a4af484.png)

**Comment by johnjacobkenny** [comment]
Yes looks good! Create a PR @SarveshKadam

**Comment by SarveshKadam** [comment]
Have created a PR @johnjacobkenny once you have time, could you please review it and link the PR to this issue. 
<br>
Link to PR mentioned below

[PR Link](https://github.com/twindle-co/twindle/pull/800)

**Comment by johnjacobkenny** [comment]
Yeah @SarveshKadam I have edited the description so that it gets linked
