### ISSUE TITLE
Low priority VSCODE issues

### ISSUE THREAD

**Issue by proful** [twindle-co/twindle#786]
![image](https://user-images.githubusercontent.com/354596/99019665-f03e0400-25b0-11eb-9002-91b5cfe06dbf.png)

**Comment by PuruVJ** [comment]
Does restarting work?

**Comment by PuruVJ** [comment]
Check this out https://github.com/motdotla/dotenv/issues/475

**Comment by johnjacobkenny** [comment]
Had the same issue, came across the same thread, did not find a resolution.

**Comment by PuruVJ** [comment]
Is it causing any issues? Or is it just a warning in the Problems tab?
