### ISSUE TITLE
CLI epub embedded tweet missing

### ISSUE THREAD

**Issue by proful** [twindle-co/twindle#788]
![image](https://user-images.githubusercontent.com/354596/99056159-ff8f7280-25ed-11eb-8a9a-57c42139c81e.png)
`node . -i 1326999228636409864 -f epub`

**Comment by PuruVJ** [comment]
Reason for that is it uses Thread-epub.hbs, which Tolga copied and modified from the Thread.hbs file before I added in the embedded tweets

cc @tolgaerdonmez

**Comment by tolgaerdonmez** [comment]
Okay then, I'll send a pr

**Comment by tolgaerdonmez** [comment]
@proful I've fixed the problem, but design needs to be changed. with that I can deal on Sunday.
