### ISSUE TITLE
CLI Not able to convert thread to PDF 

### ISSUE THREAD

**Issue by proful** [twindle-co/twindle#789]
[Example](https://twitter.com/jackbutcher/status/1306589668352425984)
[Example](https://twitter.com/david_perell/status/1169981379620290560)

Naval one also breaking https://twitter.com/naval/status/1002103360646823936

Many threads are failing.

Only one page appearing

`node . -i 1306589668352425984`

@PuruVJ @Mira-Alf @tolgaerdonmez @johnjacobkenny

**Comment by tr0mbl3y** [comment]
no problem with latest threads its problem when getting older threads

**Comment by PuruVJ** [comment]
This could be a problem with scraping. Scraping looks for `time` tags, but because embedded tweets don't have those, it simply maynot be recognizing them.

**Comment by proful** [comment]
Naval thread was working earlier
