### ISSUE TITLE
CLI epub profile page 

### ISSUE THREAD

**Issue by proful** [twindle-co/twindle#792]
![Screenshot_20201113_231148](https://user-images.githubusercontent.com/354596/99071180-bd722b00-2605-11eb-9584-63fa817a8b05.jpg)
Image missing

**Comment by tolgaerdonmez** [comment]
Didn't I solve this ?

**Comment by PuruVJ** [comment]
Solved by Tolga. Correct me if I'm wrong.

**Comment by tolgaerdonmez** [comment]
> Solved by Tolga. Correct me if I'm wrong.

I think Shekhar solved it.

**Comment by tolgaerdonmez** [comment]
But we can create a nice cover image by converting html canvas to image

**Comment by tolgaerdonmez** [comment]
Is this for the cover ? or the part that has user info ? @proful

**Comment by proful** [comment]
This is for user profile. Some one need to confirm whether it works in offline mode

**Comment by tolgaerdonmez** [comment]
I've solved offline profile page long ago, closing this  then.
