### ISSUE TITLE
CLI epub tweet issue 

### ISSUE THREAD

**Issue by proful** [twindle-co/twindle#793]
![Screenshot_20201113_231324](https://user-images.githubusercontent.com/354596/99071273-e4306180-2605-11eb-8467-3fc01464bd68.jpg)

Android app: ReadEra

List item aligned little bit off.

**Comment by SarveshKadam** [comment]
@proful seems like this issue is only occurring in **ReadEra** App

The List item is looking good in other apps such as **Lithium**(Android) and **Books**(iOS)

![lithiumApp](https://user-images.githubusercontent.com/66166738/99785066-ac17aa00-2b42-11eb-9341-412412d29742.png)

**Comment by PuruVJ** [comment]
Seems the problem here is regarding specific Reader apps and how they interpret and epub file, not with epub itself. Closing
