### ISSUE TITLE
CLI epub cover page design 

### ISSUE THREAD

**Issue by proful** [twindle-co/twindle#795]
![Screenshot_20201113_232809_org readera](https://user-images.githubusercontent.com/354596/99072383-062ae380-2608-11eb-8896-397612a93eec.jpg)
Cover page needs to be improved

**Comment by PuruVJ** [comment]
@twindle-co/developer Anyone on this?

**Comment by tolgaerdonmez** [comment]
@PuruVJ I've got some ideas.

**Comment by joelvinaykumar** [comment]
![CoverPage - Monochrome](https://user-images.githubusercontent.com/16177724/101015866-062a5d80-358e-11eb-8972-b32b47c8d377.png)
![CoverPage](https://user-images.githubusercontent.com/16177724/101015922-17736a00-358e-11eb-96d2-ee2b1cd911fa.png)

Let me know your opinions

**Comment by PuruVJ** [comment]
It looks good.

One question. Is that logo finalized?

I'm more in favour of the current one(Or mine too 😏)

**Comment by joelvinaykumar** [comment]
No, consider it a placeholder. Guess we need to finalize any one logo.

**Comment by tolgaerdonmez** [comment]
I liked the design, I'm going to implement this after finished with svelte rendering.

**Comment by PuruVJ** [comment]
Not needed for now
