### ISSUE TITLE
CLI EPUB Unicode support 

### ISSUE THREAD

**Issue by proful** [twindle-co/twindle#796]
Few characters or symbols not displayed

![Screenshot_20201113_233105](https://user-images.githubusercontent.com/354596/99072598-76396980-2608-11eb-8de1-c7a610676e75.jpg)

**Comment by proful** [comment]
![Screenshot_20201113_233259_org readera](https://user-images.githubusercontent.com/354596/99072690-a08b2700-2608-11eb-8778-b7a583f914f4.jpg)

**Comment by PuruVJ** [comment]
That shouldn't happen. There shouldn't be any unicode characters, as all emojis are converted to images beforehand.

**Comment by PuruVJ** [comment]
Apparently, it's getting the emojis-as-images, but its unable to render them, so its rendering the alt attribute instead, which is the unicode emoji. WPS reader is rendering its own weird emojis(not Windows emojis, its own emojis), and nothing is breaking for me.

This is highly irregular, as the block images are being rendered perfectly(in WPS reader at least). We need to look into it deeper

What are your thoughts @tolgaerdonmez ?

**Comment by tolgaerdonmez** [comment]
I see no errors about emojis, but while offline user images was not being saved, I solved the user images problem. If there's more let me know, sending a PR

**Comment by PuruVJ** [comment]
I think the problem is with Proful's epub reader, as WPS reader rendered them. They were different than the OS's stock emoji library, but they were there.

**Comment by tolgaerdonmez** [comment]
> I think the problem is with Proful's epub reader, as WPS reader rendered them. They were different than the OS's stock emoji library, but they were there.

Yeah emojis is about that but not images.
