### ISSUE TITLE
twindle-thread Thread Bookmark & Management

### ISSUE THREAD

**Issue by proful** [twindle-co/twindle#803]
### Technical Stack

- Backend express js with MySQL
- Frontend svelte
- code Deployed on AWS (taken are by Proful)

### Feaures
- Save a new thread
- fetch who created, like, retweets
- store in db
- display in HN ways
- better to have tags like github label
- filter/sorting based on recent, more RT, more likes, user
- no authentication
- Puru: Would need a basic admin interface to find and delete. 

### Twitter API
- minimal usage
- if you want to use twitter api (it is fine to use "https://api.twitter.com/2/tweet?id=123)
- clean up code we don't need

[![tutorial](https://img.youtube.com/vi/yKL-6QXKQMw/0.jpg)](https://www.youtube.com/watch?v=yKL-6QXKQMw).

Design can be as simple as possible. (Inspiration)
![image](https://user-images.githubusercontent.com/354596/99158880-c3fac280-272b-11eb-9e57-522f9ea955d9.png)

**Comment by PuruVJ** [comment]
This seems like a Twindle web feature. I'm all in for it.

**Comment by tolgaerdonmez** [comment]
Me too!

**Comment by PuruVJ** [comment]
I think It would be better to hit the Twitter API everytime to get likes and retweets, as these are ever changing.

**Comment by proful** [comment]
@PuruVJ it not needed to be that dynamic.

We can talk more about it. Please don't call each time. It doesn't add significant value.


Later we can update daily by script but that is not necessary now.

**Comment by joelvinaykumar** [comment]
Hey, does this mean a user can create account to save their twindles ?

**Comment by PuruVJ** [comment]
> Hey, does this mean a user can create account to save their twindles ?

Not at the moment. We'll add that in later when traffic gets out hand

**Comment by joelvinaykumar** [comment]
That would be a great feature to do something like pocket.now
But, maybe yeah...we should concentrate on stable build first

**Comment by PuruVJ** [comment]
Removing `future` tag. The Future is here.

**Comment by PuruVJ** [comment]
This issue will stay open for a while, and every single PR related to Twindle Threads will be referenced here, to keep track of everything that has been happening.

When Twindle Threads initial version stabilises, we can close this, and make more focused issues

**Comment by PuruVJ** [comment]
Taking a brief break from Twindle Thread to work on the new svelte templates.

I'm getting a serious analysis paralysis that comes only with designing stuff. So I'm gonna indulge in plain code for now, do not worry about designing and stuff.

**Comment by PuruVJ** [comment]
Would be great if somebody would continue this project in my absense.

I've been the only one since, and it's good to have more people jump in. It's foundation is set enough that people can easily contribute without anybody's personal coding styles conflicting too much.

**Comment by proful** [comment]
@all-contributors please add @PuruVJ  for code, mentoring

**Comment by PuruVJ** [comment]
Scrapped for now
