### ISSUE TITLE
Twitter API fetch tweet and reply by author 

### ISSUE THREAD

**Issue by proful** [twindle-co/twindle#818]
- input: Twitter id
- output:
  User profile information 
  Tweet details 
       Person who ask question
       Author reply

Ignore replies where author not replied

**Comment by Mira-Alf** [comment]
Quick question proful, so in this issue, you dont want the original thread, simply the replies to which the author replied?

**Comment by proful** [comment]
Any conversation by author.

So the answer is yes we want the thread as well.

But start with simple tweet with out thread.

**Comment by PuruVJ** [comment]
Fixed by Mira
