### ISSUE TITLE
CLI multiple thread bugs

### ISSUE THREAD

**Issue by proful** [twindle-co/twindle#823]
![image](https://user-images.githubusercontent.com/354596/99360771-3377da00-2905-11eb-8703-dca52cec74f2.png)
`node . -i 1307811967428702208,1169981379620290560,1323317674466775041,1309681736079597568,1321111764851920902,1259539005097426944 -o david-perell-fix -f epub`

- Error should show the specific thread where error happened

@Mira-Alf

**Comment by PuruVJ** [comment]
Mira fixed it.
