### ISSUE TITLE
CLI github reading MD file - fetch

### ISSUE THREAD

**Issue by proful** [twindle-co/twindle#840]
https://github.com/ryanmcdermott/clean-code-javascript/blob/master/README.md

[![tutorial](https://img.youtube.com/vi/2SyHZglZZFo/0.jpg)](https://www.youtube.com/watch?v=2SyHZglZZFo).

**Comment by johnjacobkenny** [comment]
[test.pdf](https://github.com/twindle-co/twindle/files/5576903/test.pdf)

**Comment by proful** [comment]
Looks awesome @johnjacobkenny

**Comment by johnjacobkenny** [comment]
I don't think I will have the time to implement it correctly, here is the main code so someone else can take inspiration.

```js
const nodeFetch = require("node-fetch");
const marked = require("marked");

const fetch = async (url) => {
  const response = await nodeFetch(url);
  console.log(response);
  const body = await response.text();

  return body;
};

const fetchMarkdownFromGithubURL = async () => {
  const md = await fetch(
    "https://raw.githubusercontent.com/twindle-co/twindle/main/docs/articles/git%20-github-related.md"
  );
  const html = marked(md);
  return html;
};

module.exports = {
  fetchMarkdownFromGithubURL,
};

```

**Comment by johnjacobkenny** [comment]
And here is a pdf from the link mentioned by Proful 
[ryanmcdermott.pdf](https://github.com/twindle-co/twindle/files/5576920/ryanmcdermott.pdf)

**Comment by SarveshKadam** [comment]
@proful @johnjacobkenny 

For the first stage, I've taken some baby steps towards this task by building a sample code locally.

In my root folder, I pass the below command

`node app.js md --f="<GitHub URL>"`

`md` is the custom action command we passed and  `--f` is the custom argument which takes the GitHub URL

For example below

`node app.js md --f="https://github.com/ryanmcdermott/clean-code-javascript/blob/master/README.md"`

On the passing the GitHub URL it first of all parses the URL to a Raw markdown code

Then the raw markdown code is then converted to HTML format

Then this HTML is stored locally using file-system module 

Please refer the below gif

![githubparse](https://user-images.githubusercontent.com/66166738/99902754-2f253580-2ce6-11eb-9cdb-e3a166768940.gif)

Please do let me know if I am moving in the right direction.

**Comment by proful** [comment]
This looks awesome and you are in perfect direction.

**Comment by johnjacobkenny** [comment]
@SarveshKadam Yess! :partying_face:

**Comment by SarveshKadam** [comment]
@proful @johnjacobkenny 

Added dynamic fileName for the generated HTML File

Naming convention for the file will be the `<GitHubUsername>_<RepositoryName>.html`

For example, for the below-mentioned URL 

`https://github.com/ryanmcdermott/clean-code-javascript/blob/master/README.md`

The fileName will be `ryanmcdermott_clean-code-javascript.html`  as shown in the image.

The next steps will be to integrate my code into our twindle codebase for which I'll create a folder under `twindle-cli/src/<github folder>`

Will look into it since I need to get familiar with our codebase and puppeteer itself

![filenamegit](https://user-images.githubusercontent.com/66166738/99938412-ba0d3b00-2d8d-11eb-8ba6-7260e6e7aff3.png)

**Comment by proful** [comment]
Very good progress @SarveshKadam

**Comment by SarveshKadam** [comment]
@Mira-Alf @proful 

Able to produce PDF now [ryanmcdermott_clean-code-javascript.pdf](https://github.com/twindle-co/twindle/files/5589944/ryanmcdermott_clean-code-javascript.pdf)

![image](https://user-images.githubusercontent.com/66166738/100096235-c1157580-2e81-11eb-857a-f7bf6d2c0480.png)

**Comment by SarveshKadam** [comment]
@proful 

The PDF conversion functionality is working as expected, therefore have created PR.

However, in some readme files, there are full-screen size images as shown in this readme [Readme URL](https://github.com/twindle-co/twindle/blob/main/docs/articles/sync-to-main-repo.md)

Such kind of full-screen images broke in PDF as shown below which we need to fix

![image](https://user-images.githubusercontent.com/66166738/100118053-77398900-2e9b-11eb-9b1f-90f5b5b4c37a.png)

**Comment by Mira-Alf** [comment]
All problems have been fixed. And now we have a fully functioning module.
