### ISSUE TITLE
CLI github error message

### ISSUE THREAD

**Issue by proful** [twindle-co/twindle#852]
![image](https://user-images.githubusercontent.com/354596/100164116-501aa000-2f0b-11eb-8903-c5bdb1574cb3.png)

`node . -g https://github.com/ryanmcdermott/clean-code-javascript`

This error message is perfect.

One suggestion. Remove the highlight (background color). Only use red font color for the error message.

@SarveshKadam you no need to fix. Let some beginner address this issue.

**Comment by PuruVJ** [comment]
Whoever is working on it, also fix the spelling mistake (haaving) too please.

Thank you

**Comment by SarveshKadam** [comment]
That the typo was corrected in the previous PR

**Comment by PuruVJ** [comment]
OK

**Comment by SarveshKadam** [comment]
This issue is redundant now, we can close it
