### ISSUE TITLE
CLI github output to A5 size

### ISSUE THREAD

**Issue by proful** [twindle-co/twindle#855]
- A5 size
- Larger font

**Comment by PuruVJ** [comment]
It is A5 size already.
Larger font - That can be done. how much larger? Current font size is 108%, or `17.28px`. What do you think

**Comment by proful** [comment]
@PuruVJ are you talking about github md pdf?

**Comment by PuruVJ** [comment]
No.

There's a github md pdf too?

Please update the title to indicate the fact it's related to Github Rendering Pipeline

**Comment by PuruVJ** [comment]
Is it resolved?

**Comment by proful** [comment]
it is looking good in Kindle. Doesn't look like A4.

**Comment by PuruVJ** [comment]
I still think we should at least experiment in A5 a little.

What can go wrong, only change needed of 2 letters 😁

**Comment by Mira-Alf** [comment]
I dont understand this issue. The PDF is being rendered in A5 format already right?
`await page.pdf({
      path: outputPath,
      format: "A5",
      margin: {
        bottom: 52, // minimum required for footer msg to display
        left: 20,
        right: 20,
        top: 10,
      },
      printBackground: true,
      displayHeaderFooter: true,
      footerTemplate: footerMarkup(),
      headerTemplate: "<div></div>",
    });`

I see the above code and the format is clearly A5. Am I missing something?
