### ISSUE TITLE
CLI Github multiple link to single pdf

### ISSUE THREAD

**Issue by proful** [twindle-co/twindle#879]
`node . -g input.txt`

-g should be intelligent.
Able to distinguish between a github url or a txt file

input.txt
https://github.com/kentcdodds/react-fundamentals/blob/main/src/exercise/01.md
https://github.com/kentcdodds/react-fundamentals/blob/main/src/exercise/02.md
https://github.com/kentcdodds/react-fundamentals/blob/main/src/exercise/03.md

@SarveshKadam @Mira-Alf

**Comment by Mira-Alf** [comment]
* The -g has been improved to recognize a single url ending with .md format or a .txt file. The txt file must be placed inside github\input folder as shown below:
![image](https://user-images.githubusercontent.com/64691316/101298317-63a30080-3853-11eb-9f76-ae11e013a35a.png)

* A sample input.txt file shown below
![image](https://user-images.githubusercontent.com/64691316/101298395-c3011080-3853-11eb-8fc9-474c339361ea.png)

* Now running the command 
`node . -g input.txt` 
produces the following output
![image](https://user-images.githubusercontent.com/64691316/101298440-f5ab0900-3853-11eb-9a66-6964e9a70bf4.png)

* The output pdf has the details about all three MD files

`

**Comment by Mira-Alf** [comment]
I am closing this issue, if anyone faces any errors feel free to reopen it @SarveshKadam kindly review this since it incorporated your code changes #898
