### ISSUE TITLE
CLI github file name update

### ISSUE THREAD

**Issue by proful** [twindle-co/twindle#880]
❯ node . -g https://github.com/kentcdodds/react-fundamentals/blob/main/src/exercise/01.md

⠏ Loading    /Users/sanvi/all/code/github/twindle/twindle-cli/TwindleLibrary/kentcdodds-Jun-1-2019.pdf
✔ Your data saved into kentcdodds-Jun-1-2019.pdf

File name should be kentcdodds-react-fundamentals-Dec-3-2020.pdf
Dec-3-2020.pdf >> when the CLI Run

**Comment by shekhar10feb** [comment]
![working](https://user-images.githubusercontent.com/72906055/101130693-f2343980-3629-11eb-803a-d1ac845fee29.JPG)

It is working!!
