### ISSUE TITLE
Error on executing GitHub MD command if Twitter API AUTH Token is not provided

### ISSUE THREAD

**Issue by SarveshKadam** [twindle-co/twindle#889]
**Observation:** Error on executing GitHub MD command if Twitter API AUTH Token is not provided

#### Steps to Reproduce:

1.) Prerequisite: Do not provide twitter API key or configure your `.env` file

2.) Run the command `node . -g https://github.com/kentcdodds/react-fundamentals/blob/main/src/exercise/01.md`

3.) Verify if the PDF is generated successfully 

#### Expected Result: 
Github action should not be dependant on Twitter API configuration

#### Actual Result:

![image](https://user-images.githubusercontent.com/66166738/101167426-de0b2f00-365f-11eb-8a1c-6063a237bf5d.png)

**Comment by Mira-Alf** [comment]
This has been fixed in PR #904 - order of environment variable evaluation was moved around - I tested this and looks fixed. @sarvesh you can try this once to make sure it is all okay. I am closing this issue now, if you have any issues reopen this issue
