### ISSUE TITLE
Change in naming convention of file generated via GitHub MD

### ISSUE THREAD

**Issue by SarveshKadam** [twindle-co/twindle#890]
Currently, we are using the naming conventions 

`<GitHub Username>-<Repository Name>-<CLI Run Date>.pdf`

For eg. : `kentcdodds-react-fundamentals-Dec-5-2020.pdf`

This will give an error if you want to fetch another `.md` file from the same repository on the same day and also it will override your existing file.

Here's my suggested filename 

`<GitHub Username>-<Repository Name>-<MD File name>-<CLI Run Date>.pdf`

For eg. : `kentcdodds-react-fundamentals-01-Dec-5-2020.pdf`

**Comment by Mira-Alf** [comment]
@sarvesh this was a good catch, I am now extracting the file name along with branch and repo details - so using that to compute file name as you have described it here
![image](https://user-images.githubusercontent.com/64691316/101298816-c09fb600-3855-11eb-926a-4d702c5df25c.png)

Closing this issue.
