### ISSUE TITLE
HackerNews Fetching  based on Parameter

### ISSUE THREAD

**Issue by proful** [twindle-co/twindle#894]
`node . -h 25301437 -n 5 -d 3`

-n 5 >> How many top-level comment to fetch
-d 3 >> How many depths (or nested comment) to go for each comment

**Comment by Mira-Alf** [comment]
The -n argument is used as numTweets in cli.js and yargs command line argument I have it specified to default to 10 tweets. I am not sure how to reuse the same argument for hackernews as for HN it should default to 5 and also validation of arguments becomes a little tricky. Currently you can run the hackernews test as follows:
`node . -h <<hackernews id>> -t <<numTopLevelComments>> -d <<depthOfNestedComments>>`

If someone else wants to take a look at cli.js to reuse the same -n argument that would be great.

**Comment by tr0mbl3y** [comment]
we can make it consistent by making default ```numTweets/numTopLevelComments = 10``` this way we could reuse ```n```. if you agree i will take a look.
