### ISSUE TITLE
HackerNews Article title enhancement

### ISSUE THREAD

**Issue by proful** [twindle-co/twindle#895]
![image](https://user-images.githubusercontent.com/354596/101230348-ee231d00-36f8-11eb-8d69-ad2bab36f078.png)

![image](https://user-images.githubusercontent.com/354596/101230406-422e0180-36f9-11eb-9d15-1589efcdd7d5.png)

Image can be left

**Comment by Mira-Alf** [comment]
The title section has been modified as follows:
![image](https://user-images.githubusercontent.com/64691316/101371931-54fb2e80-38d1-11eb-9df8-bd1f02e9ffae.png)

I am closing this issue for now. If anyone has any other interesting designs for this, feel free to reopen this issue
