### ISSUE TITLE
Need Dark Theme for twindle-web

### ISSUE THREAD

**Issue by Akshay2996** [twindle-co/twindle#902]
## Important Pointers

- Implement dark theme (shades of black)
- Use CSS variables in the **:root selector** in different CSS file or use CSS variables in body class like done by @PuruVJ  in this file https://github.com/PuruVJ/puruvjdev2/blob/main/static/css/themes.css
- Use [HappyHues](https://www.happyhues.co/) for the dark theme inspiration

**PS: Anyone up for the task can take this & inform it here in this issue after taking the task**

**Comment by PuruVJ** [comment]
Additional note for anyone reading this:

Body mode is much more easier, as all you have to is put a different class on body, whereas for root, you need to set every single variable in JS, and chances of messing up stuff is more.

**Comment by frankiefab100** [comment]
I would like to work on this

**Comment by PuruVJ** [comment]
Scrapped for now
