### ISSUE TITLE
Slider Presentation for Testimonials in twindle-web

### ISSUE THREAD

**Issue by Akshay2996** [twindle-co/twindle#903]
## Important Pointers

- Testimonials should be slided to another after a period of time (Use **Javascript setTimeout function** for this)
- Use inspiration from https://designmodo.com/examples-sliders-web-design/ for slider presentation
- Remove the button or remove popping out the button to divert the attention of the user to the text instead of the buttons shown in the image below 👇 which is wrong

![image](https://user-images.githubusercontent.com/37118877/101275336-dae08200-37ca-11eb-993e-d234b53e8e0a.png)

**PS: Anyone up for the task can take this & inform it here in this issue after taking the task**

**Comment by joelvinaykumar** [comment]
Can we please try the updated the [design](https://www.figma.com/file/34YX1uk6ZVhQWVzLyjzUdG/Twindle?node-id=0%3A1)

There is no point in asking a user to see another testimonial. This should be an automatic carousel.

**Comment by Akshay2996** [comment]
> Can we please try the updated the [design](https://www.figma.com/file/34YX1uk6ZVhQWVzLyjzUdG/Twindle?node-id=0%3A1)
> 
> There is no point in asking a user to see another testimonial. This should be an automatic carousel.

That is what we are going for right now. It should automatically slides to another testimonial after a certain period of time instead of clicking it.

Looking for someone to implement it.

**Comment by PuruVJ** [comment]
I say we get rid of right left buttons all together. Move the profile photo to the top, and add 3 dots to bottom

**Comment by joelvinaykumar** [comment]
@PuruVJ  Your advice sounds right. But, we might lose the horizontal real estate and we need to pack everything in a line. Hence, the horizontal layout.
And, for a more realistic effect, we can do something like this : "The sentences are typed and it is paused for 5-7 seconds for user to read"

**Comment by PuruVJ** [comment]
Packing everything in a single line isn't bad @joelvinaykumar. Or you could make this carousel like multiple showing at once, like Netflix or Disney+

**Comment by joelvinaykumar** [comment]
![image](https://user-images.githubusercontent.com/16177724/101479932-fa1d1200-3978-11eb-8e9b-03c5c0781f9d.png)
Something like this ?

**Comment by PuruVJ** [comment]
Perfectio 👌

**Comment by joelvinaykumar** [comment]
In this case, we can move the active dots to bottom

**Comment by devarshidoshi** [comment]
Is anyone working on testimonial part??

**Comment by PuruVJ** [comment]
Scrapped for now
