### ISSUE TITLE
Banner needed for Twindle-web

### ISSUE THREAD

**Issue by Akshay2996** [twindle-co/twindle#907]
![image](https://user-images.githubusercontent.com/37118877/101317345-55b9a380-3884-11eb-86cb-2f342d394b85.png)

## Important Pointers

- Replace the Banner shown above 👆 to show something meaningful that relates to our project.
- Take inspiration from [Notion](https://www.notion.so/), [Pocket](https://getpocket.com/), [Remarkable](https://remarkable.com/) & other sites for the banner.

**For Illustrations see these sites:**
- [Undraw](https://undraw.co/)
- [ls.graphics](https://www.ls.graphics/free-mockups)
- See other Illustration sites too for the banner
- Post your suggestions with **Screenshot** here in the Issue or in the Discord server

**PS: Anyone up for the task can take this & inform it here in this issue after taking the task**

**Comment by PuruVJ** [comment]
Scrapped for now
