### ISSUE TITLE
Create a Terms & Conditions page for Twindle-web

### ISSUE THREAD

**Issue by Akshay2996** [twindle-co/twindle#908]
## Important Pointers

- This will be a separate page which will be linked to twindle-web landing page.
- **For reference:** See other sites **Terms & Conditions page** & copy, paste their content & modify it to the Twindle project's demand.

**PS: Anyone up for the task can take this & inform it here in this issue after taking the task**

**Comment by PuruVJ** [comment]
I don't think this is important at this point of time, as no one has any idea what are terms and conditions, let alone the person trying to write the legalese.

I think it should be closed for now. Way too much in future.

Your call Akshay.

**Comment by Akshay2996** [comment]
> I don't think this is important at this point of time, as no one has any idea what are terms and conditions, let alone the person trying to write the legalese.
> 
> I think it should be closed for now. Way too much in future.
> 
> Your call Akshay.

You're right Puru. Had a discussion with proful & he said we can copy paste the **Terms & Conditions** from other site & modify it according to our project. And we have to do this in the future too so not a priority as of now.

**Comment by PuruVJ** [comment]
Let's close it for now. It's way too much in future. We can always reopen it or create new issue
