### ISSUE TITLE
Redesign Footer for twindle-web

### ISSUE THREAD

**Issue by Akshay2996** [twindle-co/twindle#913]
![image](https://user-images.githubusercontent.com/37118877/101596188-a82cc880-3a1a-11eb-91d3-126316855c19.png)

- What type of footer we currently have 👆

## Important Pointers

- Replace the footer to make it look more appealing
- Reference some professional sites to get a better understanding of the footer

#### See links 👇 for footer designs
- https://hookagency.com/website-footers/
- https://weblium.com/blog/15-website-footer-examples-best-footer-designs-for-your-inspiration/
- https://www.mockplus.com/blog/post/website-footer-design

**Comment by lh536** [comment]
@Akshay2996 great! I'll take this! Right now I'm a little busy solving some personal problems, but I think on weekend I'll work on it.

**Comment by Akshay2996** [comment]
@lh536 See the footer design of this site. It's minimal & looks great https://100daysof.codes/ Lets design somewhat of this style per say.

**Comment by joelvinaykumar** [comment]
Sure @Akshay2996  Use the 100daysof.codes design

**Comment by praveen2896** [comment]
I am working on it

**Comment by frankiefab100** [comment]
@Akshay2996 how do you see this footer? 
![Footertwindle landing](https://user-images.githubusercontent.com/46662771/103323088-88009000-4a41-11eb-8171-22d5c80b375f.jpg)

**Comment by Akshay2996** [comment]
> @Akshay2996 how do you see this footer?
> ![Footertwindle landing](https://user-images.githubusercontent.com/46662771/103323088-88009000-4a41-11eb-8171-22d5c80b375f.jpg)

This looks amazing to me 🤩 Raise a PR @frankiefab100 & match the color to the whole site, try to make it uniform.

**Comment by frankiefab100** [comment]
@Akshay2996 Alright.

**Comment by johnjacobkenny** [comment]
Looks awesome! @frankiefab100

**Comment by PuruVJ** [comment]
Scrapped for now
