### ISSUE TITLE
Modular Styling in New Svelte templates

### ISSUE THREAD

**Issue by PuruVJ** [twindle-co/twindle#915]
@tolgaerdonmez has done really good work by converting from HBS to Svelte.

However, it's still using global CSS, which completely defeats the purpose of moving to Svelte.

Someone should take on this task of putting the correct CSS in the correct components, and also modifying selectors to overall simplify the code.

**Comment by PuruVJ** [comment]
All that work is happening in the `renderer-svelte` branch

**Comment by Akshay2996** [comment]
> All that work is happening in the `renderer-svelte` branch

I have seen the code!! If I get the time I can work on that but don't want to give any false hope quite busy with some work. And label the Issue to design too if we have to make changes in the CSS part only.

**Comment by PuruVJ** [comment]
Resolved in #940
