### ISSUE TITLE
Introduce Twindle Web to Prettier

### ISSUE THREAD

**Issue by PuruVJ** [twindle-co/twindle#932]
Twindle CII and Twindle Thread both have prettier configs in them, and devs more or less follow it. I think we should introduce Prettier in Twindle Web.

For those not familiar with prettier or how to set it up, please read https://puruvj.dev/blog/setup-prettier-vscode

What are your thoughts @twindle-co/developer ?

**Comment by frankiefab100** [comment]
I agree with you. I will help make the project have a consistent format.

**Comment by Akshay2996** [comment]
It's a great suggestion @PuruVJ But I think everybody working on twindle-web already have prettier installed as an extension in VSCode as far as I know & the formatting of the code is looking great for the twindle-web due to the prettier extension. Regardless, we should have a discussion on it to encourage people about this.

**Comment by PuruVJ** [comment]
> I agree with you. I will help make the project have a consistent format.

Good! 

It's very easy to format it in the beginning, it's just one command for all files.

The problem is maintaining formatting as more code is written. We have to encourage people to format their files as they are writing the code. 

The blog post I referenced above is for people who need to learn this. It can be gently enforced on the whole project. Whenever someone who does not have auto-formatting set up makes a PR, we can have it approved, but refer this blog post. Not hard and fast, gently. We have to **gently** make everyone adopt this practice. It will be mutually beneficial for us and them.

**Comment by PuruVJ** [comment]
> It's a great suggestion @PuruVJ But I think everybody working on twindle-web already have prettier installed as an extension in VSCode as far as I know & the formatting of the code is looking great for the twindle-web due to the prettier extension. Regardless, we should have a discussion on it to encourage people about this.

I agree @Akshay2996, but the thing is that you have to press the shortcut keys to format, and you have to remember to do that. For example, a recent PR done by Devarshi Doshi has weird formatting at some places. It was formatted by hand, not by prettier. So yes, having a 5-lines long prettierrc file won't harm anyone, and it will enforce consistent styling across the 3 projects, which is quite needed.

Twindle CLI is using 2-space indentation, while Twindle Web is using 4 space indentation. There are these small consistencies.

What happens if some new novice dev comes, and puts in code with 8 as indentation? (Plausible, if that person has  a monitor)

We would need to hand-fix that code or ask that person to re-indent everything by hand.

And prettierrc is needed because different people may have different prettier settings built into VSCode.

**Comment by PuruVJ** [comment]
All right, I'm gonna go ahead and introduce prettier. No harm in doing so
