### ISSUE TITLE
Formatting differences between the main branch and the svelte branch

### ISSUE THREAD

**Issue by Mira-Alf** [twindle-co/twindle#937]
This is primarily for documenting the differences:
a) A tweet with a link
[FrancescoCiull4-Dec-14-2020.pdf](https://github.com/twindle-co/twindle/files/5689098/FrancescoCiull4-Dec-14-2020.pdf)
[main_sample4.pdf](https://github.com/twindle-co/twindle/files/5689099/main_sample4.pdf)
b) A tweet with an embedded youtube link
[DThompsonDev-Dec-14-2020.pdf](https://github.com/twindle-co/twindle/files/5689101/DThompsonDev-Dec-14-2020.pdf)
[main_sample2.pdf](https://github.com/twindle-co/twindle/files/5689102/main_sample2.pdf)
c) A tweet with an image
[CajigoApp-Dec-13-2020.pdf](https://github.com/twindle-co/twindle/files/5689108/CajigoApp-Dec-13-2020.pdf)
[main_sample3.pdf](https://github.com/twindle-co/twindle/files/5689109/main_sample3.pdf)
d) A tweet with an embedded tweet
[Adithya_BGoT-Dec-14-2020.pdf](https://github.com/twindle-co/twindle/files/5689110/Adithya_BGoT-Dec-14-2020.pdf)
[main_sample4.pdf](https://github.com/twindle-co/twindle/files/5689111/main_sample4.pdf)

The files with the name main in it are generated from the main branch.
Please leave comments.

**Comment by PuruVJ** [comment]
Closing, as all these are resolved now.
