### ISSUE TITLE
Replies section in Twitter Svelte template shows Replies heading even without any replies in them

### ISSUE THREAD

**Issue by Mira-Alf** [twindle-co/twindle#950]
## Description with command
I am not sure if this is a renderer issue or the json issue - will need to check this.
Command needed to replicate this: 
`node . -i 1339510645125828609 -r`

## Screenshot
![image](https://user-images.githubusercontent.com/64691316/102632919-b8a91580-4175-11eb-8317-5198043a5727.png)

**Comment by proful** [comment]
@all-contributors please add @Mira-Alf  for code, mentoring

**Comment by PuruVJ** [comment]
@Mira-Alf is it fixed now?

**Comment by PuruVJ** [comment]
All right It's fixed. Closing this
