### ISSUE TITLE
Hackernews - duplication of comments in the output PDF when there are few comments

### ISSUE THREAD

**Issue by Mira-Alf** [twindle-co/twindle#951]
## Problem Description
I tried running this command:
`node . -h 25467545`

The last comment is repeated twice. 

## Screenshot
![image](https://user-images.githubusercontent.com/64691316/102634103-636e0380-4177-11eb-9519-a14ba647fe22.png)
![image](https://user-images.githubusercontent.com/64691316/102634127-6963e480-4177-11eb-912e-7c72786da9d4.png)

@tr0mbl3y and I discussed something similar but thought we had fixed this - we will take another look at it. 
@tr0mbl3y please leave your comments here!

**Comment by tr0mbl3y** [comment]
![Screenshot from 2020-12-18 23-48-21](https://user-images.githubusercontent.com/72851843/102650170-76d99880-4190-11eb-85b6-5a10c3f70c48.png)
--> fixed one on right side
