### ISSUE TITLE
twitter cli naval profile pdf looks empty with many white spaces

### ISSUE THREAD

**Issue by proful** [twindle-co/twindle#954]
![image](https://user-images.githubusercontent.com/354596/102688077-700e5c80-4248-11eb-8241-1b35d0d69c0b.png)

`node . -i 1002103360646823936`

**Comment by proful** [comment]
@all-contributors please add @proful  for code, mentoring and ideas

**Comment by PuruVJ** [comment]
I don't know what to solve in this? His description is empty. Pointers from anyone?

**Comment by PuruVJ** [comment]
Wait It's fixed 😅. Closing for now.
