### ISSUE TITLE
Adding contributor list to twindle

### ISSUE THREAD

**Issue by proful** [twindle-co/twindle#962]

**Comment by proful** [comment]
@all-contributors please add @johnjacobkenny   for code, mentoring

**Comment by proful** [comment]
@all-contributors please add @Mira-Alf  for code, mentoring

**Comment by proful** [comment]
@all-contributors please add @Mira-Alf  for code, mentoring

**Comment by proful** [comment]
@all-contributors please add @Akshay2996  for code, design

**Comment by proful** [comment]
@all-contributors please add @shekhar10feb   for code

**Comment by proful** [comment]
@all-contributors please add @shekhar10feb for code

**Comment by proful** [comment]
@all-contributors please add @tolgaerdonmez  for code

**Comment by proful** [comment]
@all-contributors please add @UnevenCoder  for code

**Comment by proful** [comment]
@all-contributors please add @SarveshKadam  for code

**Comment by PuruVJ** [comment]
If no more contributors are to be added, can it be closed?
