### ISSUE TITLE
Github Markdown formatting issues

### ISSUE THREAD

**Issue by Mira-Alf** [twindle-co/twindle#987]
* When an image or a link was added in the MD file, originally the links didnt work because they had relative paths like './images/image-001.png' - these links for images and hrefs broke in the PDF output
* I fixed it by replacing the pattern './' with the url of the repository - all was good and it worked for most of the cases
* I observed some cases where the above pattern for links and images sometimes begins like this 'images/image-001.png' - in this case my solution will not work and some images and links dont work. A good example:
`node . -g https://github.com/donnemartin/system-design-primer/blob/master/README.md`
* The above file has a lot of images broken
* It also has a lot of the links broken because the header tag ids get messed up and the anchor links no longer work
* Please try the above command and if anyone understands the problem and has a fix for it, please make a commit. Or please leave comments as to what can be done.

**Comment by johnjacobkenny** [comment]
This could be an option - https://stackoverflow.com/a/7995298/8323067

The idea is to provide an `onerror` handler which will set the image to some default image that we provide.

**Comment by PuruVJ** [comment]
@Mira-Alf Are these solved?

**Comment by Mira-Alf** [comment]
I havent tried this. Leaving this issue open for now.

**Comment by PuruVJ** [comment]
@simrin051 is taking over this issue
