### ISSUE TITLE
List of pending svelte template changes

### ISSUE THREAD

**Issue by Mira-Alf** [twindle-co/twindle#988]
## So far
@tolgaerdonmez  did an enormous job by starting the migration to svelte templates. We have done a few live coding sessions for this now and now svelte templates are ready for PDF generation of 
* Tweet threads
* User timeline tweets
* Github markdown files
* Articles of URLs
* Hackernews comments - styling is left here

## What remains?
* The epub module continues to use handlebars for the above sources except for Twitter - so this needs to be done
* Hackernews svelte templates dont have styling at this point of writing this issue
* epub formatting needs to be checked with various readers and sources
* Retire handlebar hbs files to playground once they are no longer needed since they are cluttering up the space
* Some code reorganization and plenty of Unit Testing

I know I probably shouldnt have combined the issues into a single issue but I wanted to document all pending things at this point before I take a break for the move. Feel free to close this if it is irrelevant.

**Comment by johnjacobkenny** [comment]
Should I take up something from this?
