### ISSUE TITLE
Daily Call Meeting notes

### ISSUE THREAD

**Issue by johnjacobkenny** [twindle-co/twindle#99]
## 14-Oct-2020

About 45/60 joined.

* Walkthrough of Github repository/organization
* Domain `twindle.co` purchased by @proful 
* Collaborate using twitter, gh, sketchnotes - keep low number of tools to use, maybe consider other options if we grow a lot
* FAQ page will be created. [It was created here](https://github.com/twindle-co/twindle/blob/main/docs/FAQ.md)
* Split teams into
   * Beginner (bare minimum experience)
   * Independent (can work independently/mentor)
   * Active (say organizers)

## Week 1

* everyone get onboard with setting up github account, clone repo, make changes to files
* fork process (after cloning the repo)
   * draft PR from gh website
   * draft PR from laptop
* which client to use for git - need to pick one from github desktop, sourcetree, gitlens
* a brief explanation about PR
* touched on logo design
* break up the project into smaller chunks
* why no hacktober fest - keep PRs minimum, not doing this for freebies
* tech stack - html, css, js (nodejs)
* touch on naming convention, coding standard, e.g. google standard, airbnb standard
* importance of testing and using Jest for js testing
* documentation is critical, any features can be added to issues
* touch on how to make a cli, showed an example
* twitter API integration discussion, creating a mock API (JSON file)
* renderer - render to PDF/ePub/mobi, etc.

Thanks @sarathkumar6 for documenting, does anyone have any points to add

**Comment by johnjacobkenny** [comment]
@Sheetal777 you may move this and the upcoming meeting notes to a page on the wiki called "Meeting Notes". This can be a single page with the latest meeting note for each day coming at the top, i.e. reverse chronological order

**Comment by Sheetal777** [comment]
### Week-1 Day-2
### 15-Oct-20200
About 50 joined.

- Talks about initial success of Twindle.
- Overwhelming responses received: 100+ PRs, 90+ PRs merged.
- Appreciation to all the team members who have contributed.

#### First Experience with Github
- Detailed discussions on PRs
- 5/6 participants talked about their first PR experience (wonderful).
- Touched base on being a 'Contributor' is more important than being the one who 'Merges', however, being a 'Contributor' is more important. (Need few gate keepers to avoid many chefs in the kitchen - scenario)
- Importance of being a Code Reviewer.

#### General
- Technical discussions must be refrained from Twitter groups.
- Must use GitHub issues actively.
- Touched base on Versioning. (discussed in an issue)
- Not everyone has access to label the issues. However, project owners can do that.
- FAQ documentation was created by 2 members.
- Try to share relevant information on 'Resources' documentation in the GitHub Repositories.
- Touched base on Naming conventions of File and Folder level naming directory scaffolding.
- Try to come up with some information on naming conventions.
- Directions on creating the 3rd PR by making changes on TEAM.md (compulsory).
- Try to capture recording on making PRs locally.
- Two members are looking into CLI, Twitter API, PDF, and, ePUB Design.
- Figma: Prototyping Software.
- Experiment with color theme and we can finalize the theme once we can finish logo design.
- Coding plan will be discussed step by step consequently.
- For any help you can raise any number of issues in the repo.

**Comment by Sheetal777** [comment]
@johnjacobkenny Okay, its noted. That would be a clearer option.

**Comment by johnjacobkenny** [comment]
This is moved to wiki [Meeting Notes](../wiki/Meeting-Notes)

**Comment by UnevenCoder** [comment]
@johnjacobkenny  why is this issue still pinned ?

**Comment by johnjacobkenny** [comment]
Just so people who used to look for it in the issues section can easily get it. May be worth adding the same link in the Readme and then unpinning once people are used to it.
