### ISSUE TITLE
UX: Auto open generated PDF for preview

### ISSUE THREAD

**Issue by johnjacobkenny** [twindle-co/twindle#994]
It would be nice to have a feature to automatically open up the PDF that is generated :smiley:

**Comment by Mira-Alf** [comment]
This sounds like a wonderful idea. Is it possible to do this natively in NodeJS or some dependency?

**Comment by johnjacobkenny** [comment]
https://www.npmjs.com/package/open

This package works for me on linux :smile:

**Comment by PuruVJ** [comment]
Maybe we should have a flag for this, like --open or something
